### ISSUE TITLE
Free trial: Implement tracking for new UIs

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1003]
We'll need to add tracking for all new UI implemented for free trial.

### Acceptance criteria

1. Achieve relevant metrics (all work done by Ghidorah) as defined in peapX7-1PC-p2
1. Alternatively, this issue could be to identify and design all tracks including props if required, and then implement them in a follow-up issue.

**Comment by adrianduffell** [comment]
So far, the highest priority Tracks are implemented for launch.

Internal reference: peapX7-1PC-p2#comment-2107

**Comment by adrianduffell** [comment]
An additional Track event was identified for the Upgrade Now button in the completion banner.

![image (4)](https://user-images.githubusercontent.com/9312929/222774526-8edd8e19-f007-403c-b64d-1482a5f1a11f.png)
