### ISSUE TITLE
v0.1 for free trial expiration

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1005]
We need to decide what a user will see when their free trial expires. I would suggest we limit it to the plans/upgrade page.

**Comment by that-mike-bal** [comment]
Requires additional investigation

**Comment by that-mike-bal** [comment]
MVP may be something like a modal/landing page version of the plans page with an update to make the expired free trial more obvious. Limited to purchase a plan - nothing else.

**Comment by that-mike-bal** [comment]
We're going to design option two, which includes the monthly vs annual pricing. 
We're going to redirect users in the free trial expiration to a single page, so we don't have to duplicate the page in Calypso and wp-admin. 

After they click the CTA - it will take them directly to checkout, reflecting their selection for monthly/annual.

**Comment by manospsyx** [comment]
I've assigned this to Serenity; I think it's been discussed a few times that Serenity is ultimately the bottleneck here and that SW can't help. cc @xristos3490 @daledupreez

**Comment by that-mike-bal** [comment]
@daledupreez I thought the jetpack deploy would handle wp-admin redirects but I am still able to access wp-admin directly via URL for expired free trial sites.

**Comment by xristos3490** [comment]
@that-mike-bal This will be included in The Bridge. Here's the PR: https://github.com/Automattic/wc-calypso-bridge/pull/1055

**Comment by daledupreez** [comment]
We have now shipped Calypso and wp-admin redirects across the following changes:
 * https://github.com/Automattic/jetpack/pull/29423
 * https://github.com/Automattic/wp-calypso/pull/74335
 * https://github.com/Automattic/wc-calypso-bridge/pull/1055

Closing this issue.
