### ISSUE TITLE
Free trial: Create task header component for "Add a domain" task

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1008]
Task header for `Add a domain` needs to be built

## User Story

> As a free trial user, 
> I want to see task header when the current task is `Add a domain`
> so that I'm informed of what the task is about

## Acceptance Criteria

```
Feature: `Add a domain` header
Given the user is on a free trial plan
When the user views WooCommerce homescreen
Then show task header
```

![Image](https://user-images.githubusercontent.com/3747241/222042669-cbea38a8-95aa-4f8e-86f2-c3a2c4f90ab7.png)

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-278%3A10816

**Comment by xristos3490** [comment]
Thanks for raising this one. I've worked in the past on this in core here: https://github.com/woocommerce/woocommerce/pull/35553

I guess that we do have slots now to work with, so the PR above should be closed as soon as we done with it!

**Comment by xristos3490** [comment]
I guess we'd also need a similar issue for the "Launch your store" task.

**Comment by ilyasfoo** [comment]
Thanks for reminding us, @xristos3490!

@chihsuan Since you're working on this, would you be able to adopt Chris' work? I'm open to also include "Launch your store" task as well

**Comment by chihsuan** [comment]
Yes, definitely! 🙂
