### ISSUE TITLE
Enhance "Add a domain" task completion logic

### ISSUE THREAD

**Issue by xristos3490** [Automattic/wc-calypso-bridge#1016]
### Describe the solution you'd like

Currently, the system checks the value of the `siteurl` option to determine whether the site has a domain. Recently, @rjchow  discovered that the domain registration might take some time, in which the site URL remains untouched, resulting in a false indication of the task completion. 

As @daledupreez shared in the Slack thread (p1677739481181539-slack-C01SFMVEYAK), a better way to ensure the completion logic always reflects the state is to use the following snippet:
```php
$purchases = wpcom_get_site_purchases();
$domain_purchases = array_filter(
  $purchases,
  function ( $purchase ) {
    $product_type = $purchase['product_type'] ?? '';
    return $product_type === 'domain_map' || $product_type === 'domain_reg';
  }
);
```

**Comment by adrianduffell** [comment]
@ilyasfoo Would PR #1083 close this issue?

**Comment by ilyasfoo** [comment]
Good catch, @adrianduffell! Yes, I think the PR resolves this issue. Closing
