### ISSUE TITLE
Free trial: Update notice messages and other copies

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1019]
We need to update free trial notices to reflect latest changes from p1677673565835379/1677509212.632429-slack-CNA89KY6M.

#### Free trial notices

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-49%3A7986

- **Payments task:** Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](url).
- **Tax task (New notice, I've missed it before):** During the free trial period you can configure your sales tax settings, but not collect it. To start selling products, [upgrade now](url).

Figma: 1EGipzzulCg2uk4MsSf2x7-fi-14%3A7215

- **WCPay welcome screen, WCPay overview screen:** Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](url).
- **WCPay transactions screen:** Only Administrators and Store Managers can place orders during the free trial. If you are ready to accept payments from customers, [upgrade to a paid plan](url).
 - **WCPay deposits screen:** Deposits are not available during the trial period. To start processing real transactions and receive payments and payouts, [upgrade to a pain plan](url).

#### Payments task fill header

<img src="https://user-images.githubusercontent.com/3747241/222486238-c38aa821-423f-4b58-991a-9becd0fa1fdf.png" width="500">

- Get ready to accept payments

#### Payments task header description

<img src="https://user-images.githubusercontent.com/3747241/222487242-4ed3a8eb-0dd8-47d9-bf08-402519c5d341.png" width="500">

- Give your customers an easy and convenient way to pay! Set up and test some of our fast and secure online or in person payment methods.

### Acceptance criteria

1. Update all copies from latest changes in figma

**Comment by chihsuan** [comment]
Nvm. I found it!

1EGipzzulCg2uk4MsSf2x7-fi-14%3A5786
