### ISSUE TITLE
Free trial: Customize "Personalize your store" task

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wc-calypso-bridge#1028]
Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-56%3A8230

Customize "Personalize your store" task  for free trial

<img width="1440" alt="Home _ Editor _ Upload a logo@2x (1)" src="https://user-images.githubusercontent.com/4344253/223080467-f8bb2c52-b3ae-431d-96e0-b52ff2aef61a.png">

![Home _ Editor _ Store notice](https://user-images.githubusercontent.com/4344253/224623565-26a5f8df-4856-4132-b896-eff2ddf651a9.png)

### Acceptance criteria

1. Remove the "Create a custom homepage" step
2. Remove the default store notice. Leave it blank. https://github.com/Automattic/wc-calypso-bridge/blob/master/includes/class-wc-calypso-bridge-themes-setup.php#L106

**Comment by adrianduffell** [comment]
Could these changes be implemented in Core directly?

**Comment by chihsuan** [comment]
AFAIK, these changes are for free trial only, and the notice is added by the Bridge.

**Comment by adrianduffell** [comment]
Hey @chihsuan , I've been digging into this a bit.

I think Core needs to be smarter about how it detects whether the homepage is configured.

In the task, there is, a check to hide this step when the homepage is explicitly set in [appearance.js](https://github.com/woocommerce/woocommerce/blob/04f34e9636bfdd67c1533c5c5ec3f5fb043e74ba/plugins/woocommerce-admin/client/tasks/fills/appearance.js#L30-L33). This is derived from [Appearance.php has_homepage()](url), which checks the WordPress homepage setting. However, the Woo Express theme (Tsubaki) uses default template handling and doesn't need to have a homepage explicitly set. Overall this causes the step to appear in the task:

<img width="742" alt="Screen Shot 2023-03-17 at 12 32 48 pm" src="https://user-images.githubusercontent.com/9312929/225815699-e003aea6-ef13-4616-beec-e5f9d993dc2b.png">

I think we could make the task smarter in a future project. However for now, as a temporary hotfix, we could possibly hardcode an array of theme slugs to always `return true` in Core's `has_homepage()`.

**Comment by chihsuan** [comment]
@adrianduffell Thanks for looking into it! 😃 

> I think we could make the task smarter in a future project. However for now, as a temporary hotfix, we could possibly hardcode an array of theme slugs used by Woo Express to always return true in Core's has_homepage().

Sounds good to me!

**Comment by FlorianBru** [comment]
Hey @adrianduffell and @chihsuan,
Just getting up to speed after my AFK time. So I was wondering, did we just remove the 'create your homepage' step for Woo Express?

**Comment by chihsuan** [comment]
Hey @FlorianBru Welcome back! 👋 It's still under [PR](https://github.com/Automattic/wc-calypso-bridge/pull/1054) review. We removed the `create your homepage` step for Woo Express theme (Tsubaki). Does that sound good to you?
