### ISSUE TITLE
Remove the handling of extensions' hidden menu items in Calypso navigation and port it to each extension

### ISSUE THREAD

**Issue by xristos3490** [Automattic/wc-calypso-bridge#1035]
### Describe the solution you'd like

We fixed the initial issue in Ecommerce sites at https://github.com/Automattic/wc-calypso-bridge/pull/994

Recently, I discovered that the issue isn't coupled with the menu structure on Ecom plans and needs to be addressed in all plans. 

See the example of a business site:
<img width="1725" alt="Screenshot 2023-03-09 at 2 18 51 PM" src="https://user-images.githubusercontent.com/1105590/224021584-9d234645-78a3-4680-9dcb-4cc7f7f213c2.png">

This issue should track the removal of this code part as soon as we port the changes to each extension.

**Comment by that-mike-bal** [comment]
@xristos3490 - is this something we need Serentity to tackle or do you know where the source of truth for the nav/menu is?
