### ISSUE TITLE
Align wide all block-based checkout pages 

### ISSUE THREAD

**Issue by xristos3490** [Automattic/wc-calypso-bridge#1042]
### Description

Currently, we create block pages using the default (no-align) setting in the containers of the Cart and Checkout block. This creates a long and narrow template for the checkout experience. 

This issue aims to modify the cart's page container and checkout pages to align with the wide container (as the page title). 

Given that the block/checkout blocks are working with container-based "media queries, " the result would be significantly better.

**Comment by that-mike-bal** [comment]
@xristos3490 are you fixing this as part of your theme optimization work or is this something we need to queue up or have another team work on?

**Comment by xristos3490** [comment]
It would make sense to move this with all the other site editor defaults, but it's a straightforward fix that I already pushed here: https://github.com/Automattic/wc-calypso-bridge/pull/1043 ; I plan to release it early next week.

**Comment by adrianduffell** [comment]
@that-mike-bal I've moved this to SW as @xristos3490 already has a PR for it in flight
