### ISSUE TITLE
Add Product Checklist Step Cleanup - Should be a fresh product and the wizard/tour needs to be updated/removed

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1045]

**Comment by that-mike-bal** [comment]
### Description

When you click on the "add product" from the task list, it takes you to the product editor with what should be a new product BUT with content from an existing product. There is also a wizard that pops up and points to add a product description that shouldn't be there?



![Image](https://user-images.githubusercontent.com/89872780/224375701-e9d86fb6-8ec2-40c8-8e7f-c65eced94a26.png)

### Checklist 

- [ ] Should *not* be pre-populated content for a new product
- [ ] BEau doesn't think he wizard/tour should be there

**Comment by ilyasfoo** [comment]
The `Start typing your new product name here` should be addressed in this issue since it came from core. I'll create another issue for it

**Comment by ilyasfoo** [comment]
I'm having some trouble figuring out the underlying issue, posted a comment in this p2 peapX7-1V3-p2#comment-2674

**Comment by ilyasfoo** [comment]
Closing this issue in favour of https://github.com/woocommerce/woocommerce/issues/38136.

We've decided to keep the spotlight tour but remove sample data.
