### ISSUE TITLE
Copy Update - store looking great message

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1046]

**Comment by that-mike-bal** [comment]
Just need a space after the emoji in the message that says "Your store is looking great!...."



![Image](https://user-images.githubusercontent.com/89872780/224379414-ea867005-feca-4977-a888-b77ef00c851c.png)

**Comment by ilyasfoo** [comment]
Moved issue to https://github.com/woocommerce/woocommerce/issues/38040
