### ISSUE TITLE
Remove purchase task from free trial

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1056]
In p1679343077752069-slack-C01SFMVEYAK, we identified that purchase task was marked as completed and mislead the funnel track numbers.

Since purchase task is not applicable for free trial, we should remove it.

**Comment by chihsuan** [comment]
@ilyasfoo I guess we need to remove the task even if the user upgrades the store to a paid plan, correct?

**Comment by ilyasfoo** [comment]
@chihsuan Yes, that's correct
