### ISSUE TITLE
Site/Store Name not rendering special characters

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1064]
I updated my store name to be "Mike's Essential Store" in the site settings. 
I went back to "My Home" 
The store name displayed as `Mike&#039;s Essential Store`

![Image](https://user-images.githubusercontent.com/89872780/229923738-04044dfb-286e-466c-970b-9c2ebee96ac5.png)

We need to make sure this is displaying correctly with store names that use special characters.

**Comment by chihsuan** [comment]
Should be fixed by https://github.com/woocommerce/woocommerce/issues/36246.

**Comment by chihsuan** [comment]
I just found out that we need to fix it in Bridge as well.

https://github.com/Automattic/wc-calypso-bridge/blob/5606d638794b6f30320104e9a0e9acc7d171ad8f/src/homescreen-progress-header/progress-title.tsx#L85
