### ISSUE TITLE
Improve Upgrade CTA on task list

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1068]
We need to make the CTA to upgrade to a paid plan more compelling in the task list. We should use some outcome-focused copy like "Upgrading now unlocks....." or "Upgrade now and start selling sooner."

Edited by Ilyas:

### Acceptance criteria

1. In tasklist, update `Upgrade to a paid plan to unlock the next tasks` to `Upgrade to a paid plan to unlock more features and start selling`

**Comment by warrendholmes** [comment]
@FlorianBru Do you need any help on this?

**Comment by warrendholmes** [comment]
@verofasulo or @lauroraa Did we have make any changes to this? Looking at the figma, I don't think so lD0gTB4IqGsmSmsnjZNaP6-fi-2157%3A19583

**Comment by lauroraa** [comment]
Hi @warrendholmes and @FlorianBru! Sorry I haven't spent much time in Github and so only tend to see things when I'm tagged 🙈 Mostly through fear of clicking the wrong thing!

But yes, I totally agree. I think this was legacy content from when it wasn't clear when folks would be able to start selling, so would love to get it updated. My suggested wording would be:

Upgrade to a paid plan to unlock more features and start selling

Florian, let me know if you need this in Figma as well 😊
