### ISSUE TITLE
Automated deploy script for bridge

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1082]
Based on a recent incident on WooExpress, as @chihsuan suggested, the bridge plugin needs script(s) to automate the release process similar to wpcomsh.

Ideally, these scripts would also need to do post-build checks in order to make sure the build was done correctly. It should provide a clear error whenever it fails so that the user would not mistakenly upload a failed build.

Additionally, we should consider updating some npm dependencies.

### Acceptance criteria

1. ~~Whenever a build fails, the script should provide error messages~~
2. ~~The deployment script should run checks on build result prior to releasing a new version~~
3. ~~The deployment script should check for production build~~
4. Update the deployment instructions in readme

**Comment by ilyasfoo** [comment]
Looks like 1 - 3 would be accomplished by https://github.com/Automattic/wc-calypso-bridge/issues/1096, https://github.com/Automattic/wc-calypso-bridge/issues/1099, and https://github.com/Automattic/wc-calypso-bridge/issues/1101

**Comment by adrianduffell** [comment]
@ilyasfoo I think item 4 is completed now with https://github.com/Automattic/wc-calypso-bridge/pull/1135. Would that allow us to close this issue?
