### ISSUE TITLE
Unable to Add Multiple Videos After Upgrading from Woo Express: Trial to Woo Express: Essentials

### ISSUE THREAD

**Issue by masperber** [Automattic/wc-calypso-bridge#1089]
### Describe the bug

The Woo Express: Trial plan level allows customers to upload only one videos. After purchasing Woo Express: Essentials, the customer should be able to upload more videos. However, after purchasing Woo Express: Essentials, customers are allowed to upload the videos, but VideoPress refuses to process them. If you click on the video in the site Media Library, you will encounter this message:

>Trial plans are limited to a single video.
>Upgrade now to upload more videos!

### Expected behavior

After upgrading to a paid Woo Express plan, the customer should be allowed to upload more videos, and VideoPress should not give the message noted previously.

### Steps to reproduce

1. Start a site with Woo Express: Trial
2. Navigate to Media and switch to use the Classic View.
3. Upload one video to the Media Library. The video will upload successfully.
4. Upload another video to the Media Library. The video will upload, but it cannot be used. Clicking on the video in the Media Library will give the message: Trial plans are limited to a single video. Upgrade now to upload more videos!
5. Purchase an upgrade to Woo Express: Essentials.
6. Upload another video to the Media Library. The same behavior will occur, and VideoPress does not recognize that the customer has upgraded to a paid plan.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://woo-fortunately-krispy-lady.wpcomstaging.com
Site address (URL): https://woo-fortunately-krispy-lady.wpcomstaging.com
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 4.99MB
Database Data Size: 2.18MB
Database Index Size: 2.81MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.31MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
jetpack_migration: 2
page: 9
post: 1
product: 4
revision: 2
wp_global_styles: 1
wp_navigation: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Akismet Anti-Spam: by Automattic – 5.1
AutomateWoo: by WooCommerce – 5.7.2
Crowdsignal Forms: by Automattic – 1.6.7
Facebook for WooCommerce: by Facebook – 3.0.19
WordPress.com Editing Toolkit: by Automattic – 3.63212
Google Listings and Ads: by WooCommerce – 2.4.2
Gutenberg: by Gutenberg Team – 15.6.1
Jetpack: by Automattic – 12.1-a.7
Layout Grid: by Automattic – 1.8.2
Page Optimize: by Automattic – 0.5.3
Pinterest for WooCommerce: by WooCommerce – 1.2.19
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.10

TikTok: by TikTok – 1.0.16
WooCommerce Back In Stock Notifications: by WooCommerce – 1.4.3
WooCommerce Brands: by WooCommerce – 1.6.47
WooCommerce Gift Cards: by WooCommerce – 1.15.4
WooCommerce Google Analytics Integration: by WooCommerce – 1.7.1
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.7
WooCommerce Payments: by Automattic – 5.7.0
WooCommerce Product Add-ons: by WooCommerce – 6.2.0
WooCommerce Product Bundles: by WooCommerce – 6.18.4
WooCommerce Product Recommendations: by WooCommerce – 2.2.2
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce Shipment Tracking: by WooCommerce – 2.3.1
WooCommerce: by Automattic – 7.6.0

### Inactive Plugins (10) ###

Avalara AvaTax: by Avalara – 2.2.0
Classic Editor: by WordPress Contributors – 1.6.3
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.5
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.1
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.0
WooCommerce EU VAT Number: by WooCommerce – 2.8.3
WooCommerce FedEx Shipping: by WooCommerce – 3.7.2
WooCommerce Royal Mail: by WooCommerce – 2.8.0
WooCommerce UPS Shipping: by WooCommerce – 3.4.2
WooCommerce USPS Shipping: by WooCommerce – 4.6.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #45 - /shop/
Cart: #46 - /cart/
Checkout: #47 - /checkout/
My account: #48 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tsubaki
Version: 1.1.4
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://woo-fortunately-krispy-lady.wpcomstaging.com
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — Florida

### Back In Stock ###

Database Version: 1.4.3
Loopback Test: –

### Gift Cards ###

Database Version: 1.15.4
Loopback Test: –
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 6.18.4
Loopback Test: –
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
navigation
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-22 17:41:04 -04:00
Options: ✔
Notes: 51
Onboarding: skipped

### WooCommerce Payments ###

Version: 5.7.0
Connected to WPCOM: Yes
Blog ID: 218142136
Account ID: -

### Action Scheduler ###

Complete: 15
Oldest: 2023-04-21 13:42:20 -0400
Newest: 2023-04-21 13:47:27 -0400

Pending: 4
Oldest: 2023-04-21 14:47:27 -0400
Newest: 2023-04-22 13:47:27 -0400

### Product Recommendations ###

Database Version: 2.2.2
Loopback Test: –
Task Queueing Test: ✔
Page Cache Test: –

### Status report information ###

Generated at: 2023-04-21 14:06:43 -04:00
`

### What plan is active?

Essential

**Comment by worldomonation** [comment]
📌 REPRODUCTION RESULTS
     Reproduced

📌 FINDINGS/SCREENSHOTS/VIDEO

**Upgrade to Woo Essentials**
<img width="1513" alt="Screenshot 2023-05-23 at 2 39 32 PM" src="https://github.com/Automattic/wc-calypso-bridge/assets/6549265/0618f131-c268-4976-8f26-7e1076e07cb0">

**Media Gallery > Video**
<img width="1513" alt="Screenshot 2023-05-23 at 2 40 53 PM" src="https://github.com/Automattic/wc-calypso-bridge/assets/6549265/605c7924-a0a2-4307-9b51-d18245be7551">

**Comment by worldomonation** [comment]
Addendum: I noticed that once the page is refreshed, the upgrade CTA text goes away. 
The preview has not rendered yet as of writing though, and it has been ~10 minutes since the upload and ~5 minute since reloading the page.

I can confirm that any new videos uploaded after seems to work fine.

**After page reload/refresh** - notice the CTA text has gone away.
<img width="1513" alt="Screenshot 2023-05-23 at 2 40 53 PM" src="https://github.com/Automattic/wc-calypso-bridge/assets/6549265/dd1b36cc-1ba7-42cc-906b-5adfa9a24152">

**Newly uploaded video after the page reload**
<img width="1513" alt="image" src="https://github.com/Automattic/wc-calypso-bridge/assets/6549265/426f4c73-6203-4084-bb6f-140ecd2ba8a6">

**Comment by wynwin** [comment]
Another report in 6459779-zen

**Comment by retnonindya** [comment]
Another repot: 6503302-zd-woothemes

Site: pleasedpeddlershop.com (Woo Express: Essential Plan)

**Comment by dolgelukkig** [comment]
Another report: 6571866-zd
Plan: Woo express Essential

**Comment by zoemyers** [comment]
Played into the ticket again, just checking in for an update.

**Comment by masperber** [comment]
Another report: 6675370-zen

@worldomonation would you be able to identify an assignee for this issue?

**Comment by lynnjat7** [comment]
Pinging again, is there any update on this issue?

**Comment by worldomonation** [comment]
No update, unfortunately. Because it involves Woo I think it would be best to first get the Woo Express team to triage the issue, and go from there.

**Comment by jackietranwoo** [comment]
Just leaving a note that there's an active thread going on about this in slack: https://a8c.slack.com/archives/C03Q87XT1QF/p1692883850138019

**Comment by ilyasfoo** [comment]
Hi folks, I'm unable to reproduce this issue with my Woo Express: Essentials plan sites. 

I was able to play both videos I uploaded, where it wasn't when it was in free trial. I've tested this in 2 sites.

Appreciate if someone is able to reproduce this again 🙏

**Comment by masperber** [comment]
@ilyasfoo Importantly, the bug affects the ability to *upload* videos to the ML, not the ability to play videos that have already been uploaded. Also, the bug only affects VideoPress, not videos uploaded directly to the ML.

To reproduce the issue, there are a few requirements. First, the site should be a WX Trial site *first*. Then upload one video, which should succeed. You can verify that further video uploads are properly rejected. Only after this, *upgrade* the site to WX Essentials through the regular purchase flow. Ensure that the VideoPress module is enable, and then try to upload another video.

**Comment by daledupreez** [comment]
I just want to note that D118362-code addressed the viewing behaviour for upgraded sites. That change was shipped to production on 2023-08-17.

I am taking another look at this issue to make sure I understand it.

**Comment by warrendholmes** [comment]
Also asked for help from @oskosk on Slack, thanks in advance Oscar!

**Comment by daledupreez** [comment]
I am not able to reproduce the issue, though I did hit a snag whereby I wasn't permitted to upload videos on my free trial site, most likely as a result of this code block that prevents video uploads when the `VIDEOPRESS` feature is not present on the plan:
https://github.com/Automattic/wpcomsh/blob/37b4fe1220508a777427b08803de4076f862cf8c/feature-plugins/hooks.php#L265-L270

**Comment by daledupreez** [comment]
Just to follow up, I suspect that my changes in D118362-code should address this, as we had a faulty check that could incorrectly show the "Trial plans are limited to a single video. Upgrade now to upload more videos!" message after sites had upgraded from the free trial.

**Comment by worldomonation** [comment]
@daledupreez Thanks for continuing to follow up on this issue, it's very much appreciated.

**Comment by masperber** [comment]
I am no longer able to produce the issue on my test sites. Thank you @daledupreez and others!

Closing
