### ISSUE TITLE
SFTP details can be accessed in Free Trial

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1091]
### Describe the bug

It's possible for a user to view SFTP details by removing the overlay on the Hosting Config page. I don't think most users would be able to view this, but this may present a security issue.

Originally reported by @kaushikasomaiya https://a8c.slack.com/archives/C03Q87XT1QF/p1682274910890219

### Steps to reproduce

1. Sign up to a free trial.
2. Go to Settings > Hosting Config.
3. View source of the page to reveal the SFTP logins.

### WordPress Environment

NA

### What plan is active?

Free trial

**Comment by daledupreez** [comment]
Initial attempt to tighten this up is in D108739-code.

**Comment by daledupreez** [comment]
This has now been addressed by D108739-code.
