### ISSUE TITLE
[Enhancement]: When Woo Express users confirm their email address redirect them to their store

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wc-calypso-bridge#1093]
### Describe the solution you'd like

As discussed this this thread, p1681983422254829-slack-C03Q87XT1QF, @jonathan-marsan asked whether it would be possible to redirect Woo Express users to their store after confirming their email address. As things stand, at least some users are redirected to the WordPress.com Reader.

**Comment by daledupreez** [comment]
I took an initial look at this and the approach here is likely to be complex for a few reasons:
1. The current WooCommerce.com flow has the following approximate sequence:
   a. We initiate a user creation/signup flow on WordPress.com to log the user in
   b. We return the user to WooCommerce.com
   c. We then initiate the site creation flow on WordPress.com
This means we don't know which site the user actually created when we send the activation email, nor are we recording that (or which site flow was used) as part of that data
2. The current activation logic doesn't have filters that allow the blog_id to be added after signup. See fbhepr%2Skers%2Sjcpbz%2Sjc%2Qnpgvingr.cuc%3Se%3Qr199q6qo%23110-og and fbhepr%2Skers%2Sjcpbz%2Sjc%2Qvapyhqrf%2Szf%2Qshapgvbaf.cuc%3Se%3Q1320r86r%231282%2Q1313-og.

**Comment by warrendholmes** [comment]
@daledupreez I now get redirected to the plans page. Which is better than the reader, but ideally we'd direct users to the Home page. Is that possible?

**Comment by daledupreez** [comment]
@warrendholmes, I am sure it's possible, though we'll need to dig in to confirm how easy it is. But it should be possible to carve out some specific logic for users who have exactly one Woo Express site.

**Comment by warrendholmes** [comment]
@ilyasfoo I think we can close this one based on the work here peapX7-2Bq-p2 to improve the NUX for email verifications, what do you think?

**Comment by ilyasfoo** [comment]
@warrendholmes I agree 👍
