### ISSUE TITLE
Deploy Automation: Command to automate the release build

### ISSUE THREAD

**Issue by markbiek** [Automattic/wc-calypso-bridge#1100]
Related to #1096

We need a command to automate doing a build for release:

1. `git checkout master`
1. `git pull origin master`
1. `npm i`
1. `npm run build`
1. `rm -rf node_modules so these don't get packaged up in the release`

We also need to add a bunch of verification and error checking:

1. Display a message that shows the current version that we're building and asks the user to confirm before performing the build.
1. Need to make sure there are no uncommitted changes in the working copy.
1. _What other error checking can/should we do here?_
1. Verify that `npm run build` finished successfully.
  1. We can check the return code of the command.
  1. We can also verify that the files in the build directory exist.

**Comment by ilyasfoo** [comment]
Thanks for creating this issue, @markbiek. One of the issues we bumped into was a dev build was included in the final result. One risk is that we have a `start` command running in a separate terminal while we run the build command, resulting in an intermingled build.

If we could somehow detect a non-production build, it'll also help with making sure the correct build gets deployed.

**Comment by markbiek** [comment]
> Thanks for creating this issue, @markbiek. One of the issues we bumped into was a dev build was included in the final result. I think what could've happened is a `start` command running in a separate terminal while we run the build command, resulting in an intermingled build.
> 
> If we could somehow detect a non-production build, it'll also help with making sure the correct build gets deployed.

Thanks for the additional context! Checking for a non-production build (or maybe checking for a running `start` command) definitely seems like a good idea.
