### ISSUE TITLE
Update plans grid ‘Plus’ content

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/wc-calypso-bridge#1108]
Please see post here for reference:https://hostedwoo.wordpress.com/2023/04/27/request-to-update-plans-grid-plus-content/

The desired update would be to have only two columns–one for the Essential plan, and one for Performance, removing the Plus plan altogether. Beneath these plans, we’d have a CTA for high-volume stores that can benefit from our Woo Enterprise offering. We can use the content as shown below:

Enterprise ecommerce
Learn how Woo can support the unique needs of businesses using WooCommerce at scale.
[ Learn more ]

Please link the ‘learn more’ button to [https://woocommerce.com/enterprise-ecommerce/?utm_source=wooexpress&utm_campaign=plans_grid](https://href.li/?https://woocommerce.com/enterprise-ecommerce/?utm_source=wooexpress&utm_campaign=plans_grid)

Rough mockup 

![Image](https://user-images.githubusercontent.com/89872780/234913404-dafecc86-f36f-4bf7-822d-879c6c2d128a.png)

**Comment by ilyasfoo** [comment]
Hey, @that-mike-bal. Yes, we can. 😄 

>If so, do we need design on it or can we figure it out in browser?

Best if we can have a design since I can't find a suitable component for the "Enterprise ecommerce" bottom popup in [calypso UI component docs](https://wpcalypso.wordpress.com/devdocs/design). I assume the "Enterprise plan" and "Performance plan" cards look exactly the same as the current design as a standard card UI.

**Comment by that-mike-bal** [comment]
I would assume the same but I can double check with Tim.

**Comment by that-mike-bal** [comment]
@ilyasfoo I commented on the wrong issue before 🤦 

@dlcallaway had suggested we put "Plus" underneath like we did here 

![Image](https://user-images.githubusercontent.com/89872780/235684836-841d3666-eeb7-4669-abdf-082d83d8ce63.png)

I think that would mean just showing the two plans and creating a different card for the "Plus" option.

**Comment by ilyasfoo** [comment]
@that-mike-bal Ok, we'll use the same component for the bottom card then. Thanks!

**Comment by ilyasfoo** [comment]
Design is underway p1684309610180039-slack-C01SFMVEYAK

**Comment by warrendholmes** [comment]
@ilyasfoo Just wanted to make sure you're aware that the design has been finalised peapX7-2ct-p2#comment-3072. 

@adrianduffell mentioned in the video on the cycle post that Ghidorah is waiting on  the design to be ready pdibGW-24i-p2.

Let me know if you have any questions!

**Comment by crunnells** [comment]
Thanks @warrendholmes, dev work is underway.

**Comment by ilyasfoo** [comment]
@warrendholmes Yes, we're aware the design is final but thanks for making sure!

**Comment by crunnells** [comment]
The primary part of this change [has been committed](https://github.com/Automattic/wp-calypso/commit/4d5fbc1a752a824be1655882a719d00664919d83).
