### ISSUE TITLE
Images are stretched out

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1110]
### Describe the bug

I'm seeing this on the plans page:

<img width="1048" alt="Screenshot 2023-04-28 at 12 18 46" src="https://user-images.githubusercontent.com/995473/235039067-2ccadf40-4fe2-4adf-a9e6-e691b8a46d81.png">

### Steps to reproduce

Go to the plans page in the free trial

### WordPress Environment

NA

### What plan is active?

Free trial

**Comment by PanosSynetos** [comment]
@warrendholmes are you still seeing this issue? I don't see it anymore, but if you do, you might need to ping @Automattic/ghidorah who has self-assigned this issue

**Comment by warrendholmes** [comment]
Not seeing it after a case reset, thanks @PanosSynetos !
