### ISSUE TITLE
Enable "Classic" wp-admin by default for Woo Express stores

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1129]

**Comment by manospsyx** [comment]
[Unblocked](https://cftp2.wordpress.com/2023/10/27/wp-admin-site-default-due-november-7th/#comment-3541).

**Comment by danielbachhuber** [comment]
D129564-code

**Comment by danielbachhuber** [comment]
> Are the changes being made here are only setting the /wp-admin admin interface as the default page to load? Or are we also disabling the WPCom toolbar to achieve this, like the snippet here does?

@Brianmitchtay The latter too. You can learn more about the feature here: https://wordpress.com/support/dashboard/#set-the-admin-interface-style

**Comment by danielbachhuber** [comment]
I deployed D129564-code. Woo Express sites now default to "Classic style". WordPress.com sites remain as "Default style"

🚢

**Comment by PanosSynetos** [comment]
Thank you @danielbachhuber !
