### ISSUE TITLE
[Enhancement]: Remove the Add Store Details task from the task list

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1131]
### Describe the solution you'd like

On Woo Express sites, we need to remove the Add Store details task. For every store created through the free trial, we have the store details populated. We end up at the Home Screen with the task list already "completed".

**Comment by rjchow** [comment]
Looked into it a bit while estimating, I suspect all that's required here is to add 'store_details' [here](https://github.com/Automattic/wc-calypso-bridge/blob/bb937be6794160599605f99c2f77f177e33ea9f1/includes/free-trial/class-wc-calypso-bridge-free-trial-hide-tasklist-tasks.php#L84) ?

**Comment by adrianduffell** [comment]
That looks correct to me @rjchow .
