### ISSUE TITLE
Update the side bar CTA

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1145]
The side bar nudge should changed for free trials from "Sign up" to "Upgrade now"

![Image](https://github.com/Automattic/wc-calypso-bridge/assets/3747241/4968883c-bc29-4da9-a14d-8573a4d93fab)

**Comment by ilyasfoo** [comment]
This is now deployed in D113144-code

<img src="https://github.com/Automattic/wc-calypso-bridge/assets/3747241/5b40b711-cdc3-400b-93d3-7d15e83308ef" width="400">
