### ISSUE TITLE
Tax Task list is broken

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1146]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The tax task list item appears to be broken for Woo Express sites. If you choose to use WooCommerce Tax, we're showing the Jetpack steps which are not needed. The address should already be set to enable Tax by default. 

We should also decide whether we should show Avalara.

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

-

### WordPress Environment

-

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by ilyasfoo** [comment]
Hey, @warrendholmes! Regarding Avalara, we currently only install the plugin without activating it. I think the only way for users to activate it is via the Tax task. Do you know of any discussions on removing it?

**Comment by adrianduffell** [comment]
I can reproduce the unnecessary Jetpack connection steps in the tax task when the connection is already made. Maybe the task is not detecting the specific type of connection used by Woo Express?


I think a fix for this ultimately needs to be made in Core, but we could prioritize a hotfix for WX if possible.

**Comment by adrianduffell** [comment]
> We should also decide whether we should show Avalara.

If we want to remove it for Woo Express, I think we should think about it abstractly so it can be applied through the Core recommendation engine. For example "Show Avalara only when WC Tax is not installed". That would reduce the maintenance and contractual complexities and I think benefit all users.

**Comment by warrendholmes** [comment]
We can leave Avalara for now, if there is a partnership in place ... but if we're able to make a decision for the user we should. i can follow up with the payments team. So let's ignore that for now and fix the connection issue for WCTax.

**Comment by warrendholmes** [comment]
Ok, spoke with @aleftick and we can leave Avalara for now — we're in negotiations with Stripe for their Tax product and can make the change when that agreement is in place. I'm changed this from Blocked to To Do.

So for now, we just need to fix the Jetpack connection issue that users are seeing.

@manospsyx or @adrianduffell Which of your teams is best to take this on?

**Comment by moon0326** [comment]
@adrianduffell @warrendholmes @verofasulo   ✋ 

WooCommerce Tax requires user's address, but we don't have address data for the users who sign up for a free trial via WCCOM flow.

I suggest combining the address form from the setup step and the automation prompt. What do you guys think?

Step 1: Address form


![Screen Shot 2023-07-18 at 4 42 30 PM](https://github.com/Automattic/wc-calypso-bridge/assets/4723145/3d642522-68d0-41f7-af58-bda55e9ab4d3)

Step 2: Automation form
![Screen Shot 2023-07-18 at 4 42 42 PM](https://github.com/Automattic/wc-calypso-bridge/assets/4723145/4def0ca4-f11e-4594-9434-be1487010b9b)

**Comment by moon0326** [comment]
@adrianduffell @warrendholmes pinging again in case you missed it

**Comment by adrianduffell** [comment]
@moon0326 Does WC Tax require the full address or just the country / region? If it absolutely requires the full address, the solution LGTM! I think we should probably also add copy to reassure the user about why the full address is needed as well.

cc @verofasulo for thoughts next week too

**Comment by warrendholmes** [comment]
@moon0326 Apologies! Agree with @adrianduffell the solution looks great if we need the full address. 🙇‍♂️

**Comment by verofasulo** [comment]
@moon0326 thanks for working on this!

> Step 1: Address form

Looks good to me! 

> Step 2: Automation form

Could we simplify the design of this step, please? I think it's a bit redundant as we display the same info twice. 
Please remove the celebration icon, heading, and subheading. Plus, I don't think all three buttons are needed as we already provide those alternatives one step before. 

<img width="712" alt="image" src="https://github.com/Automattic/wc-calypso-bridge/assets/98944206/2d9c4198-5246-4482-b108-713f67e8ac15">

I would leave only one button that allows the user to automate tax. :)

**Comment by moon0326** [comment]
Sorry for the delay @warrendholmes @verofasulo @adrianduffell 

I missed the comments. 

@verofasulo Sounds good to me!

I'm going to start working on it now.

**Comment by moon0326** [comment]
Hey @warrendholmes ✋ 

> We should also decide whether we should show Avalara.

I forgot to ask about Avalara. Do we also want to enable Avalara?

**Comment by warrendholmes** [comment]
@moon0326 Yes, we should still leave that option until we have the partnership ready with Stripe Tax.

**Comment by moon0326** [comment]
@warrendholmes Thanks for the confirmation.

Hey @verofasulo ✋ 

Since wc-calypso-bridge changes can't be tested on a JN, could you confirm the following design changes? This is when you choose WooCommerce Tax. Thanks!

Step 1: 
![Screen Shot 2023-07-30 at 2 05 56 PM](https://github.com/Automattic/wc-calypso-bridge/assets/4723145/93ea45a4-337e-440d-9105-dc0fa4d9c4cb)

Step 2:
![Screen Shot 2023-07-30 at 2 05 45 PM](https://github.com/Automattic/wc-calypso-bridge/assets/4723145/d03c1004-40a4-4c84-927f-0879505690da)

**Comment by verofasulo** [comment]
> Since wc-calypso-bridge changes can't be tested on a JN site, could you confirm the following design changes?

It looks great, thanks @moon0326! 

As mentioned above, I'm not sure about the reason why we duplicate the Manual setup and I don't charge sales tax buttons. 

If I'm not mistaken, the flow is the following:

1. The user clicks on collect tax rates on My Home
2. They get directed to the intro/onboarding screen with the comparison between WooCommerce Tax and Avalara. The user can click on "Continue setup", "No, thanks, I'll set up manually" or "I don't charge sales tax". 
3. If they select WooCommerce Tax, we display the stepper with the store location and we ask again if they want to charge taxes or set it up manually. I think it's redundant and we can cut off these buttons. 

Plus, I'm thinking if it makes sense to revisit the copy -- I'm not a big fan of the "Yes please" button 😅 Can we just use the label "Automate taxes"? cc @lauroraa if she has better input.

**Comment by moon0326** [comment]
> > Since wc-calypso-bridge changes can't be tested on a JN site, could you confirm the following design changes?
> 
> It looks great, thanks @moon0326!
> 
> As mentioned above, I'm not sure about the reason why we duplicate the Manual setup and I don't charge sales tax buttons.
> 
> If I'm not mistaken, the flow is the following:
> 
> 1. The user clicks on collect tax rates on My Home
> 2. They get directed to the intro/onboarding screen with the comparison between WooCommerce Tax and Avalara. The user can click on "Continue setup", "No, thanks, I'll set up manually" or "I don't charge sales tax".
> 3. If they select WooCommerce Tax, we display the stepper with the store location and we ask again if they want to charge taxes or set it up manually. I think it's redundant and we can cut off these buttons.
> 
> Plus, I'm thinking if it makes sense to revisit the copy -- I'm not a big fan of the "Yes please" button 😅 Can we just use the label "Automate taxes"? cc @lauroraa if she has better input.

Thanks for the review! 

I'm a bit confused about the changes. Do you want to get rid of the 2nd step entirely as shown below? 

FYI, we might also need to overview how the tax task works with ECON plan on WPCOM if we are going to make changes to the tax tasks for the trial changes IMO. The tax task on ECON plan also has the buttons. 

![Screen Shot 2023-08-01 at 1 50 40 PM](https://github.com/Automattic/wc-calypso-bridge/assets/4723145/ceb42bbd-fcb5-46e7-82ca-587c9fe387ac)

**Comment by moon0326** [comment]
> > I'm a bit confused about the changes. Do you want to get rid of the 2nd step entirely as shown below?
> 
> Not for now. I think the entire flow doesn't make much sense and we can iterate and improve it but for now, I would fix the main issues. So please keep the second step but remove the second and third actions :) What do you think?
> 
> ![image](https://user-images.githubusercontent.com/98944206/257823564-2d39b340-2b76-4b82-897a-48a7f2047da7.png)

Sounds good to me 👍

**Comment by moon0326** [comment]
The change has been deployed to WPCOM

**Comment by warrendholmes** [comment]
@moon0326 THANK YOU!

**Comment by warrendholmes** [comment]
Reopening, I just tested it and it just hangs here : 



![Image](https://github.com/Automattic/wc-calypso-bridge/assets/995473/c04af852-c073-43e4-9c4b-abb6ea17afa8)

I'm not sure what's going wrong, but this is what my console shows in case it's helpful:



![Image](https://github.com/Automattic/wc-calypso-bridge/assets/995473/6f13fffe-2977-4643-9fba-b803d3ae9680)

**Comment by ilyasfoo** [comment]
Hey, @warrendholmes! I think the loading indicator next to the step title might've always been like that (still, I agree it's a faulty UX). Are you able to click on `Automate taxes`, or does that hang as well?

**Comment by warrendholmes** [comment]
@ilyasfoo The hanging starts when I clicked Automate Taxes. Let me know If I can provide any other helpful info.

**Comment by ilyasfoo** [comment]
@warrendholmes Odd that it's working fine on my end. In your console, I don't see any related errors that's indicative of the issue. It does look like the site might be missing some JS files but it's not WooCommerce. Can you try to reproduce this again in a new site? 🙏 

If you can reproduce, can you also share the exact store address that you've used?

**Comment by warrendholmes** [comment]
Worked this time, but I noticed a new issue that I've opened [here](https://github.com/Automattic/wc-calypso-bridge/issues/1288).
