### ISSUE TITLE
Prevent WCPay safe mode triggering after plan purchase

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1169]
If a merchant completes WCPay account creation during the free trial, or with the staging domain, and upgrades or purchases a domain for the store WCPay safe mode will be triggered.

Related discussion p6q7sZ-dIP-p2#comment-32116

**Comment by manospsyx** [comment]
@warrendholmes I think that the motivation behind this [safe mode](https://woocommerce.com/document/woocommerce-payments/testing-and-troubleshooting/safe-mode/) is similar to [what we saw here](https://github.com/Automattic/wc-calypso-bridge/issues/1048). 

When a site gets moved/cloned, the admin needs to pick which one should remain connected to their WC Pay account.

**Comment by PanosSynetos** [comment]
Related Project Thread peapX7-2Mx-p2

**Comment by PanosSynetos** [comment]
This has been taken care of by Jetpack crew, as it affected all Jetpack sites, not just Woo Express. Thanks!

See peapX7-2Mx-p2#comment-3633
