### ISSUE TITLE
Remove Crowdsignal from Free Trial sites

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1177]
We haven't been able to hunt down what's causing [the redirect to Crowdsignal](https://github.com/Automattic/wc-calypso-bridge/issues/1142) after creating a free trial, so we're taking a heavy handed approach and removing it from new free trials.

**Comment by PanosSynetos** [comment]
@warrendholmes This fix will be deployed later on today under WPCOMSH 3.12.22

It was not possible to remove it from free trial sites, for reasons that I'll explain in a P2, so we improved the existing code that was responsible for preventing Crowdsignal's redirects

**Comment by warrendholmes** [comment]
Thank you @PanosSynetos !
