### ISSUE TITLE
Test: Re-introduce the task list nudges

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1186]
The task list nudges that have been removed on Woo Express may actually help drive activation improvements, according to the data here pbIJXs-2jo-p2

It's worth bringing them back to see the impact. We can either run this as an experiment or re-enable the nudges for all users and compare previous cohort conversions. If possible, it could be a good learning experience for me and the SomewhereWarm team to do our first experiment.

**Comment by manospsyx** [comment]
@xristos3490 does this still need to be open?
