### ISSUE TITLE
Add the Plugins menu item back to free trial sites

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1191]
On Woo Express Free Trial sites, the Plugins menu item was removed in a low-cost attempt to prevent users from installing/modifying plugins (in addition to enforcing this limitation in the back end).

Having to access to the Plugins menu item means that:

- End users (merchants) are not able to understand that they can install plugins to add functionality to their WordPress site.
- Developers are led to believe that they cannot install plugins on Woo Express (or even WordPress.com in general).

The goal here is to design and develop a Plugins landing page that:

1. Communicates the benefits of installing Plugins on a WordPress site.
2. Prompts users to upgrade to a paid plan.

**Comment by manospsyx** [comment]
Added a description here @warrendholmes

**Comment by warrendholmes** [comment]
Some relevant information provided by @daledupreez  here peapX7-2Hz-p2#comment-3489
