### ISSUE TITLE
Free trial days JITM not showing up

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1196]
I've created sites recently (https://woocommerce.com/express/) and I've noticed that the JITM about how many days are left in free trial, doesn't show up.

![Monosnap Orders ‹ Test AutomateWoo Cron — WordPress 2023-06-22 10-43-40](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/ba5bb4c6-c9c3-40a7-a99b-43a98d74cf91)

I've noticed that sites that this JITM was shown, now don't display it.

**Comment by markbiek** [comment]
@PanosSynetos I just created a new trial site and I'm seeing the JITM on my site.

<img width="470" alt="image" src="https://github.com/Automattic/wc-calypso-bridge/assets/917632/385edbfb-5c99-4c6f-818e-a1e132fe0421">

Do you have any more context or steps to reproduce?

**Comment by PanosSynetos** [comment]
Hey @markbiek , yes, it seems random. I sometimes don't see it at all, not even on new sites.
Other times, I visit existing sites and I see the JITM, where I wasn't seeing it in past visits.

Randomness is a pain :(

I just visited a dev trial site that I have, where I would see the JITM, and now I don't see it
![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/1eb9cd00-0f4f-4311-aab3-33d91d94bade)

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/4d33f805-343f-49ad-871f-5f8fd8852644)

**Comment by markbiek** [comment]
Definitely a weird one! Thanks for the extra details. I'll keep you posted on what I figure out!

**Comment by markbiek** [comment]
I don't have a root cause yet but it seems like the JITM engine isn't being called at all. I added a bunch of debug logging in fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Swrgcnpx%2Qwvgz%2Swvgz%2Qratvar.cuc%3Se%3Q84oo4p07-og and I see those log messages when the trial JITM is visible.

But, when the trial JITM isn't there, I don't see my log messages.

**Comment by markbiek** [comment]
@Automattic/serenity If anyone else has time to take a look at this, I'm stuck. There doesn't seem to be any consistent reason why this JITM sometimes disappears.

**Comment by manospsyx** [comment]
Changed priority to "Low" as we are not able to consistently replicate this.
