### ISSUE TITLE
Third-Party plugins settings show 'Sorry, you are not allowed to access this page.'

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wc-calypso-bridge#1201]
### Describe the bug

A third-Party Plugins settings shows `Sorry, you are not allowed to access this page.` on Woo Express plans only. 

The plugin I tried is Discount Rules for WooCommerce
https://wordpress.org/plugins/woo-discount-rules/

This happens on both Woo Express Essential and Performance plans. 
WordPress.com Business plans and above are not affected, so maybe it's something to do with the trial to full plan handover?

Discussion here; p1687562280614939-slack-C03TY6J1A
Original ticket; 6460689-zd-woothemes

### Expected behavior

Should be able to access the settings page as per other WordPress.com plans. 

### Steps to reproduce

1. Have a Woo Express plan
2. Install the plugin Discount Rules for WooCommerce
3. Go to the plugin settings `*/wp-admin/admin.php?page=woo_discount_rules&tab=settings`
4. The error will show

### WordPress Environment

<details>
  <summary>Click me</summary>

### WordPress Environment ###

WordPress address (URL): https://woo-fortunately-kawaii-kid.wpcomstaging.com
Site address (URL): https://woo-fortunately-kawaii-kid.wpcomstaging.com
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: wp_
Total Database Size: 5.90MB
Database Data Size: 3.04MB
Database Index Size: 2.86MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.13MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 20
jetpack_migration: 2
page: 9
post: 1
product: 4
revision: 2
wp_global_styles: 1
wp_navigation: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Crowdsignal Forms: by Automattic – 1.7.0
Facebook for WooCommerce: by Facebook – 3.0.25
WordPress.com Editing Toolkit: by Automattic – 3.69581
Google Listings and Ads: by WooCommerce – 2.4.10
Gutenberg: by Gutenberg Team – 16.0.0
Jetpack: by Automattic – 12.3-a.7
Layout Grid: by Automattic – 1.8.3
Page Optimize: by Automattic – 0.5.3
Pinterest for WooCommerce: by WooCommerce – 1.3.4
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.10

TikTok: by TikTok – 1.1.1
Woo AI: by WooCommerce – 0.1.0
Woo Discount Rules: by Flycart – 2.6.0
WooCommerce Brands: by WooCommerce – 1.6.52
WooCommerce Gift Cards: by WooCommerce – 1.16.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.2
WooCommerce Payments: by Automattic – 6.0.0
WooCommerce Product Add-ons: by WooCommerce – 6.4.2
WooCommerce Product Recommendations: by WooCommerce – 2.4.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WooCommerce Shipment Tracking: by WooCommerce – 2.3.1
WooCommerce: by Automattic – 7.8.0

### Inactive Plugins (9) ###

Avalara AvaTax: by Avalara – 2.5.0
Classic Editor: by WordPress Contributors – 1.6.3
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.1
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.1
WooCommerce EU VAT Number: by WooCommerce – 2.8.4
WooCommerce FedEx Shipping: by WooCommerce – 3.7.3
WooCommerce Royal Mail: by WooCommerce – 2.8.1
WooCommerce UPS Shipping: by WooCommerce – 3.4.3
WooCommerce USPS Shipping: by WooCommerce – 4.6.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #45 - /shop/
Cart: #46 - /cart/
Checkout: #47 - /checkout/
My account: #48 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tsubaki
Version: 1.2.1
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /wordpress/plugins/woocommerce/7.8.0/packages/woocommerce-blocks/templates/notices/error.php
/wordpress/plugins/woocommerce/7.8.0/packages/woocommerce-blocks/templates/notices/notice.php
/wordpress/plugins/woocommerce/7.8.0/packages/woocommerce-blocks/templates/notices/success.php

### Gift Cards ###

Database Version: 1.16.2
Loopback Test: ✔
Task Queueing Test: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
navigation
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-25 00:36:54 +09:00
Options: ✔
Notes: 56
Onboarding: skipped

### WooCommerce Payments ###

Version: 6.0.0
Connected to WPCOM: Yes
Blog ID: 220509741
Account ID: -

### Action Scheduler ###

Complete: 22
Oldest: 2023-06-24 09:36:58 +0900
Newest: 2023-06-24 09:38:59 +0900

Failed: 3
Oldest: 2023-06-24 09:39:39 +0900
Newest: 2023-06-24 09:56:38 +0900

Pending: 5
Oldest: 2023-06-24 09:56:53 +0900
Newest: 2023-06-25 09:38:59 +0900

### Product Recommendations ###

Database Version: 2.4.0
Loopback Test: ✔
Task Queueing Test: ✔
Page Cache Test: –

### Status report information ###

Generated at: 2023-06-24 09:57:19 +09:00
</details>

### What plan is active?

Essential

**Comment by happychait** [comment]
I had a customer report this in 6457357-zen

**Comment by Nic-Sevic** [comment]
to add to this, it looks like this workaround should help: P9HQHe-2ck-p2
If so, you need to `wp user add-role {userid} shop_manager` to the admin to give them the correct permissions

**Comment by PanosSynetos** [comment]
I have upgraded a new site to Performance and I cannot replicate the issue.

The menu item is visible, and I don't get the `Sorry, you are not allowed to access this page`. But we're further investigating with @manospsyx 

@Nic-Sevic I wanted to point out, that my user has just the admin role, doesn't have the shop manager role and I don't have an issue.

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/5146aa30-dcaf-46a7-829b-215323bc7171)

**Comment by PanosSynetos** [comment]
We've managed to identify the root cause of the issue and we're working on it.

We'll let you know once this is ready

**Comment by PanosSynetos** [comment]
We're releasing a new version of Calypso Bridge by tomorrow EOD which should fix this issue. Thanks for reporting this!
