### ISSUE TITLE
Fatal error preventing footer scripts from loading

### ISSUE THREAD

**Issue by martynmjones** [Automattic/wc-calypso-bridge#1211]
### Describe the bug

When creating a new Woo Express Trial site a number of screens are blank because of a fatal error preventing footer scripts from being loaded. Appears to be related to #1205 as the only logged error is:

```
2023-06-28T16:13:31+00:00 CRITICAL Uncaught Error: Call to a member function is_hidden() on null in /wordpress/plugins/wpcomsh/3.12.30/vendor/automattic/wc-calypso-bridge/includes/class-wc-calypso-bridge-woocommerce-admin-features.php:373
Stack trace:
#0 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): WC_Calypso_Bridge_WooCommerce_Admin_Features->add_onboarding_reset_settings(Array)
#1 /wordpress/core/6.2.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /wordpress/plugins/woocommerce/7.8.1/includes/admin/settings/class-wc-settings-general.php(294): apply_filters('woocommerce_gen...', Array)
#3 /wordpress/plugins/woocommerce/7.8.1/includes/admin/settings/class-wc-settings-page.php(125): WC_Settings_General->get_settings_for_default_section()
#4 /wordpress/plugins/woocommerce/7.8.1/includes/admin/settings/class-wc-settings-page.php(98): WC_Settings_Page->get_settings_for_section('')
#5 /wordpress/plugins/woocommerce/7.8.1/includes/class-wc-register-wp-admin-settings.php(126): WC_Settings_Page->get_settings('')
#6 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): WC_Register_WP_Admin_Settings->register_page_settings(Array)
#7 /wordpress/core/6.2.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#8 /wordpress/plugins/woocommerce/7.8.1/includes/rest-api/Controllers/Version2/class-wc-rest-setting-options-v2-controller.php(169): apply_filters('woocommerce_set...', Array)
#9 /wordpress/plugins/woocommerce/7.8.1/src/Internal/Admin/Settings.php(163): WC_REST_Setting_Options_V2_Controller->get_group_settings('general')
#10 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Internal\Admin\Settings->add_component_settings(Array)
#11 /wordpress/core/6.2.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#12 /wordpress/plugins/woocommerce/7.8.1/src/Internal/Admin/WCAdminSharedSettings.php(61): apply_filters('woocommerce_adm...', Array)
#13 /wordpress/plugins/woocommerce/7.8.1/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(282): Automattic\WooCommerce\Internal\Admin\WCAdminSharedSettings->Automattic\WooCommerce\Internal\Admin\{closure}()
#14 /wordpress/plugins/woocommerce/7.8.1/packages/woocommerce-blocks/src/Assets/AssetDataRegistry.php(383): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->execute_lazy_data()
#15 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry->enqueue_asset_data('')
#16 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#17 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /wordpress/core/6.2.2/wp-admin/admin-footer.php(95): do_action('admin_print_foo...')
#19 /wordpress/core/6.2.2/wp-admin/admin.php(297): require_once('/wordpress/core...')
#20 {main}
  thrown in /wordpress/plugins/wpcomsh/3.12.30/vendor/automattic/wc-calypso-bridge/includes/class-wc-calypso-bridge-woocommerce-admin-features.php on line 373
```

Discovered when attempting to test AutomateWoo on WooExpress which isn't working as the required assets aren't loading.

![Screenshot 2023-06-28 at 17 40 07](https://github.com/Automattic/wc-calypso-bridge/assets/40762232/2e507e0c-f34b-4007-a92c-6962bf8006f6)

### Additional

Upgrading to a paid plan fixed the error but AutomateWoo disappeared from the site.

### Steps to reproduce

1. Launch a new Woo Express site
2. Go to `AutomateWoo > Dashboard`, `Payments`, `Analytics`, or any other screen depending on JS scripts loaded in the footer
3. See error

### WordPress Environment

<details><summary>System Status Report</summary>

### WordPress Environment ###

WordPress address (URL): https://woo-mysteriously-clear-moon.wpcomstaging.com
Site address (URL): https://woo-mysteriously-clear-moon.wpcomstaging.com
WC Version: 7.8.1
REST API Version: ✔ 7.8.1
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.28-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.1
WC Database Prefix: wp_
Total Database Size: 5.36MB
Database Data Size: 2.76MB
Database Index Size: 2.60MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.22MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bis_activity: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_bis_notifications: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_bis_notificationsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 20
aw_workflow: 3
jetpack_migration: 2
page: 9
post: 1
product: 4
revision: 2
wp_global_styles: 1
wp_navigation: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
AutomateWoo: by WooCommerce – 5.8.1
Crowdsignal Forms: by Automattic – 1.7.0
WordPress.com Editing Toolkit: by Automattic – 3.70019
Gutenberg: by Gutenberg Team – 16.0.0
Jetpack: by Automattic – 12.3-beta
Layout Grid: by Automattic – 1.8.3
Page Optimize: by Automattic – 0.5.3
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.10

Woo AI: by WooCommerce – 0.1.0
WooCommerce Back In Stock Notifications: by WooCommerce – 1.6.2
WooCommerce Brands: by WooCommerce – 1.6.52
WooCommerce Gift Cards: by WooCommerce – 1.16.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.2
WooCommerce Min/Max Quantities: by WooCommerce – 4.1.0
WooCommerce Payments: by Automattic – 6.0.0
WooCommerce Product Add-ons: by WooCommerce – 6.4.3
WooCommerce Product Bundles: by WooCommerce – 6.21.1
WooCommerce Product Recommendations: by WooCommerce – 2.4.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.5
WooCommerce Shipment Tracking: by WooCommerce – 2.3.1
WooCommerce: by Automattic – 7.8.1

### Inactive Plugins (10) ###

Avalara AvaTax: by Avalara – 2.5.0
Classic Editor: by WordPress Contributors – 1.6.3
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.5
WooCommerce Australia Post Shipping: by WooCommerce – 2.5.1
WooCommerce Canada Post Shipping: by WooCommerce – 2.8.1
WooCommerce EU VAT Number: by WooCommerce – 2.8.4
WooCommerce FedEx Shipping: by WooCommerce – 3.7.3
WooCommerce Royal Mail: by WooCommerce – 2.8.1
WooCommerce UPS Shipping: by WooCommerce – 3.4.3
WooCommerce USPS Shipping: by WooCommerce – 4.6.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #45 - /shop/
Basket: #46 - /basket/
Checkout: #47 - /checkout/
My account: #48 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tsubaki
Version: 1.2.1
Author URL: https://automattic.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: /wordpress/plugins/woocommerce/7.8.1/packages/woocommerce-blocks/templates/notices/error.php
/wordpress/plugins/woocommerce/7.8.1/packages/woocommerce-blocks/templates/notices/notice.php
/wordpress/plugins/woocommerce/7.8.1/packages/woocommerce-blocks/templates/notices/success.php

### Back In Stock ###

Database Version: 1.6.2
Loopback Test: –

### Gift Cards ###

Database Version: 1.16.2
Loopback Test: –
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 6.21.1
Loopback Test: –
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
navigation
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-29 15:33:33 +01:00
Options: ✔
Notes: 56
Onboarding: skipped

### WooCommerce Payments ###

Version: 6.0.0
Connected to WPCOM: Yes
Blog ID: 220677706
Account ID: -

### Action Scheduler ###

Complete: 67
Oldest: 2023-06-28 16:35:42 +0100
Newest: 2023-06-28 17:42:28 +0100

Pending: 2
Oldest: 2023-06-28 17:43:17 +0100
Newest: 2023-06-29 16:35:42 +0100

### Product Recommendations ###

Database Version: 2.4.0
Loopback Test: –
Task Queueing Test: ✔
Page Cache Test: –

### Status report information ###

Generated at: 2023-06-28 17:43:19 +01:00
</details>

### What plan is active?

Free trial

**Comment by PanosSynetos** [comment]
No need to check the fatal @puntope ; yesterday I released a new version, that rollbacked the code, so it won't be possible to replicate it now.

we've already identified it and will have a PR ready later in the day (and release).


> So you need to buy it when you upgrade

I've upgraded to a Performance plan, and Automatewoo is there. Do we remove it from Essential plan maybe?

Is there a P2 with the discussion, about the need to buy when upgrading? 

We (@Automattic/somewherewarm ) are not aware of this; probably we've missed it, and it would be good to be up to speed :)

Thanks!
