### ISSUE TITLE
Users are not redirected to the Woo Home when the Calypso Home is loaded

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1214]
### Description

When Woo Express and Ecommerce Plan users click on `https://wordpress.com/home/[domain].wpcomstaging.com`, they should always be re-directed to the WooCommerce Home. 

To replicate the issue, you can type the URL directly in your browser, or:

- Go to your site's home page in the front end.
- Click on My Sites in the top bar.

The Calypso Home will load -- instead, you should have been re-directed to the WooCommerce Home.

**Comment by warrendholmes** [comment]
I'm not sure how users would get to this url on their own. @PanosSynetos Not sure if you have any more colour on this one since Manos is out?

**Comment by PanosSynetos** [comment]
@xristos3490 has developed this part in wp-calypso - 

we've discussed it with the team (Manos included) and decided that @xristos3490 will trigger a discussion for the calypso team and ask for someone with more experience to solve this.

It was working, so something has broken it, and we don't have the experience in calypso to debug and solve this.

**Comment by warrendholmes** [comment]
@daledupreez or @ilyasfoo Would either of you be able to help here?

**Comment by ilyasfoo** [comment]
Hi, @warrendholmes! I'm a bit occupied today and might be able to debug either tomorrow or the day after

**Comment by warrendholmes** [comment]
@ilyasfoo No worries, thanks for following up.

**Comment by ilyasfoo** [comment]
Hey @PanosSynetos @manospsyx @warrendholmes, I wasn't able to reproduce this issue with new and old free trial sites according to the instructions above. Can you confirm if you're able to reproduce it? If so, can you let me know if there's any steps I may have missed?

**Comment by PanosSynetos** [comment]
@ilyasfoo there was a crucial piece of info missing - Upgrade to a paid plan (essential monthly) and

- Go to https://wordpress.com/home/[domain].wpcomstaging.com
- You'll get redirected to https://wordpress.com/home/[domain].wpcomstaging.com
- There's no additional redirection to https://[domain].wpcomstaging.com/wp-admin/admin.php?page=wc-admin

I just upgraded and tested it

**Comment by ilyasfoo** [comment]
This was done in https://github.com/Automattic/wp-calypso/pull/78990
