### ISSUE TITLE
Fix hardcoded colors in WooCommerce Core

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1215]
### Description

Many input elements, text blocks, and empty state icons in WooCommerce Core are "painted" with a hardcoded purple. Some examples:

- The Products and Orders empty states.
- The Shipping Zones empty state.
- Various toggles in WooCommerce Settings.

These elements all need to inherit their color from a suitable variable, to allow Woo Express admin themes to control their appearance.

**Comment by PanosSynetos** [comment]
I've opened a PR in WooCommerce with all the related issues I could find.

- https://github.com/woocommerce/woocommerce/pull/39182

We'd need to open PRs in all of our SomewhereWarm repositories to fix the button colors (note to self :P )

cc @jimjasson

**Comment by PanosSynetos** [comment]
This is planned to be released in WooCommerce 8.1.0 - cc @warrendholmes

**Comment by warrendholmes** [comment]
Great work @PanosSynetos !
