### ISSUE TITLE
Nav tabs and sub nav should not be separated by notifications

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#122]
Admin notifications separate the nav tabs and sub nav currently.  Need to find a way to separate these.  

<img width="1356" alt="screen shot 2018-10-31 at 10 34 50 am" src="https://user-images.githubusercontent.com/10561050/47799871-29241c80-dcf9-11e8-8afa-f3957703d08b.png">

If the notifications are positioned absolutely or fixed (Calypso style) by https://github.com/Automattic/wc-calypso-bridge/issues/118 this will probably resolve this issue.

<img width="483" alt="screen shot 2018-10-31 at 10 41 17 am" src="https://user-images.githubusercontent.com/10561050/47800069-8ddf7700-dcf9-11e8-80b4-eee58e8e4c1c.png">

**Comment by joshuatf** [comment]
@josemarques Final verdict on this was this order, correct?

* Page title
* Navigation
* Subnav
* Notices

Or did we decide it's not problematic since these *should* all be hidden?

**Comment by josemarques** [comment]
Yup, correct.
