### ISSUE TITLE
AutomateWoo Upgrade notice

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1246]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

I'm seeing this notice on a free trial:

![Image](https://github.com/Automattic/wc-calypso-bridge/assets/995473/962ad46f-57a6-45d3-ac41-ac8721210fb5)

If the updater needs to run, let's just run it. If a notice is needed, then only show it in the AW section.

### Expected behavior

NA

### Actual behavior

NA

### Steps to reproduce

NA

### WordPress Environment

NA

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by jconroy** [comment]
@warrendholmes so this is a fresh install with a fresh version of the latest version AutomateWoo being activated?

**Comment by jconroy** [comment]
6.0 released on the 25th July has an upgrade needed - I'm wondering if for Woo Express we needed to for an update silently.
