### ISSUE TITLE
Incorrect plan name after purchase

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1251]
This is a bug we ran into during a walk through peapX7-2ZM-p2 

After purchasing a Woo Express plan, we saw : 

![Image](https://github.com/Automattic/wc-calypso-bridge/assets/995473/602a725c-f170-4274-9ee5-16661e33bd3e)

This should have the plan name instead of **Trial plan**

**Comment by manospsyx** [comment]
@PanosSynetos have you been able to replicate this? I kept an eye on it but didn't see anything strange.

Could it be another one of those "random bugs"?

**Comment by PanosSynetos** [comment]
It was probably something random, lots of things have changed since July. 

I've never noticed this on the sites I've created since then.
