### ISSUE TITLE
Include admins in woocommerce_analytics tracking

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#1256]
Per the discussion here peapX7-30s-p2#comment-3985 we want to include admins in all woocommerceanalytics tracking.

So that we can differentiate between admins and shoppers, we'll need to add a new field something like admin=true or false.

**Comment by pmcpinto** [comment]
Hey Warren, I also created one issue 😄 https://github.com/woocommerce/woocommerce-blocks/issues/10427
Should we keep one of them? I asked Rubik to include this work in the next cycle, considering that we plan to add/improve the events available in the woocommerceanalytics package. We don't know yet how long it will take to carry out all the work in this area, as it's the first time the team has interacted with this code base.

**Comment by manospsyx** [comment]
Looks like this is almost done. Note: Shop manager role should be included [here](https://github.com/Automattic/jetpack/pull/32692/files).
