### ISSUE TITLE
Payments task not marked as complete when WooPayments is set up and enabled.

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1270]
P2: p4ya8V-6dF-p2#comment-3608

It seems even when WooPayments is set up and enabled in a Woo Express site, the payments task is not marked as completed. I'm unsure if this affects Core or not, but if so please also fix in Core.

Tasklist:

![Image](https://user-images.githubusercontent.com/3747241/260619580-05b8f839-09e0-4476-ab87-80d3aed9c38e.png)

WooCommerce Settings > Payments

![Image](https://user-images.githubusercontent.com/3747241/260619684-b9d55cec-e599-4e8e-af2a-95ec456984d1.png)

### Acceptance criteria

1. Payments task should be marked as complete when at least a payment method is set up and enabled, especially WooPayments.

**Comment by PanosSynetos** [comment]
Should be fixed in this PR

https://github.com/woocommerce/woocommerce/pull/39786

**Comment by ilyasfoo** [comment]
Nice, thanks for letting me know!

**Comment by manospsyx** [comment]
Good to close @PanosSynetos ?

**Comment by ilyasfoo** [comment]
I was able to confirm the fix in Woo Express, closing
