### ISSUE TITLE
Text correction on screen after sign up and before tasklist

### ISSUE THREAD

**Issue by jackietranwoo** [Automattic/wc-calypso-bridge#1290]
### Describe the bug

"Start Selling quickly" is supposed to be "Start selling quickly"

The s in "selling" is **not** supposed to be capitalized.

### Steps to reproduce

![screenshot 4](https://github.com/Automattic/wc-calypso-bridge/assets/128577987/b3b7c64f-91b4-475e-bd4d-53551982e636)

### WordPress Environment

N/A

### What plan is active?

Free trial

**Comment by jackietranwoo** [comment]
Hi @ilyasfoo, I think Ghidorah could help with this but please let me know if this is another team. Thanks!

**Comment by ilyasfoo** [comment]
Hi @jackietranwoo. Yes, Ghidorah will handle this. Thanks for the report!
