### ISSUE TITLE
Turn on CYS feature flag and hide "Choose Your Theme" task

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wc-calypso-bridge#1305]
**Issue Description:**

Turn on CYS feature flag (`customize-store`) and remove ["Choose Your Theme" task](https://github.com/Automattic/wc-calypso-bridge/blob/7f8f4b9038634f3df4220b1dc87c8fa32276856f/includes/tasks/class-wc-calypso-task-appearance.php#L29) to launch CYS MVP on WooExpress.

**Comment by adrianduffell** [comment]
For the time-being, I'll create a PR to make the theme task hide when the feature flag is on.

It seems it also appears twice right now:

<img width="699" alt="Screen Shot 2023-10-02 at 3 30 31 pm" src="https://github.com/Automattic/wc-calypso-bridge/assets/9312929/319a4cdf-44a1-4128-9dfe-c25a42493bfc">
