### ISSUE TITLE
[Enhancement]: Update WooCommerce.com client to use v2 API

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wc-calypso-bridge#1306]
### Describe the solution you'd like

As requested in the following thread, p6JqRr-aKe-p2#comment-17007, we want to update the client code that registers eCommerce and Woo Express plans with WooCommerce.com to call the newer v2 API so we can correctly leverage aspects of the API to apply limitations to what users can (and can't) do.

### Describe alternatives you've considered

We're currently using the v1 API, which is not being enhanced at this time.

**Comment by andres-blanco** [comment]
Diff D125298-code

**Comment by andres-blanco** [comment]
Closed in D125298-code
