### ISSUE TITLE
Implement a remote inbox notifications rule in Core to target Woo Express sites

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1313]
### Description

WooCommerce Core already includes an `is_ecommerce` remote inbox rule that makes it possible to send Inbox messages to sites on the Ecommerce Plan. No such rule exists for the Woo Express plan.

**Comment by manospsyx** [comment]
Opened a PR here: https://github.com/woocommerce/woocommerce/pull/40513

**Comment by PanosSynetos** [comment]
Closing this, PR has been merged
