### ISSUE TITLE
[Customize Your Store] Filter recommended themes

### ISSUE THREAD

**Issue by chihsuan** [Automattic/wc-calypso-bridge#1316]
**Issue Description:**

We have implemented a new API to fetch themes and added a filter `__experimental_woocommerce_rest_get_recommended_themes` for extensibility in https://github.com/woocommerce/woocommerce/pull/40508.

We need to use that filter to provide the correct themes in WooExpress.

**Comment by moon0326** [comment]
@chihsuan 

Do we have a list of themes to use in WooExpress?

**Comment by chihsuan** [comment]
> @chihsuan
> 
> Do we have a list of themes to use in WooExpress?

Hey @moon0326 Yes,https://github.com/woocommerce/woocommerce/pull/40508/files#diff-32f2ff7604500d2d654df06be40cc93b3a0194cafe143123e78f78a69d2712e6R263-R300 are themes to use in WooExpress. We just need to update the `link_url` and `is_active` fields via the filter. 🙂

**Comment by adrianduffell** [comment]
@ilyasfoo Do you have any tips on how to get the price of the theme? We would need to display it in the user's currency.

**Comment by crunnells** [comment]
AFAIK, we'll need to get the theme price(s) from the WPCOM/Store code, based on the user locale and site plan.

**Comment by adrianduffell** [comment]
Ha, actually all the themes will included in the Woo Express plan and don't need to be paid for. For the price, we would just need to pass through a translated string of "Free".

**Comment by crunnells** [comment]
Ah right, for Woo Express it's included. I was thinking about how we might show Premium themes to self-hosted Woo users, but I'm unclear about the install process if Jetpack isn't installed and enabled.
