### ISSUE TITLE
[Woo Express $1 offer] Homescreen banner

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1320]
## Issue description

![Image](https://github.com/Automattic/wc-calypso-bridge/assets/3747241/2791cf96-6ebe-40a3-ae52-4336f293ca22)

Figma: jFG3dxNDOdMkw8AC1aGWBL-fi-458_1884

Homescreen banner is customized for $1 offers.

## Acceptance criteria

```
Feature: Homescreen Banner

Scenario: Display new homescreen banner for eligible users
  Given the user is eligible for the $1 offer
  And the new homescreen banner is not dismissed by the user
  When the user navigates to the homescreen
  Then the new homescreen banner for the $1 offer is displayed

Scenario: Display old homescreen banner for non-eligible users
  Given the user is not eligible for the $1 offer
  And the old homescreen banner is not dismissed by the user
  When the user navigates to the homescreen
  Then the old homescreen banner is displayed

Scenario: Dismiss the new homescreen banner
  Given the new homescreen banner for the $1 offer is displayed
  When the user clicks the dismiss option on the new banner
  Then the new banner should be dismissed
  And the dismiss action used should be unique for the new banner

Scenario: Navigate to the plans page
  Given the new homescreen banner for the $1 offer is displayed
  When the user clicks the "Upgrade now" button on the banner
  Then navigate to plans page (ex: https://wordpress.com/plans/sitenamehere)
```

**Comment by moon0326** [comment]
Hey @ilyasfoo 

Should we display the $1 offer banner on top of the free trial banner, or should we replace the free trial banner with the $1 offer banner?

![Image](https://github.com/Automattic/wc-calypso-bridge/assets/4723145/55c6516b-695d-4db3-b51a-00a9294eac1c)

**Comment by ilyasfoo** [comment]
Hey, @moon0326! The $1 banner should replace the free trial banner.

Also, a detail I missed adding - $1 should respect users' currency, which should be returned by the API 
`https://public-api.wordpress.com/rest/v1.3/sites/225833434/plans?http_envelope=1` and use it in the copy accordingly:

<img width="1145" alt="image" src="https://github.com/Automattic/wc-calypso-bridge/assets/3747241/0c68232d-53fd-497b-b671-8311ee0d77e2">

**Comment by moon0326** [comment]
@ilyasfoo Thank you for the details 👍

**Comment by ilyasfoo** [comment]
@moon0326 I've updated the image in the issue description, there was a copy update. It should be final now
