### ISSUE TITLE
[Woo Express $1 offer] Homescreen track

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1322]
## Issue description

Related to https://github.com/Automattic/wp-calypso/pull/82099, we need to add the track `calypso_wooexpress_one_dollar_offer` with the prop `location: homescreen` when a user visits homescreen.

We have a prior art for adding calypso tracks: https://github.com/Automattic/wc-calypso-bridge/blob/ef3b3ae7c16caff0aaae0a0b6e1329c351bc7a08/src/track-menu-item.ts#L31-L33

## Acceptance criteria

1. When a user is eligible for $1 offer and visits the homescreen, fire the tracks `calypso_wooexpress_one_dollar_offer` with props `location: homescreen`.

**Comment by moon0326** [comment]
Hey @ilyasfoo Do you think we can implement it on wp-calypso since it already has useOneDollarOfferTrack?

**Comment by ilyasfoo** [comment]
Good question, @moon0326! We'll still need to add in bridge since the entrypoint of every $1 offer is the homescreen, which is ideal for an "allocation event" (internal discussion: p1696616543883129/1696608289.267929-slack-C05KSH7B4UV)

**Comment by moon0326** [comment]
@ilyasfoo Sounds good!

**Comment by ilyasfoo** [comment]
For posterity, https://github.com/Automattic/wc-calypso-bridge/issues/1320#issuecomment-1809869478 and p1700098190300649/1700073223.773259-slack-C01SFMVEYAK

**Comment by moon0326** [comment]
@ilyasfoo Calling the plans endpoint and triggering the track function might be tricky. There's a chance that the user could leave the page before we finish the request and make the function call.

Is there a way to add a classname (.has-intro-offer) to the upgrade button? I've looked into `jitm-engine.php`, but no luck :( 

![Screenshot 2023-11-20 at 11 39 30 AM](https://github.com/Automattic/wc-calypso-bridge/assets/4723145/43c2bf64-825a-4ac4-9b74-b4a8f0fa7eba)

**Comment by moon0326** [comment]
@ilyasfoo It seems like we can re-use useOneDollarOfferTrack and other changes added to `automattic/data-stores` packages in wc-calypso-brige. I've reached out to Christos to request  the release a new version of `automattic/data-stores` 

I'm going to put a hold on this issue for now.
