### ISSUE TITLE
Cart/checkout block compatibility

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1323]
### Description

All Woo Express extensions need to be updated to declare compatibility with the cart/checkout blocks.

- [x] [PB]: https://github.com/woocommerce/woocommerce-product-bundles/pull/1269
- [x] [GC]: https://github.com/woocommerce/woocommerce-gift-cards/pull/717
- [x] [BIS]: https://github.com/woocommerce/woocommerce-back-in-stock-notifications/pull/247
- [x] [PAO]: https://github.com/woocommerce/woocommerce-product-addons/pull/915
- [x] [MMQ]: https://github.com/woocommerce/woocommerce-min-max-quantities/pull/263
- [x] [PRL]: https://github.com/woocommerce/woocommerce-product-recommendations/pull/496

**Comment by PanosSynetos** [comment]
@manospsyx this is reviewed and PRs have been merged. Pending releases
