### ISSUE TITLE
[EPIC] Sunset Customizer in Woo Express plans

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1327]
### Description

The Customizer was recently [removed from WooCommerce Core](https://github.com/woocommerce/woocommerce/blob/fe6e43b438710ecd3b0a97bfbe74bc6559a3db69/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php#L889-L895) when a block theme is detected.

In Woo Express, we have peapX7-3rB-p2#comment-4963 registering customizer options that appear to introduce it when a block theme is active.

Let's investigate those and hide the customizer in the Woo Express environment: We have received reports from users who are led to believe that they can't launch their store because they can't figure out how to turn off the Store Notice.

**Important**: This is going to require changes in Calypso as the Customizer is used to allow WP.com users to configure (i) a footer message; (ii) fonts; (iii) custom CSS; etc.

EDIT: Decided to make this as simple as possible
```[tasklist]
### Tasks
- [ ] Uncheck the store notice and don’t enable it for all new sites
- [ ] Hide the customizer menu item, when a block theme is used and there is no custom CSS

```

**Comment by PanosSynetos** [comment]
For more info see Project Thread at peapX7-3Xx-p2
