### ISSUE TITLE
Free trial - discrepancy between JIT and Upgrades / Plans

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1329]
As @tckasa mentioned 

> There’s a discrepancy between the number of days remaining for the free trial account displayed in the banner at the top of the ‘Upgrades - Plans’ section and the countdown timer. 

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/4c6545ca-2265-43be-95f9-876fcce991a9)

There is an internal slack discussion at p1696946153884259-slack-C03Q87XT1QF

cc-ing @Automattic/serenity

**Comment by zaerl** [comment]
Calypso uses `ceil()`; otherwise, it will show `will expire in 6 days` the first time you see the migration plan page.

Context: p1692857129186919-slack-C01A60HCGUA

**Comment by daledupreez** [comment]
I have kicked off an internal discussion to work through some of the subtleties, as they involve the duration of our hosting and migration trials: pdKhl6-2Vg-p2
