### ISSUE TITLE
Poor text contrast on :visited primary buttons

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1332]
### Description

The following text contrast issue seems to affect primary buttons in WP admin pages:

![Image](https://user-images.githubusercontent.com/1783726/277612165-971660e3-1df5-4c06-80be-b77f8e349337.png)

This seems to be caused by a `:visited` CSS rule that appears to be applied to primary and likely secondary buttons.

**Comment by PanosSynetos** [comment]
@manospsyx it seems like help-center CSS has some very generic `.button` styles. I don't have a way to override those.

![Monosnap Orders ‹ Site Title — WordPress 2023-11-30 18-22-40(1)](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/1fbdc0b8-ef08-41db-821f-038972dcc90c)


I've pinged the team in Slack p1701361793125619-slack-C02DQP0FP to let them know for assistance. I'll write back when I have news

**Comment by PanosSynetos** [comment]
This has been fixed by PR
- https://github.com/Automattic/wp-calypso/pull/84774

Closing it, it will be fixed once the latest calypso version will be deployed on Atomic
