### ISSUE TITLE
Mobile sidebar toggle hover state color and padding

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#135]
On mobile the padding for the sidebar toggle looks uneven and it seems like the hovered/focus color of the icon should be white.  @josemarques What do you think?

<img width="326" alt="screen shot 2018-11-02 at 9 35 32 am" src="https://user-images.githubusercontent.com/10561050/47921577-f27a0d80-de82-11e8-8ee0-a8b131f98d1c.png">

**Comment by josemarques** [comment]
Is it possible to mimic the sidebar behaviour in calypso? 

![sidebar](https://user-images.githubusercontent.com/57050/47935988-519f4880-deaa-11e8-99aa-3560002f0a3a.gif)

**Comment by joshuatf** [comment]
Closing this issue since the mobile nav button will be hidden by fixing https://github.com/Automattic/wc-calypso-bridge/issues/153
