### ISSUE TITLE
Remove 'subscription product' from "Add Products" task

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#1360]
### Description

The "Add Products" onboarding task in Woo Core is exposing a "Subscription product" option that is probably a leftover from an older promotion of WooPayments. When users click on that option, the flow results in the creation of a Simple product, and there is nothing in the flow to suggest that it's part of a promotion or experiment.

**Comment by PanosSynetos** [comment]
Issue opened in Core
- https://github.com/woocommerce/woocommerce/issues/41606

**Comment by jimjasson** [comment]
Closed via: https://github.com/woocommerce/woocommerce/pull/41778
