### ISSUE TITLE
WC Admin bar pushed down when there are steps to complete the onboarding

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1387]
See screenshot, self explanatory

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/fd0e25b8-3b49-4b40-b5cd-5d141997ac52)

@manospsyx for awareness and prioritization

**Comment by PanosSynetos** [comment]
This doesn't seem related to Woo Express. Happens on self hosted WC 8.4 as @barryhughes shared 
in p1703017714001579-slack-C01DT6U03HC

![image](https://github.com/Automattic/wc-calypso-bridge/assets/2484390/be55ade9-d008-4fa3-a5d6-68805b479748)

Let's see how the discussion goes, and if it's not addressed, we can check it out on an upcoming sprint

**Comment by barryhughes** [comment]
See also https://github.com/woocommerce/woocommerce/pull/43020.

**Comment by PanosSynetos** [comment]
Closing this, I tested the above PR and works as expected!
