### ISSUE TITLE
Test TT4 with Shopper Experience Map

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#1425]
, update everything on the cloned site, test and compare

```[tasklist]
### Tasks
- [x] Clone wooxdemo/woo-express-feature-map/
- [x] Update cloned site
- [x] Enable TT4
- [x] Compare
```

**Comment by jimjasson** [comment]
Closed via: https://somewherewarmattic.wordpress.com/2024/01/22/xpost-the-twenty-twenty-four-experience-in-woo-express/
