### ISSUE TITLE
Pagination styles don't match Calypso's

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#143]
The pagination styles don't match Calypso's - https://wpcalypso.wordpress.com/devdocs/design/pagination

There isn't a hook for the WC pagination, but most can be done through styling, while individual page links may need to be modified via JavaScript.

<img width="317" alt="screen shot 2018-11-02 at 3 39 35 pm" src="https://user-images.githubusercontent.com/10561050/47939539-b4e2a800-deb5-11e8-985b-02da7e969a05.png">

**Comment by joshuatf** [comment]
@josemarques I'm working on a PR for this, but wanted to get your input first.  Do you think we should keep the pagination where it is or put it below the table to make it more like Calypso?

The former is probably best done through JavaScript while the latter needs to be done through PHP.

**Comment by josemarques** [comment]
Definitely below the table like in Calypso. 🙌
