### ISSUE TITLE
Deactivate woocommerce-services when woocommerce-shipping or woocommerce-tax is installed

### ISSUE THREAD

**Issue by kloon** [Automattic/wc-calypso-bridge#1457]
When launching Woo Shipping and Woo Tax on WooExpress we need to ensure that if WCS&T is activated and either Woo Shipping or Woo Tax is installed that it deactivated WCS&T.

See the following PR for how it was done for TikTok https://github.com/Automattic/wc-calypso-bridge/pull/1430/

**Comment by waclawjacek** [comment]
The following things still need to be done to land this PR:

This release PR will have to be merged: https://github.com/Automattic/wc-calypso-bridge/pull/1464

And then:

> You'll also need to make a wpcomsh release with bumped bridge composer dependency
> 
> See https://github.com/Automattic/wpcomsh/pull/1668 and [Automattic/wpcomsh#deployment](https://github.com/Automattic/wpcomsh?tab=readme-ov-file#deployment)

~ @PanosSynetos

**Comment by PanosSynetos** [comment]
It's the other way around @waclawjacek  - First this one needs to be merged and then get on with the release PR

**Comment by PanosSynetos** [comment]
Sorry, the PR has been merged https://github.com/Automattic/wc-calypso-bridge/pull/1458

**Comment by waclawjacek** [comment]
WPCOMSH PR merged: https://github.com/Automattic/wpcomsh/pull/1811
