### ISSUE TITLE
WooCommerce HPOS is not being turned on consistently for new Entrepeneur or Woo Express stores

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wc-calypso-bridge#1468]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Sites that are being created with the Entrepreneur plan or the Woo Express trial plan are not always being created with the WooCommerce HPOS feature enabled, which should be the default for new WooCommerce installs.

This was reported internally in plenty of detail in p9F6qB-faq-p2

### Expected behavior

When a site first gets WooCommerce installed (which happens as part of the transfer process for Entrepreneur and Woo Express sites), the HPOS feature should be enabled by default.

### Actual behavior

The HPOS feature is not enabled in a number of cases.

### Steps to reproduce

* Log in to WordPress.com
* Create a new Woo Express or WPCOM site by using either of the following links:
  - Woo Express: https://wordpress.com/setup/wooexpress
  - WPCOM: https://wordpress.com/start/domains. Select the Entrepreneur plan. Give yourself free credits if needed, in order to purchase it.
* Without making any kind of customizations to the site, `_cli` into it.
* Run `wp wc hpos status`
* You will get an output saying `HPOS enabled? no` meaning that the site was created with HPOS disabled. In non-WPCOM installations, HPOS is enabled by default. And if I’m not mistaken, HPOS had been enabled by default in Woo Express and WPCOM sites in the past.
* If you go to the site’s admin dashboard and go to `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`, you will notice that `WordPress posts storage (legacy)` was selected instead of `High-performance order storage (recommended)` which confirms that the site was created with HPOS disabled.
<img width="958" alt="screenshot-2024-05-10-at-3 38 16e280afpm" src="https://github.com/Automattic/wc-calypso-bridge/assets/3376401/4ca3b5b5-518c-4d9a-8880-7f0c3f65d0c5">

### WordPress Environment

Not needed - this occurs during install.

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by daledupreez** [comment]
I managed to reproduce this using WP-CLI, and I think there is something going on with the way Woo detects (in)compatible plugins.

From a clean site with no previous Woo options or install, I ran the following command to install and activate WooCommerce:
```
wp --skip-plugins --skip-themes plugin install woocommerce --activate
```

After doing that, the HPOS option was disabled.

Looking at the code more closely, it looks like the way this is actually updated is based on the first admin visit to the site.

The logic to call `WC_Install::maybe_enable_hpos()` is driven by the `'woocommerce_newly_installed'` hook, which itself is triggered from `WC_Install::newly_installed()`.

https://github.com/woocommerce/woocommerce/blob/e765a717d23445cf62efd811628eb77f3c422a4e/plugins/woocommerce/includes/class-wc-install.php#L277

https://github.com/woocommerce/woocommerce/blob/e765a717d23445cf62efd811628eb77f3c422a4e/plugins/woocommerce/includes/class-wc-install.php#L292-L309

In turn `WC_Install::newly_installed()` is hooked on `'admin_init'`: https://github.com/woocommerce/woocommerce/blob/e765a717d23445cf62efd811628eb77f3c422a4e/plugins/woocommerce/includes/class-wc-install.php#L288

The complication we may hit is that for eCommerce/Woo Express sites, we probably add our sample content before the `admin_init` action is ever fired, which would then disqualify us from enabling HPOS.

**Comment by sixhours** [comment]
After chatting about it in p1715794796764419-slack-C0Q664T29 I started a diff to manually enable HPOS for sites coming through `/setup/wooexpress` and `/setup/ecommerce` to start: D148861-code

**Comment by sixhours** [comment]
We've fixed this for incoming sites from `/setup/wooexpress` and `/setup/ecommerce`, but still needs to be fixed for users who select the e-commerce plan on signing up.

**Comment by markbiek** [comment]
Noting that I did a quick test of `/setup/wooexpress` and I'm still seeing it set to legacy storage (blog id: 234366614).

![CleanShot 2024-06-19 at 15 13 45](https://github.com/Automattic/wc-calypso-bridge/assets/917632/2612fc98-c79e-48f3-afba-d9c795e58eca)

**Comment by markbiek** [comment]
@daledupreez Also noting that I made a new site with the Creator plan and installed WooCommerce using

```
wp --skip-plugins --skip-themes plugin install woocommerce --activate
```

and HPOS was correctly enabled.

**Comment by markbiek** [comment]
I think this should be fixed with the new HPOS work we shipped. Closing for now.
