### ISSUE TITLE
Taxonomy form toggle

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#147]
Taxonomy forms should be hidden by default and toggled on/off by a button on mobile.  This involves
* Hiding the taxonomy form
* Adding a "Add new" button
* Hiding the taxonomy/category list on "Add new" click and showing the form
* Adding a cancel button to the form
* Reversing the form-hiding process when cancel is clicked.

### Screenshots
<img width="802" alt="screen shot 2018-11-06 at 4 29 18 pm" src="https://user-images.githubusercontent.com/10561050/48094803-246fd480-e1e1-11e8-97a5-da46dfcbed4c.png">

**Comment by timmyc** [comment]
@josemarques any input on the location of the "Add Category" button, and if the search input needs to be moved at all to respond to the addition of the button?

**Comment by timmyc** [comment]
So re-reading this issue, I was of the understanding that we were going to implement the form toggle on *all* viewport sizes, but I could have been wrong. And to my question about the location of the Add button - assuming we match what is being done in #145

**Comment by joshuatf** [comment]
@timmyc Just spoke with @josemarques and you're right; we're doing this on all screen sizes and the "Add new" will be aligned right of the page title.
