### ISSUE TITLE
Restyle inputs to be more Calypso-like

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#148]
Form styling is still very much the wp-admin default.  Restyle all default inputs to be more like Calypso.

### Before
<img width="475" alt="screen shot 2018-11-06 at 4 30 09 pm" src="https://user-images.githubusercontent.com/10561050/48094945-744e9b80-e1e1-11e8-9121-bb46917b163e.png">

### After
<img width="692" alt="screen shot 2018-11-06 at 4 30 37 pm" src="https://user-images.githubusercontent.com/10561050/48094943-71ec4180-e1e1-11e8-8324-81f5d3726c23.png">

**Comment by timmyc** [comment]
But we are going to keep the existing form functionality like the `<select />` shown in the `wp-admin` version. Not going to get too crazy.
