### ISSUE TITLE
[GlobalStep] "Country / Region" and "State" dropdowns fail to render properly on shortcode Checkout page.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/wc-calypso-bridge#1495]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

"Country / Region" and "State" dropdowns fail to render properly on shortcode Checkout page.

### Expected behavior

"Country / Region" and "State" dropdowns should render properly on shortcode Checkout page.

### Actual behavior

"Country / Region" and "State" dropdowns fail to render properly on shortcode Checkout page.

### Steps to reproduce

1. Create a test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.2.0-beta.1 plugins.
4. Make sure you are using Block theme (e.g. TT4)
5. Create a new test page and add shortcode for classic checkout page.
6. Add few product to your store.
7. Go to Shop page and add the products to tyour cart
8. Now go to the classic checkout page you created on step 4.
9. Observe that, "Country / Region" and "State" dropdowns fail to render properly on shortcode Checkout page.

### Note:
1. The issue occurs in WooCommerce 9.1.4 and 9.2.0 Beta.

### WordPress Environment

Woocommerce Version: 9.2.0-beta.1
WordPress version: 6.6.2

PC:
Windows 10
Chrome (Version 127.0.6533.89)
Firefox (Version 128.0.3)

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nigeljamesstevenson** [comment]
Issue created in error - will be raised in the appropriate [WooCommerce core repo](https://github.com/woocommerce/woocommerce/issues)

**Comment by nigeljamesstevenson** [comment]
Bug ID: [#50208](https://github.com/woocommerce/woocommerce/issues/50208) raised
