### ISSUE TITLE
[LYS] Disable launch your store on trial sites

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#1504]
### Issue Description

Launch your store is not supported for trial sites since trial sites cannot be viewed by the public. I think the following has to be done, but @adrianduffell please let me know if it's desirable:

- Hide `Site visibility` settings tabs
- Hide `Launch your store` task
- Disable WPCOM coming soon page override implemented in [this PR](https://github.com/Automattic/wc-calypso-bridge/pull/1500)
- Disable the coming soon banner [shown in frontend](https://github.com/user-attachments/assets/02fc7a23-e4b6-406d-835b-0fb454cf4bb2) 

Alternatively, we could disable the `launch-your-store` feature flag, but it'll be a tech debt since we eventually may remove the feature flag altogether.

### Acceptance criteria

1. Apply all of above for trial plans (both ecommerce and business trial plans)

**Comment by beaulebens** [comment]
If it doesn't create too much more work, it seems like "Launch Your Store" is the perfect time to tell users that they need to upgrade/pay so that they can actually launch. Not sure exactly what it should look like, but imagine it being like a "blocker" task in the LYS UI somewhere.

**Comment by ilyasfoo** [comment]
@beaulebens Makes sense for a task to tell users to upgrade since it's the end of the trial setup flow. Engineering wise, it may be relatively simple UI work, but I think we may need design's input to make it effective.

For reference, currently the launch task is a dummy "disabled" task on trial sites ([screenshot](https://github.com/user-attachments/assets/15ea8db3-4efb-46da-98ff-0b1957c78954)).

**Comment by beaulebens** [comment]
Ah I see in the screenshot it's contextually linked with [Upgrade] to make it clear you need to do that before you can Launch, so that's probably OK. Thanks.

**Comment by adrianduffell** [comment]
> Hide Site visibility settings tabs

I think it would be good to keep the tab visible to keep it consistent with screenshots and video tutorials. Perhaps it is another opportunity to place an upgrade message and maybe disable the save button or hide the form altogether 🤔

**Comment by ilyasfoo** [comment]
> I think it would be good to keep the tab visible to keep it consistent with screenshots and video tutorials. Perhaps it is another opportunity to place an upgrade message and maybe disable the save button or hide the form altogether 🤔

Good point, @adrianduffell! I think it makes sense 👍 

Should be appropriate for a follow-up
