### ISSUE TITLE
Issue with Product Vendors in Table

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#152]
With the WooCommerce Product Vendors extension installed, the Vendor table column that is added to the product listing table is appearing quite odd:

![image](https://user-images.githubusercontent.com/22080/48146100-22515880-e269-11e8-8bda-fdcbe0ce94a2.png)

__Steps To Recreate__
- Install Product Vendors
- View Product listing page

**Comment by timmyc** [comment]
Digging a bit more, I turned off some of the columns in the product listing table, and it "fixed" the issue - so guessing the bug will affect any extension that adds a new column - just an overflow issue with the table in general:

![image](https://user-images.githubusercontent.com/22080/48146547-13b77100-e26a-11e8-937a-f75dcdf26e8f.png)

Guessing we might need to consider a horizontal scroll on the table 😱 ... @josemarques any input on the best solution here?

**Comment by josemarques** [comment]
Yuck... but I'm not seeing another solution here.
