### ISSUE TITLE
Notifications still splitting nav and subnav on some pages

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#191]
Related issue was resolved for shipping settings in #122 but appears to still be an issue on other pages (tab manager/wc_product_tab).

<img width="1372" alt="screen shot 2018-11-16 at 5 28 52 am" src="https://user-images.githubusercontent.com/10561050/48582910-c5d4f400-e960-11e8-80b3-5b8ab5f904e8.png">

**Comment by justinshreve** [comment]
Fixed by #202.
