### ISSUE TITLE
Notification FOUC on slower connections

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#193]
On slower connections, notification styling flashes to the default style before showing the Calypsoified style.  Try to:
* Prevent this flash of unstyled content
* Bonus points for hiding the "move" that WP core does for notifications from one div to the other.

<img width="717" alt="screen shot 2018-11-16 at 5 40 20 am" src="https://user-images.githubusercontent.com/10561050/48583592-78f21d00-e962-11e8-8f37-9839675ff5a8.png">

**Comment by justinshreve** [comment]
Fixed by #200.
