### ISSUE TITLE
Product Actions, Narrow Viewport

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#197]
Things are a wee bit crowded in the action bar / header on the products listing page in a narrow viewport:

![image](https://user-images.githubusercontent.com/22080/48590490-7ce75600-e8f4-11e8-8835-73552d659fed.png)

**Comment by joshuatf** [comment]
What are our thoughts on how to best fix/design this?  /cc @josemarques

**Comment by timmyc** [comment]
I think we should hide the actions that aren't as likely to be used in the narrow viewport: so that would display none'ing Import and Export.

**Comment by joshuatf** [comment]
@timmyc Do you think hiding all action buttons except the first would be a safe way to go on smaller viewports?  I think this would work for most WC plugins adding in multiple buttons since (hopefully) the first is the primary action.

**Comment by timmyc** [comment]
Seems like a good solution to me 👍

**Comment by justinshreve** [comment]
Fixed by #210.

**Comment by josemarques** [comment]
@joshuatf circling back to this, are we able to use a split button? 

![screen shot 2018-11-20 at 11 01 31](https://user-images.githubusercontent.com/57050/48769482-af59d000-ecb3-11e8-8e1d-2b851feb84c9.png)

I'm not comfortable with hiding actions just because they don't fit

**Comment by timmyc** [comment]
I don't believe we have a split button component readily available in [WP core](https://github.com/WordPress/gutenberg/tree/master/packages/components/src) but also using a JS component in this context would be a bit interesting.

To me the only other option would be to move the actions outside of the nav bar on smaller viewports.

**Comment by justinshreve** [comment]
Maybe making the action bar scrollable with a shadow could work?

**Comment by josemarques** [comment]
@timmyc I made that mention because it exists in Calypso. 

Are we able to do something like "more" elipsis that reveals the secondary actions?

**Comment by timmyc** [comment]
I'm not personally aware of a Core WP/Woo pattern for that right now. [We have that](https://github.com/woocommerce/wc-admin/tree/master/packages/components/src/ellipsis-menu) in wp-admin, but that isn't currently available for us to utilize at this time.

That would be a bit of an effort to use the new js-based components like that in this context since we don't have a modern js build system in place yet for this project.

I'd prefer us to find a different solution that we already have access to without adding too much more complexity here. Long-term, this code is all temporary, so I'd rather us get things to a stable point, then shift focus back to solving these sorts of problems in wc-admin/woo core. Just my .02 though

**Comment by josemarques** [comment]
Doesn't seem like we have another option rather then hiding those then. 
Regarding @justinshreve's suggestion: I haven't seen that pattern, so it's probably something the users won't expect.

**Comment by justinshreve** [comment]
> Doesn't seem like we have another option rather then hiding those then.

I'm going to close this for now, since it looks like we are sticking with this path. 

Long term, this can be solved by wc-admin improvements to core screens.
