### ISSUE TITLE
Jetpack JITM Style Issues

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#208]
The style doesn't match the other notifications, and the spacing is weird.

<img width="1167" alt="screen shot 2018-11-16 at 1 54 08 pm" src="https://user-images.githubusercontent.com/689165/48641247-2555f280-e9a7-11e8-8259-c8c796c5fb71.png">

**Comment by joshuatf** [comment]
@justinshreve I know I've seen this somewhere before, but I can't seem to replicate anymore.  Where can this be found?

**Comment by justinshreve** [comment]
It shows up for me on the add new order page when Jetpack and WooCommerce Services are connected.
