### ISSUE TITLE
System status report notice styling issue regression

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#212]
The styling on this appears to have regressed, but we can probably tweak @justinshreve 's previous working solution in #177 to get this working again.

<img width="938" alt="screen shot 2018-11-19 at 8 22 15 am" src="https://user-images.githubusercontent.com/10561050/48680261-6e3ebe80-ebd4-11e8-8259-6d6c6f16ebcf.png">

**Comment by justinshreve** [comment]
Fixed by #216.
