### ISSUE TITLE
Extra stripe notices after initial setup

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#232]
I walked through the full eCommerce plan flow (see directions on #231) and I went to the Stripe task from the setup list.

I see a notice that could use some formatting improvements:

<img width="980" alt="screen shot 2018-11-19 at 3 16 56 pm" src="https://user-images.githubusercontent.com/689165/48732773-86333400-ec0e-11e8-8c00-cc68b44bcf9e.png">

and 

<img width="996" alt="screen shot 2018-11-19 at 3 17 07 pm" src="https://user-images.githubusercontent.com/689165/48732784-8c291500-ec0e-11e8-8015-db132c620d8e.png">

which doesn't seem useful.

**Comment by dougaitken** [comment]
Clarification, that first screenshot is before initial connection
