### ISSUE TITLE
Notifs shown on new site

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#250]
On a new site - I'm seeing the notif to run through the Woo setup wizard, and it has some visual glitches:

![image](https://user-images.githubusercontent.com/22080/48797447-0ad98d00-ecb7-11e8-9842-f466c7021d42.png)

Should we suppress this notif, and the Akismet ones by default?

**Comment by joshuatf** [comment]
@timmyc Agreed on those WC notices. 

Do we want to hide all of the Akismet notices or just this one?  This one looks like it might be helpful, but maybe there's something I don't know about how this will connect with the ecomm plan.

Here's a comprehensive list of the Akismet notices - https://github.com/Automattic/vip-go-mu-plugins/blob/master/akismet/views/notice.php

**Comment by joshuatf** [comment]
Also for reference here later, it looks like the only way to remove Akismet notices will be through CSS.
