### ISSUE TITLE
Empty payments screen if no payment options available

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#286]
If a user selects a currency with no available gateways (e.g., AFN), an empty screen is shown:

<img width="582" alt="screen shot 2018-11-23 at 12 31 57 pm" src="https://user-images.githubusercontent.com/10561050/48928618-dc102080-ef1b-11e8-8270-8ee1ed31b394.png">

We should redirect them to the setup checklist in this scenario or at least display a message in place of the empty container.

**Comment by timmyc** [comment]
Thanks for logging this issue - I noticed it too while testing out the shipping extension mapping 🌟
