### ISSUE TITLE
Deactivating WooCommerce results in a 500 error from the Store

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#297]
If you deactivate WooCommerce and navigate to the "Store" link on WP.com:

<img width="316" alt="screen-shot-2018-11-20-at-3-12-56-pm 1" src="https://user-images.githubusercontent.com/10561050/48987102-cb97ba00-f156-11e8-9613-4550febd4c89.png">

You'll get a 500 error:
<img width="829" alt="screen shot 2018-11-26 at 8 38 28 am" src="https://user-images.githubusercontent.com/10561050/48987105-d5b9b880-f156-11e8-8b88-45c4ee4707d8.png">

Props to @apeatling for noting this issue.

We should probably not allow disabling of WooCommerce on the ecomm plans.

**Comment by justinshreve** [comment]
Fixed by https://github.com/Automattic/wc-calypso-bridge/pull/330
