### ISSUE TITLE
Akismet notice persists despite closing

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#298]
When clicking the "X" for the Akismet notice, it just slides closed, but the notice will reappear on next page load.

<img width="840" alt="screen shot 2018-11-26 at 9 03 51 am" src="https://user-images.githubusercontent.com/10561050/48987489-5f1eba00-f15a-11e8-8444-ab5e7fa6eeb7.png">

We should either:
a. Make this dismiss button persistent.
b. Or hide the dismiss button since the real action prompt is to "enable" or "disable."

**Comment by justinshreve** [comment]
Fixed by https://github.com/Automattic/wc-calypso-bridge/pull/332.
