### ISSUE TITLE
No notice to go back to setup checklist after action

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#299]
When users click on an action in the checklist "Do it," they are sent to the action, but may not be able to find their way back as @MarinaWoo noted.

> After creating first product it was unclear how to get back to checklist. I clicked the X top right and went back to dashboard and then saw a notice # – be nice if that showed up on the product creation page, too.

It would be nice if we gave them an easy way to navigate back to the checklist.  Would a dismissible notice be appropriate here?  Something like this:
<img width="704" alt="screen shot 2018-11-26 at 9 14 40 am" src="https://user-images.githubusercontent.com/10561050/48987635-bb360e00-f15b-11e8-981d-33ab95c127ba.png">

/cc @timmyc @josemarques

**Comment by josemarques** [comment]
I like your suggestion above.

**Comment by timmyc** [comment]
I like the suggestion in your original post, and we can base the display of the alert off of the options we are already tracking to show the remaining steps 👍
