### ISSUE TITLE
Setup Checklist should be top-level menu item

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#300]
Since the "WooCommerce" menu items collapse when under the "Product" top level menu item, the Setup should be moved to a top-level to remain always visible.

Icon that should be used: https://developer.wordpress.org/resource/dashicons/#admin-tools

#### Open
<img width="276" alt="screen shot 2018-11-26 at 9 25 26 am" src="https://user-images.githubusercontent.com/10561050/48987880-58457680-f15d-11e8-9b13-fad3ce2d81bc.png">

#### Closed
<img width="278" alt="screen shot 2018-11-26 at 9 25 36 am" src="https://user-images.githubusercontent.com/10561050/48987996-d9047280-f15d-11e8-8d65-432df8096cbd.png">

**Comment by justinshreve** [comment]
Closed by https://github.com/Automattic/wc-calypso-bridge/pull/333.
