### ISSUE TITLE
Buttons should remain same size on hover

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#301]
Button heights change slightly on hover/active state.

#### Shipping -> WooCommerce Services, the "Save Changes"
![screen capture on 2018-11-21 at 17-19-06](https://user-images.githubusercontent.com/10561050/48988229-58467600-f15f-11e8-9477-677062463297.gif)

#### Single Product -> Attributes "Add" button
<img width="399" alt="screen shot 2018-11-26 at 9 44 21 am" src="https://user-images.githubusercontent.com/10561050/48988335-ed496f00-f15f-11e8-9917-6e14c97e5b94.png">

#### Media model "Select files" hover
<img width="367" alt="screen shot 2018-11-26 at 9 45 39 am" src="https://user-images.githubusercontent.com/10561050/48988360-1407a580-f160-11e8-918f-bf304b0a3826.png">

#### Edit permalink button
<img width="530" alt="screen shot 2018-11-26 at 11 32 50 am" src="https://user-images.githubusercontent.com/10561050/48991719-2b9a5a80-f16f-11e8-8e8d-41abca7f3bcb.png">

#### Add media button
![add-media-button](https://user-images.githubusercontent.com/10561050/48991885-0823df80-f170-11e8-8645-4d6c3ad4b712.gif)

**Comment by justinshreve** [comment]
https://trello.com/c/t5EoMsUs/98-buttons-are-vibrating-jiggling-on-multiple-pages

**Comment by justinshreve** [comment]
Fixed by https://github.com/Automattic/wc-calypso-bridge/pull/331.
