### ISSUE TITLE
Media modal select dropdowns overlap images

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#302]
The select boxes are overlapped by the images and the input for searching images does not appear to be Calypso height.

<img width="1045" alt="screen shot 2018-11-26 at 9 45 20 am" src="https://user-images.githubusercontent.com/10561050/48988470-b162d980-f160-11e8-9949-515431871c61.png">

**Comment by justinshreve** [comment]
This looks fixed for me now (though I was able to reproduce the other day). I think one of your style fixes for select2 fixed it.

<img width="1098" alt="screen shot 2018-11-27 at 11 49 18 am" src="https://user-images.githubusercontent.com/689165/49097356-95336b00-f23a-11e8-8b46-409f1d8c1ffe.png">
