### ISSUE TITLE
New product page width should be wider

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#303]
Caused by #282 

We should probably make all `post-new-php` page wraps full width since these will include meta boxes and need a wider area.

<img width="1598" alt="screen shot 2018-11-26 at 10 09 54 am" src="https://user-images.githubusercontent.com/10561050/48989083-980f5c80-f163-11e8-98cf-1c26a57d6ebc.png">

**Comment by justinshreve** [comment]
Fixed by https://github.com/Automattic/wc-calypso-bridge/pull/335.
