### ISSUE TITLE
WooCommerce should be a dependency

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#317]
Not only is it not needed if not activated, but also causes some errors if WC is not activated:

<img width="406" alt="screen shot 2018-11-26 at 4 18 11 pm" src="https://user-images.githubusercontent.com/10561050/49001180-e427c480-f196-11e8-9cd0-a78c8f300e8d.png">

**Comment by jeffikus** [comment]
Nice catch!
