### ISSUE TITLE
Sidebar Setup Number and Setup Checklist Number Mis-Match

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#342]
On a fresh new test site, the number of tasks remaining shown in the sidebar bubble does not match what is shown on the checklist page itself:

<img width="1553" alt="tasks-remaining-mis-match" src="https://user-images.githubusercontent.com/22080/49121886-0ab53080-f267-11e8-8474-d89bc3734977.png">

**Comment by timmyc** [comment]
Thinking it might be related to the shipping tasks, as when I complete them, the sidebar number is not updated:

![image](https://user-images.githubusercontent.com/22080/49121943-4fd96280-f267-11e8-8d0d-a9bbfba8ec8b.png)

**Comment by joshuatf** [comment]
@timmyc Which shipping task did this occur with?  I was not able to replicate with UPS.

**Comment by justinshreve** [comment]
Maybe I was being too cautious/paranoid about catching these? I installed the query monitor plugin and I actually think a number of these are retrieved by `wp_load_alloptions`, and other WC extensions are already grabbing other settings. Maybe we could just drop the caching for now unless it seems to be an issue?

**Comment by timmyc** [comment]
yeah it could very well be cache related since it is hard to reproduce. i suppose we can omit the caching for now to work around the problem.

**Comment by joshuatf** [comment]
I think the caching was a good call, but we'll remove for now since the query load doesn't seem to be too significant and we'll want those correct numbers showing for v1.
