### ISSUE TITLE
Add support links

### ISSUE THREAD

**Issue by justinshreve** [Automattic/wc-calypso-bridge#416]
Per https://trello.com/c/Ks1eKXGt/131-live-chat-support-in-calypsofiy-how-to-add-link-from-setup-checklist, let's add some support links to the checklist and/or sidebar. @sararosso will provide placement / copy.

**Comment by sararosso** [comment]
Let's add this wording to the footer of every wc-admin page: 

> Need help? Read the eCommerce plan support document or get in touch with support.

eCommerce plan support document
links to https://en.support.wordpress.com/ecommerce-plan/

get in touch with support
links to https://wordpress.com/help/contact

And a link in the sidebar: Get Support
links to https://wordpress.com/help/contact
