### ISSUE TITLE
eComm plan checklist: Stripe requires no further setup after account provisioning

### ISSUE THREAD

**Issue by dechov** [Automattic/wc-calypso-bridge#434]
When Stripe account provisioning is enabled, it could be more clear that your payment method is already set up (as far as “things you’ll need to do to get started”) after “Continue”ing from the “Select payment methods” OBW step. (Only true when an email is submitted that doesn’t already have a Stripe account.) In particular, the “Setup payments with Stripe” checklist item could appear in an already completed state – currently it does not due to https://github.com/Automattic/wc-calypso-bridge/pull/255.

However, the need for account activation before being able to accept payments (applies for U.S. merchants after July 31 due to the CDD rule) is important to consider, since in this case there will be more for the merchant to do – albeit on stripe.com, not in the store – before payments will work (see https://github.com/Automattic/woocommerce-services/issues/1590).

**Comment by pmcpinto** [comment]
👋 I'm going to close this issue as we're going to implement the new onboarding experience that we have on Core
