### ISSUE TITLE
eComm plan styling: Stripe connected account indicator could use tweaks

### ISSUE THREAD

**Issue by dechov** [Automattic/wc-calypso-bridge#435]
The styling of the Stripe account indicator box, despite being imported from Calypso, isn’t fully optimized for Calypsoify, especially the spacing/background (see 5th screenshot in p7bbVw-2UD-p2).

@timmyc in a comment there, on enabling plugins to fix this on their end:
> Wondering if we maybe add a body class or something to wc-calypso-bridge that we can then add css logic specific to that environment in the requisite plugings like WCS to style things more calypsoify-ish. I thought we had a class or a way to toggle for e-comm plan but I’m not seeing one jump out at me as i look at the source.
> 
> Anyhow that would allow any plugins ( WCS included ) to manipulate styling of their elements without having to add more css logic to calypso-bridge.

**Comment by DanReyLop** [comment]
> Wondering if we maybe add a body class or something to wc-calypso-bridge that we can then add css logic specific to that environment in the requisite plugings like WCS to style things more calypsoify-ish.

I think that logic makes more sense in Calypsoify itself (so, Jetpack). Adding a "`calypsoifyed`" class to the `<body>` (or you know, a better name) allows all kinds of plugins to style themselves better when they're being used on a Calypsoified page.
