### ISSUE TITLE
Store: /wc/v3/settings_email_groups returning 404

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#443]
__To Reproduce__
- On a store on wordpress.com site, visit the Settings > Email page
- Notice the screen is perpetually loading
- In your js console, network tab, note a 404 is being returned for `https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/133267589/rest-api/?http_envelope=1&path=/wc/v3/settings_email_groups&_via_calypso&_method=get&json=true`

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/22080/58296891-75fd3c80-7d8a-11e9-8e05-af88bb9a735d.png">

**Comment by justinshreve** [comment]
@timmyc I was able to reproduce this on my test site so I started to do some digging. I noticed that my test store had the eCommerce Plan flag set (`at_options` with `plan_slug` set to `ecommerce`).

When in eCommerce Plan mode, old Store.com legacy code is not loaded by `wc-calypso-bridge`. Setting this option to false and refreshing allowed the email settings to fully load. I was also able to save settings. This looks fine for normal production stores and should only crop up by manually toggling the flag.

Could you check your `at_options` and confirm as well?

**Comment by timmyc** [comment]
Indeed I'm pretty certain that is why I hit this bug too - ran into it again yesterday and realized it was due to my wpsandbox site being setup as an ecomm site. Confirmed all is working with the email section yesterday on the latest wpcomsh, plus the version where wc-api-dev was removed so I think we are good to close this out. Sorry for not looping back on it when I discovered it yesterday 🤦‍♂
