### ISSUE TITLE
Calypsoify obw script not loaded during wizard

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#445]
The script located at `assets/js/calypsoify-obw.js` is not loaded during the wizard and prevents the "Continue" button from working.

There was previously an issue with not all scripts being loaded on this page since the default admin template footer is never called.  Further investigation is probably needed to determine why the `admin_enqueue_scripts` hook does not enqueue all scripts.

### To reproduce:

1.  Visit `wp-admin/index.php?page=wc-setup`.
2.  Note the above script is never loaded.
3.  Click "Continue"
4.  Note that the page does not change.

### Screenshot
<img width="595" alt="Screen Shot 2019-06-11 at 4 04 55 PM" src="https://user-images.githubusercontent.com/10561050/59254522-f06efd00-8c62-11e9-92a8-8edc3313ff52.png">

**Comment by mattsherman** [comment]
@joshuatf Thanks for working on this! This is a critical blocker for the WordPress.com eCommerce plan, so please let @Automattic/start-samus know if there is something we can do to help test/verify a fix once it is in place.

/cc @michaeldcain

**Comment by joshuatf** [comment]
Hi @mattsherman - the PR for this has already been merged in on bridge.  I have an [open PR](https://github.com/Automattic/wpcomsh/pull/284) on wpcomsh to bump the version and then we just need to open a systems request to deploy once that's merged.

Closed via https://github.com/Automattic/wc-calypso-bridge/pull/446

**Comment by mattsherman** [comment]
@joshuatf Awesome. Thank you very much for the quick turnaround!
