### ISSUE TITLE
Setup screens should match the current appearance of WP.com start screens

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wc-calypso-bridge#447]
Steps to reproduce:

1. Start with a test site with the eCommerce plan on WP.com, or locally, with wc-calypso-bridge set up.
2. Navigate to [mysite.com]/wp-admin/admin.php?page=wc-setup
3. Observe the appearance of the screen:

<img width="1391" alt="Screen Shot 2019-06-12 at 1 49 09 PM" src="https://user-images.githubusercontent.com/177561/59385372-0939ea00-8d19-11e9-9f3f-82fb9bb5f090.png">

The design of the ['start' pages on WordPress.com](https://wordpress.com/start) that this was based off of has since changed -- they have a solid coloured background, and different fonts:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/177561/59385458-3eded300-8d19-11e9-86a3-fd8437c62f81.png">

The screens in wp-calypso-bridge should be updated to match the same styles, to create a more consistent experience. 

Moved over from:

https://github.com/Automattic/wp-calypso/issues/33041

**Comment by laurelfulford** [comment]
I started digging into this, and it seems to be a bit more than just swapping a couple colours and fonts on the two setup screens. 

Here's what that would look like in action:

<img width="1190" alt="Screen Shot 2019-06-12 at 3 45 35 PM" src="https://user-images.githubusercontent.com/177561/59391650-d2b89b00-8d29-11e9-9dd5-9363fbfe8330.png">

<img width="1174" alt="Screen Shot 2019-06-12 at 3 45 49 PM" src="https://user-images.githubusercontent.com/177561/59391658-d6e4b880-8d29-11e9-87d1-cb590c90f7a9.png">

There are two issues:

1. The masterbar is visible on these screens, and with the background update, it blends into the background.
2. The button styles controlling the colours (the original blue, and the updated pink) actually live in Jetpack [here](https://github.com/Automattic/jetpack/blob/b0600d38a06de249f42b7b4b1906a2e0d5177357/modules/calypsoify/style.scss#L731). In experimenting with the styles, I added overrides in this plugin, but ideally that would happen in Jetpack - it looks like there's already a PR here: https://github.com/Automattic/jetpack/pull/12359

I wonder, as an intermediate step, if we could improve the background and fonts, but leave the button colours to Jetpack, and the blue background to whether or not we want to remove the masterbar -- something like:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/177561/59392035-0e079980-8d2b-11e9-8e94-ded04f853610.png">

@sixhours I'd appreciate your thoughts here, since we already discussed approaches to fixing this issue. Thanks!

**Comment by sixhours** [comment]
> I wonder, as an intermediate step, if we could improve the background and fonts, but leave the button colours to Jetpack, and the blue background to whether or not we want to remove the masterbar -- something like:

This seems like a solid step in the right direction. I think @jeffikus is working on the ticket that removes the masterbar from this screen, too, which could make that a non-issue if it gets done soon-ish. 👍 from me!

**Comment by laurelfulford** [comment]
Thanks @sixhours! I'll push up a PR with the suggested partial fix, and it can be refined more once the masterbar is gone and button colours are updated :)

**Comment by jeffikus** [comment]
@laurelfulford @sixhours I've submitted https://github.com/Automattic/wp-calypso/pull/33921 to hide the masterbar.
