### ISSUE TITLE
Remove the master bar from the setup screens

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wc-calypso-bridge#449]
Related to the work being done in #447 for [fix the flows](https://github.com/Automattic/wp-calypso/labels/FixTheFlows):

To better match the appearance of the https://wordpress.com/start screens, and to allow us to switch the background colour of the setup screens to the dark blue, the standard masterbar should be hidden from these screens.

There are a couple things to consider:

1. Without the masterbar, there's no way to navigate back or out of the screen -- you lose your site link at the top:

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/177561/59394518-c980fb80-8d34-11e9-9bab-04f503b48de7.png">

2. The top of the https://wordpress.com/start pages include a Back button, as well as the current step -- a similar approach would help make these screens more similar, and would be a good work around to issue #1. 

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/177561/59394545-e1f11600-8d34-11e9-93e8-f967cb5a3142.png">

The removal/update of this master bar, paired with the updated button colour work being done in Jetpack (https://github.com/Automattic/jetpack/pull/12359), will ultimately let us change the background colour of this screen to the dark blue. 

**Steps to reproduce:** 

1. Navigate to [mysite.com]/wp-admin/admin.php?page=wc-setup and http://dev.wordpress.test/build/wp-admin/admin.php?page=wc-setup&step=payment, and note that there is a masterbar.
2. Compare to https://wordpress.com/start, which does not.

**Comment by timmyc** [comment]
This issue is no longer relevant with our migration to the new WooCommerce setup wizard, closing out.
