### ISSUE TITLE
Change the background of the setup screens to dark blue

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/wc-calypso-bridge#450]
This is related to the work being done for #447, and is dependent on #449 and https://github.com/Automattic/jetpack/pull/12359 before it can be completed:

The background colour on the two setup screens for WC should use the same dark blue background as https://wordpress.com/start

Screens:
/wp-admin/admin.php?page=wc-setup
/wp-admin/admin.php?page=wc-setup&step=payment

**Comment by timmyc** [comment]
Likewise here, the new WooCommerce Setup Wizard does not display the masterbar so closing this one out.
