### ISSUE TITLE
Fatal error if Jetpack_Calypsoify is not found

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#452]
If you attempt to connect without a connected Jetpack site, or without the Jetpack dev filter, you'll get the following fatal error:

<img width="460" alt="Screen Shot 2019-06-17 at 4 14 49 PM" src="https://user-images.githubusercontent.com/10561050/59588931-4d632b00-911b-11e9-9851-7b2d090b2495.png">

### To reproduce:

1. Go to `wp-admin/admin.php?page=wc-setup`.
2. Disconnect Jetpack and remove any Jetpack dev filters.
3. Note the error.

There's a note about always including this file in ecommerce plans.  I wonder if that ever shouldn't meet the default dependencies or if we should just check for `Jetpack_Calypsoify` in the setup file. /cc @justinshreve 

https://github.com/Automattic/wc-calypso-bridge/blob/b86e59591a52ab405741293ea2c296eb5e97b252/class-wc-calypso-bridge.php#L121

**Comment by justinshreve** [comment]
I think eCommerce plans should always have Jetpack setup, but of course bad things can happen. So I agree we should do a check for the class and stop execution early 👍.
