### ISSUE TITLE
Post Counts, parens inside <Count />

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#458]
When viewing a post listing page, like orders, the type totals shown at the top have styling in place to emulate the `<Count />` component of calypso. But inside the count "bubble" the numbers are displayed inside parenthesis, which looks quite odd. Seems like we should just do one or the other.

![order-counts-parens](https://user-images.githubusercontent.com/22080/61161064-f8ff6100-a4b6-11e9-8587-72f77e86b11a.png)

**Comment by jeffstieler** [comment]
Opened a PR in Jetpack to fix: https://github.com/Automattic/jetpack/pull/13110
