### ISSUE TITLE
Sidebar double triangle arrow oddity

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#459]
When looking closely at the "Store" accordion in the sidebar, it appears there are two different < triangles ... almost looks like a little fish mouth - which brings me happy thoughts, but visually looks off.

![double-triangle-arrows](https://user-images.githubusercontent.com/22080/61161132-5693ad80-a4b7-11e9-9603-b5884542c289.png)

**Comment by joshuatf** [comment]
I think this is actually an issue from wc-admin.  Wc-admin adds the psuedo element triangle on `.woocommerce-page .wp-has-current-submenu:after` whereas WP adds it to `ul#adminmenu a.wp-has-current-submenu:after, ul#adminmenu > li.current > a.current:after`.

<img width="282" alt="Screen Shot 2019-07-23 at 11 34 11 AM" src="https://user-images.githubusercontent.com/10561050/61680905-e4845980-ad3d-11e9-91ba-af36dea6ff0d.png">

Non-calypsoified version this exists as well (but only by a pixel it seems).

<img width="323" alt="Screen Shot 2019-07-23 at 11 33 26 AM" src="https://user-images.githubusercontent.com/10561050/61680906-e4845980-ad3d-11e9-8f19-3686661623ba.png">

**Comment by jeffstieler** [comment]
@joshuatf whoops! I forgot to assign this to myself - I've opened a PR for it: https://github.com/woocommerce/woocommerce-admin/pull/2687
