### ISSUE TITLE
wc-admin breaks the ecomm plan

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#461]
After installing wc-admin on an ecomm plan site, the top-level menu item for WooCommerce is properly updated to the dashboard, but when you attempt to load the dashboard, an exception is thrown:

![image](https://user-images.githubusercontent.com/22080/61161431-80010900-a4b8-11e9-9c98-b55be353e6dd.png)

**Comment by rrennick** [comment]
@timmyc Can you confirm this one is okay to close with #471 ?

**Comment by timmyc** [comment]
Confirmed against `master` all is looking happy now!
