### ISSUE TITLE
Setup Checklist: Product task not marked done after product created

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#464]
As noted by @pmcpinto [here](https://docs.google.com/presentation/d/1HG2542dQztspXQ4CbKXNrXcxNdGjC0lhwX_kD2KHNps/edit#slide=id.g5d7a2319be_0_15) and noted in my screen recording, after a product is created, or if a product(s) already exist, the step to add a product in the checklist is not being marked as completed.

__Steps to recreate__
- on a new ecomm plan, create a new product
- return to the setup checklist and note the item is still being shown as not completed.

**Comment by pmcpinto** [comment]
I'm going to close this issue, as we're going to implement the task list that we have on WC Core
