### ISSUE TITLE
Mailchimp: Double Settings Saved notices

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#466]
[As noted](https://docs.google.com/presentation/d/1HG2542dQztspXQ4CbKXNrXcxNdGjC0lhwX_kD2KHNps/edit#slide=id.g5d7eab02ec_0_5) by @pmcpinto - after saving a MailChimp API key, two notices are being displayed that settings have been saved.

Perhaps the plugin is adding an admin_alert on top of what Woo core is already doing?

**Comment by joshuatf** [comment]
Oddly, I'm unable to replicate or even get a single "Settings saved" notice.  Taking a stab in the dark, it looks like it may be coming from default WP notice in wp-admin/options-head.php since Mailchimp doesn't seem to contain that string.

**Comment by timmyc** [comment]
I can't reproduce this anymore either. closing.
