### ISSUE TITLE
Store: Remove wc-api-dev dependency

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#467]
`wc-api-dev` [is still flagged as a dependency](https://github.com/Automattic/wpcomsh/blob/master/composer.json#L12) in wpcomsh. The vision was to move any custom REST endpoints needed for store to this plugin - which has been done - and remove wc-api-dev completely.

Really the repo needs to be retired too now that we have a set repo/package for Woo REST API development.

@justinshreve had attempted to remove this prior, and I believe some issues were hit with load order. See #432 for the prior PR and notes.

**Comment by jeffstieler** [comment]
I must be missing something - this seems to work without any code changes for me.

What I did have to do to get things working was to remove my `at_options` option, or at least change the `plan_slug` to not be `ecommerce`.

There is a check to not load the class with the rest routes if the site is an ecommerce plan: https://github.com/Automattic/wc-calypso-bridge/blob/master/wc-calypso-bridge.php#L53-L56

**Comment by timmyc** [comment]
Hmmm interesting! Well lets ready a wpcomsh PR that removes the dependency then. We can then test it out against some Store sites to verify. Thanks for looking into it @jeffstieler
