### ISSUE TITLE
Calypso Header/Toolbar overlays WC Admin header

### ISSUE THREAD

**Issue by rrennick** [Automattic/wc-calypso-bridge#468]
This is probably just the height difference between the WP admin bar and the Calypso one.

<img width="1343" alt="Screen Shot 2019-07-18 at 10 58 46 AM" src="https://user-images.githubusercontent.com/343847/61463603-216ddc00-a94b-11e9-9d68-f73dd78b44a4.png">

vs

<img width="1342" alt="Screen Shot 2019-07-18 at 10 59 20 AM" src="https://user-images.githubusercontent.com/343847/61463619-2894ea00-a94b-11e9-82a8-7fdf64e5347a.png">

**Comment by psealock** [comment]
With the changes in https://github.com/Automattic/wc-calypso-bridge/pull/471, we get the Calypso header, so I don't think this will be an issue:

![Screen Shot 2019-07-22 at 12 52 32 PM](https://user-images.githubusercontent.com/1922453/61599722-cd7f3200-ac7f-11e9-8d0e-ceabca79fe38.png)

Looks like there is some spacing problem going on.

**Comment by psealock** [comment]
https://github.com/Automattic/wc-calypso-bridge/issues/462 speaks to the larger issue of the header, spacing, and activity panel.

>What to do about the navigation bar and activity panels. Do we disable them on the ecomm plan as there is redundant breadcrumbs/screen titles. Perhaps we keep the activity panels still?

Should we close this one in favor of that #462?

**Comment by rrennick** [comment]
> Should we close this one in favor of #462?

Closing.
