### ISSUE TITLE
Menu hover/focus colors are incorrect

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#487]
Something is causing some of the menu items to have the wrong hover and focus colors.  This is probably related to CSS selector specificity.

### WC Calypso Bridge
<img width="281" alt="Screen Shot 2019-07-24 at 4 22 50 PM" src="https://user-images.githubusercontent.com/10561050/61777421-7324d380-ae2f-11e9-8ad9-b27e41fa19a5.png">

### Correct Calypso Styles
<img width="283" alt="Screen Shot 2019-07-24 at 4 22 39 PM" src="https://user-images.githubusercontent.com/10561050/61777429-74560080-ae2f-11e9-8b03-410c1e1d40c8.png">

**Comment by justinshreve** [comment]
There is also an issue with the the dashboard link when running `wc-admin`. The entire menu becomes blue:

<img width="275" alt="Screen Shot 2019-12-11 at 5 54 56 AM" src="https://user-images.githubusercontent.com/689165/70615633-c7600280-1bda-11ea-9b8e-ae5101272afb.png">

**Comment by timmyc** [comment]
Just testing this out and all appears to be well here now, also with the planned changes to use new nav, closing this as won't fix.
