### ISSUE TITLE
Migrate Store-Specific Endpoints

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#49]
Background: https://github.com/woocommerce/woocommerce/pull/20116

In preparation for `wc/v3` endpoints from `wc-api-dev` being merged into core - there are two endpoints that are not going to be migrated:

- `products/reviews`
- `data/counts`

This issue will need to involve removal of the above endpoint logic from `wc-api-dev`, and moving the same endpoint code to `wc-calypso-bridge`. It sounds like both endpoints, in some form or another may make their way into core eventually, but until then we will need to get the logic for them into this plugin so Store users can still utilize the functionality.

**Comment by justinshreve** [comment]
I'm happy to tackle this 👍
