### ISSUE TITLE
WC Admin table pages needs CSS tweaks

### ISSUE THREAD

**Issue by rrennick** [Automattic/wc-calypso-bridge#492]
The Rows per page in a WC Admin table:

<img width="885" alt="Screen Shot 2019-07-25 at 4 56 37 PM" src="https://user-images.githubusercontent.com/343847/61904473-4a6b0f80-aefd-11e9-9e54-44587bff2d5b.png">

**Comment by jeffstieler** [comment]
I'm unable to reproduce this on `master`:

<img width="536" alt="Screen Shot 2019-08-06 at 10 12 42 AM" src="https://user-images.githubusercontent.com/63922/62556760-d1d84d00-b832-11e9-855c-e6f845a77326.png">

Is there a build step I'm missing? I didn't see anything other than some composer dependencies.

**Comment by rrennick** [comment]
I'm not seeing it now either. This has probably been fixed through the combination of other CSS fixes applied during hack week.
