### ISSUE TITLE
Stripe warning showing up during set up

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#497]
I followed the checklist to add a new product and Stripe is throwing a warning:

https://cloudup.com/cslNBYNdCOe

This shouldn't show for new stores.

**Comment by warrendholmes** [comment]
More warnings :|

https://cloudup.com/cAppdkWHmYc

This time Akismet came up too.

**Comment by timmyc** [comment]
Doing a bit of clean up of old issues here, and with the plans to migrate to new nav eventually, thinking this is one we will likely not fix. Furthermore, not sure about the practice of suppressing extension-created admin notices is a practice we should continue to do. It is a game of whack-a-mole that really creates quite a bit of tech debt, and possibly hampers the experience intended by extension developers.
