### ISSUE TITLE
UPS Warning

### ISSUE THREAD

**Issue by warrendholmes** [Automattic/wc-calypso-bridge#498]
After following the checklist item to set up my UPS settings, I get a UPS warning 😅

https://cloudup.com/c-qVeUkn56L

**Comment by timmyc** [comment]
Doing a bit of clean up of old issues here, and with the plans to migrate to new nav eventually, thinking this is one we will likely not fix. Furthermore, not sure about the practice of suppressing extension-created admin notices is a practice we should continue to do. It is a game of whack-a-mole that really creates quite a bit of tech debt, and possibly hampers the experience intended by extension developers.
