### ISSUE TITLE
Docs dev setup doesn't work as expected

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#516]
The docs recommend this snippet to enable the bridge ecommerce plan styles:

```php
add_filter( 'pre_option_at_options', function() {
	return [ 'plan_slug' => 'ecommerce' ];
});
```

But this only works if loaded before bridge, so it may not work for some plugins and all themes.  We might want to update this to an `update_option()` solution instead to cut down on troubleshooting during setup.

**Comment by timmyc** [comment]
The docs on setup have since diverged from this approach, and the current approach has been documented here p90Yrv-1O5-p2
