### ISSUE TITLE
Breadcrumbs are being shown in settings table

### ISSUE THREAD

**Issue by joshuatf** [Automattic/wc-calypso-bridge#518]
The breadcrumbs seem to be somehow hooked to the settings table.

### Screenshots
<img width="433" alt="Screen Shot 2020-01-21 at 8 52 42 PM" src="https://user-images.githubusercontent.com/10561050/72806549-607d4100-3c90-11ea-8b49-523e96f29523.png">

### To recreate
1. Enable calyosoify bridge.
1. Visit Settings->Payments->Stripe.
1. Scroll to the bottom.
1. Note the breadcrumbs.

**Comment by timmyc** [comment]
I'm not seeing this anymore so closing out.
