### ISSUE TITLE
Select elements sytling issues

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#519]
When viewing pages with Select elements, the styling appears a bit off:

<img width="602" alt="WooCommerce settings ‹ ecomm woo test — WordPress - Mozilla Firefox 2020-02-24 17-13-33" src="https://user-images.githubusercontent.com/22080/75206088-74521200-572a-11ea-9ffc-8088b99ca4b1.png">

Visit `wp-admin/admin.php?page=wc-settings&tab=general` to reproduce

**Comment by timmyc** [comment]
Seeing this in a few other spots too, Order listing page:

![orders-filter-registered-customer-select](https://user-images.githubusercontent.com/22080/75281900-eecf7000-57c4-11ea-9c12-ff6c85d38ffc.png)

**Comment by psealock** [comment]
In removing Calypsoify this will no longer be an issue, closing.
