### ISSUE TITLE
Customizer: Update tooltip copy when switching to Storefront theme

### ISSUE THREAD

**Issue by kyleaparker** [Automattic/wc-calypso-bridge#52]
Continued from this converation: https://github.com/Automattic/wp-calypso/issues/24663#event-1639763000

We need to alter either the CSS or the copy in the following tooltip to remove the widow:

**Option 1: Reduce width of the tooltip**

<img width="1506" alt="40728751-d4e6ceac-63f8-11e8-8976-c9e67936e790" src="https://user-images.githubusercontent.com/712873/40861316-9cc664a0-65b6-11e8-8293-dac70035b5ea.png">

To this:

<img width="720" alt="40728860-0f6d9c54-63f9-11e8-815b-7712d4d3681f" src="https://user-images.githubusercontent.com/712873/40861319-9f885d56-65b6-11e8-840d-06638f1c0ae3.png">

**Option 2: Change the message**
Current: Click the change button and select Storefront to get started
Alternative: Click the change button and select the Storefront theme to get started

cc @timmyc

**Comment by timmyc** [comment]
Closing this out as we likely aren't going to continue to support this customizer tour.
