### ISSUE TITLE
Two Setup Task Lists

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#520]
With WooCommerce Beta 1 installed on a local copy of the ecomm plan, I'm seeing both the ecomm plan setup checklist, and the new onboarding checklist present:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22080/75206273-e4f92e80-572a-11ea-923f-131cec48e495.png">

and

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22080/75206292-efb3c380-572a-11ea-82e4-c07a87f25e17.png">

@pmcpinto which of these two should be shown on the ecomm plan?

**Comment by pmcpinto** [comment]
@timmyc I think that as for now we should simplify and keep the legacy task list. We can reevaluate if it makes sense to change it for the new cycle (depending on if we can remove calypsoify).

cc @jameskoster for any additional feedback.

**Comment by timmyc** [comment]
Okay for 4.0 I'm going to disable the new wc-admin task list on the ecomm plan.

**Comment by timmyc** [comment]
shipped in #521
