### ISSUE TITLE
Tracks: Add New Prop For E-Comm Plan

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#527]
With https://github.com/woocommerce/woocommerce/pull/25851 set to land in 4.1, we can now implement these new filters here in wc-calypso-bridge to add props to each track to denote them as "sourced" from ecommerce plan.

Since we only want to track events specific to the ecommerce plan sites, I'm thinking creating a new class and including it, akin to most that live in https://github.com/Automattic/wc-calypso-bridge/tree/master/includes would be a good way to go here.

**Questions**
@pmcpinto we need to determine the name of the `prop` and the `value` specifically to use for the ecomm plan sites.

Should we use `host` for the prop name and `ecommplan` as the value?

**Prior Art**
I created the following [gist](https://gist.github.com/timmyc/edf820bded9a805a0746751a421bfb8a) with some examples of how to implement the filter in JS and PHP.

**Comment by pmcpinto** [comment]
> Should we use host for the prop name and ecommplan as the value?

Hey @timmyc, that approach looks good to me.

What will be necessary if in the future we want to start filtering the events by more hosts? Do we need to change anything on our side or it will be just on the host side? Thanks

**Comment by timmyc** [comment]
> if in the future we want to start filtering the events by more hosts? 

They will have to take the code we implement here, and duplicate it in their environment, ideally in some sort of `mu-plugin` logic that is loaded on any site running WooCommerce.

**Comment by pmcpinto** [comment]
Got it. Thanks for the clarification.
