### ISSUE TITLE
Removing Calypsoify from the WooCommerce pages (new users)

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#530]
We're going to remove Calypsoify from the WooCommerce pages, as part of the effort to have a cohesive store experience across the eCommerce plan and WooCommerce core. This change should only target new eCommerce plan users. We plan to see first how this is going to impact that target audience, eventually fix some bugs, and then we'll transition all the existing eCommerce plan users to the new experience. 

How will this work in practice? 
When the user clicks in the Store item in the Calypso menu he will be redirected to WooCommerce without the Calypso styles. But instead of seeing the wp-admin menu, we'll display the new WooCommerce navigation. The user can navigate back the Calypso menu by clicking in the Manage site item in the new WC nav. It will allow us to:
- Avoid overwhelming new users with the wp-admin menu
- Start testing the new navigation before we start rolling it out in wc-admin for anyone that wants to use it (p2 about the roll-out plan for the navigation coming soon)

Beware of Beau's comment regarding the technical implementation to target just new eCommerce plan users:

> let’s make sure it’s possible to either ship a custom plugin to some portion of these users, or that we’re able to somehow else target the new experience to only new users. I believe in the current model, WooCommerce is a “managed plugin” on Atomic sites, which means it’s controlled at the system level, and is the same for all users, so we’ll need to sidestep that or include the logic for all users, but conditionally change things for “new” folks.

**Comment by pmcpinto** [comment]
@jameskoster @timmyc, I noticed that Calypso hides the wp-admin notices and if we remove Calypsoify from the WC pages we'll start displaying those notices, which can be annoying. I'm thinking that one workaround could be bringing back the WP notices to the activity panel, just for eCommerce plan users. What do you think?

**Comment by timmyc** [comment]
Well the "default" behavior from Woo Core would then take over for notices, so they would be shown on all pages except wc-admin powered pages ( analytics + analytics dash ). I think it might be worth considering using the ecomm plan to explore solutions for wordpress notifs.

**Comment by jameskoster** [comment]
The problem with the notices panel in the AP is that important messages were getting lost. An alternative approach would be just display notices on the legacy wp-admin screens, and to use our site-wide notice feature on wc-admin screens to do something like this:

![notices](https://cldup.com/oarSzcnNnr.gif)

**Comment by timmyc** [comment]
I like that approach - keeps it subtle, yet still discoverable.

**Comment by pmcpinto** [comment]
That's a really nice approach. @timmyc is there an easy way to hide the notifications on the legacy wp-admin screens? Seeing something like this it's far from ideal, especially in the eCommerce plan: https://d.pr/i/jsYDon

**Comment by jameskoster** [comment]
One note on the concept above: I don't know if it would be possible, but if we can apply an appropriate `status` to the containing `Notice` component, based on the currently active messages that would be great. 

IE - If one of the messages has the class `notice-error`, set the status to `error`. Else if one of the messages has the class `notice-warning` or `updated` set the status to `warning`. Else if one of the messages has the class `notice-success` set the status to `success`. Then just fallback to the default `info`.

That would help give an indication of notice importance without having to open the drawer.

**Comment by timmyc** [comment]
@pmcpinto are we still considering this approach, or are we going to just focus fully on new nav?

**Comment by pmcpinto** [comment]
> @pmcpinto are we still considering this approach, or are we going to just focus fully on new nav?

I think that we'll have more impact if we just focus on the new nav. What do you think?

**Comment by timmyc** [comment]
Totally agree that I think we should just focus on new nav at this point. Going to close this one out then.
