### ISSUE TITLE
Add new value in the Host prop to check eComm plan usage outside of the calypsoified views

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#542]
Add an event property to track when the eCommerce plan users are interacting with WooCommerce outside of the calypsoified views.

This is a follow up of the discussion that started here: #536

**Comment by pmcpinto** [comment]
After checking several customers using WooCommerce outside of Calypso it seems that we're only seeing part of the picture until we implement this event prop (more than I imagined 😄 ) So the sooner we can implement this prop the better. 

cc @timmyc

**Comment by timmyc** [comment]
Gotcha, what should the `host` prop value be for these actions? `ecom-wpadmin`?

**Comment by pmcpinto** [comment]
Yep, that name works perfectly. Thanks!

**Comment by pmcpinto** [comment]
@timmyc is it possible to also include a value or new prop that allows us to see the Business users activity?
