### ISSUE TITLE
Adjusting the new Woo home to Calypsoify

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#543]
Once the new home screen is ready (#4080), it's necessary to make sure that it works well with Calypsoify, so it can be deployed in the eCommerce plan.

**Comment by pmcpinto** [comment]
cc @timmyc

**Comment by pmcpinto** [comment]
@timmyc is there a way to check this before the Core release?

**Comment by timmyc** [comment]
@pmcpinto I just Dm'ed you some credentials on a test site. Since Woo is a symlinked install on the ecom plan sites, you can't easily update using the beta tester plugin.

**Comment by pmcpinto** [comment]
> @pmcpinto I just Dm'ed you some credentials on a test site. Since Woo is a symlinked install on the ecom plan sites, you can't easily update using the beta tester plugin

Thanks, I'm going to close this one, as the Home Screen seems to be working properly on the eComm plan: https://d.pr/i/6rbDU3
