### ISSUE TITLE
add_settings_error is being redefined.

### ISSUE THREAD

**Issue by jhnstn** [Automattic/wc-calypso-bridge#55]
We got a report of `add_settings_error` is being redefined. 
@seanosh traced it back to https://github.com/Automattic/wc-calypso-bridge/blob/master/inc/wc-calypso-bridge-mailchimp-add-settings-error.php#L25

Original Issue: https://atomicrequests.wordpress.com/2018/08/21/errors-with-regenerate-thumbnails-plugin-on-eye-render-com/
Slack convo: https://a8c.slack.com/archives/C4MJE0MHB/p1535565084000100

cc @druesome

**Comment by iamgabrielma** [comment]
The user keeps coming back asking for an update, is there any ballpark timeline or priority we could provide?
