### ISSUE TITLE
Disable WC Tracker when user disables tracking in the Privacy setting

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#551]
Currently the usage tracking in WooCommerce pages is automatically disabled when the user disables usage tracking in the Privacy Settings: https://wordpress.com/me/privacy

In order to keep all the tracking settings in one place, we should add a filter that also disables WC Tracker when the user turns off that setting.

**Comment by pmcpinto** [comment]
@timmyc I think this covers our chat with Legal

**Comment by timmyc** [comment]
Based off what @deltaWhiskey shared in the chat too - WC Tracker _should_ not send any data if the site has opted out of Tracks. But in looking around at the code in Woo core, I don't see any logic in the method that fires via cron to check for the value of that setting.

https://github.com/woocommerce/woocommerce/blob/172ceb51e8e63f23142a71f23a2415bf1c5b938a/includes/class-wc-tracker.php#L41

It looks like the event gets scheduled to run daily on install [here](https://github.com/woocommerce/woocommerce/blob/7fb1079137ca4969a2b2b8bc6100d21539f23458/includes/class-wc-install.php#L489).

Dan is there another place where the check for the site's tracking preference is happening?

**Comment by deltaWhiskey** [comment]
I think it would be ideal if WC Tracker did not send any data if the site owner has opted out of tracks, but here's my understanding of what's actually happening now:

* The monthly snapshots do not interact with the site owner's WordPress.com privacy setting in any way.
* The tracks events (`wcadmin_*`) will still get sent, but events associated with the opted-out WordPress.com user will be filtered out on the receiving end. Events associated with other users on that site will still be stored normally.

Not really WC Tracker, but related: the shopper-tracking `woocommerceanalytics_` Tracks events from Jetpack ignore the WC Tracker opt-out. They honor the WordPress.com privacy settings on a per-user basis, not a per-site basis.

@timmyc you're looking in the right place for stopping WC Tracker snapshots from being sent. I don't know of anything currently in place to make that honor WordPress.com privacy settings.

**Comment by timmyc** [comment]
Thanks @deltaWhiskey for the input.

> you're looking in the right place for stopping WC Tracker snapshots from being sent. I don't know of anything currently in place to make that honor WordPress.com privacy settings.

Yes that is a tricky one since not all Woo users will have an associated WPCOM account, so I think the solution in place right now to filter the track events in wpcom is the best approach there.

As for Tracker sending data, sounds like we will add some logic there to not send the tracker snapshots if users have opted out. @pmcpinto thinking we should move this issue to `woocommerce/woocommerce` instead since the change should happen in core and roll to all users.

**Comment by pmcpinto** [comment]
Sounds good. I created an issue here: #26689

**Comment by timmyc** [comment]
Closing this in favor of the woo core issue.

**Comment by deltaWhiskey** [comment]
Just a heads up: once the filter is implemented per https://github.com/woocommerce/woocommerce/issues/26689 , Calypso will still need new code to leverage the filter.

**Comment by rrennick** [comment]
@deltaWhiskey Can you clarify what filter you are referring to? WC doesn't load the tracker class if the user has opted out of tracking.

**Comment by deltaWhiskey** [comment]
I don't think such a filter exists yet.

WC's "opt out of tracking" setting is working well. There's a concern on the hosting (Calypso) side that people will opt out of tracking via Calypso, and not understand that WC has a separate opt-out. They want the Calypso opt-out to stop snapshots from being sent, even if WC is opted in to tracking.

**Comment by rrennick** [comment]
> They want the Calypso opt-out to stop snapshots from being sent, even if WC is opted in to tracking.

I would do that here instead of in WC.

**Comment by rrennick** [comment]
@timmyc I couldn't find the setting for https://wordpress.com/me/privacy in my dev install. How do I retrieve that setting?

**Comment by timmyc** [comment]
@rrennick not sure I follow - you want to get the value of the WPCOM privacy setting in the context of Woo?

**Comment by rrennick** [comment]
> There's a concern on the hosting (Calypso) side that people will opt out of tracking via Calypso, and not understand that WC has a separate opt-out. They want the Calypso opt-out to stop snapshots from being sent, even if WC is opted in to tracking. https://github.com/Automattic/wc-calypso-bridge/issues/551#issuecomment-645605066

@timmyc Also, is the Calypso opt-out per site or per user?

**Comment by timmyc** [comment]
Wanted to summarize some thoughts around this from conversations with @rrennick and @pmcpinto 

To properly honor the opt-out of usage tracking that is done on a WordPress.com account, and have that "respected" by WooCommerce ( aka, " do the right thing " ) - I'm thinking we need to take the following approach.

Caveat - as Ron points out - the WPCOM setting is a **user setting** whereas the WooCommerce tracking is a **site setting**. Still it seems that if a WordPress.com/Jetpack user opts out of tracking on Calypso, we should respect that setting on any Jetpack-connected Woo site they are an admin on.

That being said - I'm feeling we should:

- Hook into the REST API process on WordPress.com that opts users out of usage tracking.
- Then cycle through all of that user's Jetpack-connected sites to see if any have Woo Installed.
- If Woo is installed, and the user's account there is an admin, turn off usage tracking in Woo.
- If the site happens to be an Atomic hosted site ( business or ecommerce plan ) toggle a new site option showing that an admin user has opted out of usage tracking, and this would side-step our forced opt-in of tracking that is here in wc-calypso-bridge.

On the flip side, if a user then opts back into usage tracking - I propose we don't do anything to back out of the changes listed above. Again it just feels like the right thing to do.

If that sounds good to everyone, I feel the next steps would be to run it past legal for confirmation, and then schedule the work in a future sprint. The work will need to take place in WordPress.com and here in wc-calypso-bridge.

**Comment by pmcpinto** [comment]
> On the flip side, if a user then opts back into usage tracking - I propose we don't do anything to back out of the changes listed above. Again it just feels like the right thing to do.

@timmyc just to clarify - so if a user opts-in again we don't track him, correct?

**Comment by timmyc** [comment]
> @timmyc just to clarify - so if a user opts-in again we don't track him, correct?

I feel like that might be a bit of an edge case, like I just don't see many users having a change of heart around usage tracking 🤣 but I suppose we could also re-opt-in the impacted sites if a user re-enables tracking in calypso.

**Comment by timmyc** [comment]
@pmcpinto I kind of feel like we should probably loop Jetpack in on these effort, and see if they have a similar mechanism for turning off usage tracking in JP based upon Calypso. Perhaps they already have a similar solution.

**Comment by pmcpinto** [comment]
@timmyc 

> I feel like that might be a bit of an edge case, like I just don't see many users having a change of heart around usage tracking 🤣 but I suppose we could also re-opt-in the impacted sites if a user re-enables tracking in calypso.

Agreed. Probably the number of users changing their minds is minimal.

> I kind of feel like we should probably loop Jetpack in on these effort, and see if they have a similar mechanism for turning off usage tracking in JP based upon Calypso. Perhaps they already have a similar solution.


Good idea. who should we talk to on the JP side?

**Comment by timmyc** [comment]
> Good idea. who should we talk to on the JP side?

Perhaps @ebinnion would know.

**Comment by ebinnion** [comment]
I'm not aware of anything, so I'll ask @dereksmart

For convenience, the question is whether we turn off usage tracking in Jetpack based on a WordPress.com users preferences?

**Comment by timmyc** [comment]
Hey @ebinnion - excellent!

> For convenience, the question is whether we turn off usage tracking in Jetpack based on a WordPress.com users preferences?

Correct our plan here is to respect if users have opted out of usage tracking on WordPress.com, and to not record tracks at all in Woo if so. Currently in this scenario, tracks are still collected, but are filtered off on the WPCOM side of things if the user has opted out.
