### ISSUE TITLE
Add contextual information about store management on My Home

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#555]
**User story:**
As an existing eCommerce user
I want to have more information about my store when I enter My Home
So I can have a sense if there's something that needs my immediate attention

**Description:** currently My Home doesn't provide any information about store management, which makes it difficult for a user to have a clear picture of what's happening with their store without going to Store. The experience is completely focused on site management, while the most pressing tasks probably fall under store management. We should progressively try to change that by providing more contextual information about the current state of their store.

![screenshot-2020-06-09-at-16.50.35.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/033d43b8-c076-4b13-a0eb-5d917002ddc0)

**Acceptance Criteria:**
- [ ] introduce a banner focused on the store setup with the [gauge component](https://wpcalypso.wordpress.com/devdocs/design/gauge) to display the current progress
- [ ] introduce a weekly orders data point in the Weekly stats widget
- [ ] add a "View store stats" link at the bottom of the Weekly stats widget that redirects the user to the WC Analytics page

**Event tracking:**
TBD

**Additional links:**
pbIJXs-cU-p2

**Comment by xristos3490** [comment]
Closing this as obsolete.
