### ISSUE TITLE
Installing WooCommerce Payments by default on US stores

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#557]
Now that we already have the WCPay connection in place on Calypso bridge, it would be good to update the eCommerce product bundle for US stores with WCPay:

 - Having the extension pre-installed can influence their decision of using it instead of opting for other extensions. The Pay menu item will probably catch their attention if they end up skipping the task list.
- This can be a good test before we decide to update the bundle with more extensions, such as AW.

**Comment by pmcpinto** [comment]
cc @timmyc for estimation. Tks!

**Comment by timmyc** [comment]
Adding `woocommerce-payments` as a pre-installed extension for **new** ecom plan sites:

estimate: 2 - should be simple, but since this code lives in wpcom, i imagine it will take more time on the testing side of things.

**Comment by timmyc** [comment]
Diff created on wpcom: https://code.a8c.com/D47209

I left a few notes on that revision, but also summarizing some items that need to be addressed prior to this shipping:

- WCPay is currently redirecting users to their setup flow after install. This would result in new ecomm plan sites being redirected when clicking "Setup Store" after the checkout flow on WordPress.com. As such, we need to wait until [this issue](https://github.com/Automattic/woocommerce-payments/issues/808) has been resolved + shipped to wp.org.
- The way the installation of extensions works on the Atomic provision flow, is that all extensions are installed regardless of store location. So there is no prior setup for installing a certain payment gateway only if a store's country is supported. I'm note entirely certain of the background on this, but that is how things work today. So we will likely need to update some of the code in WooCommerce Admin 1.4 to only show the WCPay item in the task list if WCPay is installed *and* the country is supported. ( original PR that added in that logic: https://github.com/woocommerce/woocommerce-admin/pull/4793/ )

**Comment by pmcpinto** [comment]
@timmyc do you have an estimate of when this will be shipped? Thanks!

**Comment by timmyc** [comment]
@pmcpinto we can ship it at anytime - the only thing that is causing me to pause is the WCPay redirect bug still appears to be present: https://github.com/Automattic/woocommerce-payments/issues/834

This could create some odd flows during onboarding, but really just say when you would like it to ship.

**Comment by thenbrent** [comment]
> WCPay redirect bug still appears to be present

In case it's a blocker, I've confirmed that #834 is only affecting WC 4.5 beta-1 and not WC 4.4.x.

**Comment by pmcpinto** [comment]
> In case it's a blocker, I've confirmed that Automattic/woocommerce-payments#834 is only affecting WC 4.5 beta-1 and not WC 4.4.x.

@thenbrent do you think that this issue will be solved before 4.5? If yes, then I'd move forward and ship this.

**Comment by pmcpinto** [comment]
@timmyc I think that we're good to go, considering that the issue affecting 4.5 beta was already [fixed](https://github.com/Automattic/woocommerce-payments/issues/834#issuecomment-681943018).

**Comment by timmyc** [comment]
Okay, I'll schedule up a release for next week with this change included.

**Comment by timmyc** [comment]
Deployed in r213287-wpcom
