### ISSUE TITLE
Fix "Store" redirect to Orders

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#558]
The "Store" menu item on Calypso is redirecting to the Orders page. It should redirect to the dashboard or home screen (once it's implemented)

https://www.loom.com/share/6fb4065a7cf64362a7357def298483cd

**Comment by timmyc** [comment]
Estimate: 1 - this work will happen in the wp-calypso repository. [Prior art here](https://github.com/Automattic/wp-calypso/pull/42297)

**Comment by octaedro** [comment]
Hi @pmcpinto,
I tried [to reproduce](https://d.pr/i/Rf84Ay) this bug but I couldn't. Is it still happening on your end?

**Comment by pmcpinto** [comment]
It seems that I lost the ownership of the site where this was happening - it's no longer on the eCommerce plan. I tested in a couple of different test stores and it's working fine (I'm redirected to the home screen). So I guess that we can close this issue

**Comment by octaedro** [comment]
Thanks @pmcpinto, I'm going to close this issue now.
