### ISSUE TITLE
Inbox notification: Quick Start session

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#559]
Users that went through a quick-start session are less likely to churn (p58i-976-p2). We're going to trigger an inbox notification exclusive to eCommerce plan users highlighting the access to two quick-start sessions, as it can help them set up their store. 

**Title:** Need help setting up your Store?
**Content:**  Schedule a free 30-min [quick start session](https://wordpress.com/support/concierge-support/) and get help from our specialists. We’re happy to walk through setup steps, show you around the WordPress.com dashboard, troubleshoot any issues you may have, and help you the find the features you need to accomplish your goals for your site. 
**Segmentation:** New eCommerce plan users
**Timing:** Right after the store creation
**Cadence:** Once
**CTA leads to:** https://wordpress.com/me/concierge
**CTA label:** Schedule free session

**Comment by timmyc** [comment]
So the only difficult item I see here is:

> Timing: One day after the plan purchase

If we can instead just base it off the age of the store, like we have in other notes, then this would be pretty straightforward. To get at the data on the date a plan was purchased, we will have to call out to a WPCOM REST API endpoint. I think this is technically feasible to do ( via Jetpack ), but definitely is more complex.

I'd estimate this at a 1 for using the existing store age attribute used in other notes. Otherwise I'll just take a shot and say a 3 for basing it off the plan data.

**Comment by pmcpinto** [comment]
> If we can instead just base it off the age of the store, like we have in other notes, then this would be pretty straightforward. 

Store age is more than enough, I'll update the description.

**Comment by pmcpinto** [comment]
Actually this can be a strong selling point, so let's trigger it right on store creation. We can then adjust the timing depending on the results.

**Comment by becdetat** [comment]
The remote inbox notifications system won't currently support this note's requirements:

1. trigger on store creation
2. the fact that the store is on an ecommerce plan

Both requirements will need to be added to the engine before note can be added to woocommerce.com.

**Comment by pmcpinto** [comment]
@becdetat thanks for your feedback.

> trigger on store creation
> the fact that the store is on an ecommerce plan

 Is this something that can be easily added to the remote system?

**Comment by becdetat** [comment]
@pmcpinto trigger on store creation I have a PR up for now.

Re the ecommerce plan rule, I'm just going to have to figure out where to determine that then add a new rule for it, so it shouldn't be too tricky. I'm working on it now so I should have it figured out by today.

**Comment by pmcpinto** [comment]
@becdetat sorry but we need to pause the implementation of this notification, as the Dotcom team decided to deprecate the quick start sessions 😞 pbBQWj-el-p2

We can reuse the work that was done so far once they replace the QS sessions with other education material (mid-August). I'll keep an eye on this project

**Comment by becdetat** [comment]
@pmcpinto that's ok! The work that's been merged so far won't affect anything, Actually adding the notification is sitting in the woocommerce.com repo and can just wait there until we're ready for it.

**Comment by pmcpinto** [comment]
Hey @becdetat it seems that on the Dotcom side they changed their mind and they're keeping the free quick-start sessions for eComm users 🥳  pbBQWj-eI-p2#comment-787

We can also use this one to test the remote system in the eComm plan. Thanks!

**Comment by becdetat** [comment]
Thanks @pmcpinto, it's in review.
