### ISSUE TITLE
Push users to finish store setup through an email notification

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#562]
**User story:**
As a new merchant
I want to receive guidance through different channels about setting up my store
So I can stay on top about the next steps to build a successful business 

**Description:** one of the best ways to bring users back into the flow is through external triggers and an email notification seems to be a natural fit to reach this goal. Considering that we can use the [Guides system](https://fieldguide.automattic.com/guides/), it would be good to explore the impact that email notification can have on guiding the user through the store setup journey. We can start with a simple notification and measure impact, before diving into something more complex that includes more notifications or sophisticated segmentations.

**Acceptance Criteria:**
- [ ] If a new user completed less than 3 setup tasks during the first 3 days, trigger an email notification explaining why it's important to complete the setup as soon as possible. (Content TBD)

**Event tracking:**
TBD

**Additional links:**
[Slack discussion about this topic](https://a8c.slack.com/archives/C9K5T0XSP/p1585755161093900)

**Comment by pmcpinto** [comment]
Sorry I forgot to add this to the Cycle scope. But depending on the effort, this is something that we should test as if it has a good impact we can double down on this type of notification in the upcoming months.

So I'd like to have a sense of the amount of effort required to implement a simple Guide notification and if it will be possible to use task completion as a trigger or if we should think about a simpler trigger for this experiment.

cc @timmyc and @mattsherman as you already have experience with Guides :)

Thanks

**Comment by mattsherman** [comment]
@pmcpinto @timmyc Sorry for the delayed response... this got buried in my inbox. :-(

Assuming that syncing the setup task completion syncing to Jetpack is relatively easy (estimate: 1, based on what Timmy pointed to in the Slack conversation), I'd estimate 5 for the complete story.

The actual technical tasks shouldn't be difficult, but there are a few different codebases that will be touched, and some back-and-forth probably between dev and designer/wordsmith for the email template.

**Comment by timmyc** [comment]
> Assuming that syncing the setup task completion syncing to Jetpack is relatively easy

That might be a really good first delivery item for this issue - adding in whatever options we need for the guides to the options sync in Jetpack - https://github.com/Automattic/jetpack/blob/01b62d9b421c3fa7ae97c00f434a4c3343d2d4af/packages/sync/src/modules/class-woocommerce.php#L369

**Comment by pmcpinto** [comment]
p7H4VZ-2BH-p2 this contains useful insights in terms of using Guides

**Comment by pmcpinto** [comment]
pbtFPC-ML-p2 info about JP JITM

**Comment by xristos3490** [comment]
Closing this as obsolete.
