### ISSUE TITLE
eCommerce: Included plugins are not symlinked if one already exists on the site

### ISSUE THREAD

**Issue by davemart-in** [Automattic/wc-calypso-bridge#578]
This issue was originally submitted by @aisajib on an internal repo.

The user we had on chat (22519941-hc) was unable to find "WooCommerce Product Add Ons" on their site. It was included in their eCommerce plan so they wanted it on their site. I noticed it was missing. However, they later mentioned that they had a previous version of Product Add Ons installed on their site when they upgraded to eCommerce. 

That means when they upgraded, that particular plugin was skipped as it was already installed. As a result, it wasn't symlinked so they were able to delete the plugin later with no way of getting it back. I had to manually install the plugin for them, but even then, because it was not symlinked, they still had the option to remove it. 

### Expected behavior
Like all the other plugins included with the eCommerce plan, the Product Add On will not be removable.

### Actual behavior
The user was able to remove that Product Add On plugin as they already had it installed before upgrading to eCommerce.

### To Reproduce
1. Install and activate one of the included WooCommerce extensions on an atomic site with the Business plan (for example, I installed and activated Product Add On).
2. Upgrade to WordPress.com eCommerce.
3. Go to wp-admin -> Plugins. 
4. See you are able to delete the WooCommerce Product Add On plugin.

This is probably working as expected, but there may be an opportunity to improve it for the user. I'm adding it here in case we can improve something for edge cases like this.

**Comment by timmyc** [comment]
This issue will likely need to be fixed on the WPCOM side of the ecommerce plan, specifically in the code that creates the new AT site. From my experience with that code, it creates an array of plugins to install, which is then passed along to the Atomic REST API, which then configures the site.

So thinking it would be a fix/enhancement in the atomic REST API side of things that actually performs the plugin installs, and it should check if an extension is already present, then do the delete of the existing one, and symlink with the licensed version included in the plan.

There could be more that needs to be done in this scenario from the woocommerce.com side of things too - but I'm not super savvy in that space.
