### ISSUE TITLE
Inbox Notification: Product Add-ons

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#580]
**Title:** For a shopping experience as unique as your customers
**Content:**  Product Add-Ons allow your customers to personalize products while they’re shopping on your online store. No more follow-up email requests—customers get what they want, before they’re done checking out. Learn more about this extension that comes included in your plan.
**Segmentation:** New eCommerce plan users
**Timing:** On store creation or plan purchase
**Cadence:** Once
**CTA leads to:** https://docs.woocommerce.com/document/product-add-ons/?utm_source=inbox
**CTA label:** Learn more

**Comment by pmcpinto** [comment]
@becdetat let's use this notification to test the remote system in the eCommerce plan. Thanks

**Comment by psealock** [comment]
Estimate: 1. Adding inbox notifications is pretty straightforward at this point. The only thing potentially making it 2 is `Segmentation: New eCommerce plan users` unless there already is logic relating to differentiating users like this already in place.

**Comment by psealock** [comment]
Oh, nevermind. its already fixed!
