### ISSUE TITLE
Enable HotJar in eComm plan pages

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#581]
Note: @pmcpinto needs to decide whether we use HotJat or Fullstory to implement this - we haven't assessed the product features, just the security and implementation aspect, which is very similar in either case.

We should enable HotJar/Fullstory in some of the high-traffic Woo screens, in order to have additional insights about the user behavior.

According to the HotJar docs, pasting the Tracking Code into the <head> section will be enough to make it work. But here it goes the list of pages in case it's necessary to add the code into the <head> section of each page

**Onboarding:**
Store details:/wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=store-details
Industry: /wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=industry
Product Types: /wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=product-types
Business Details: /wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=business-details
Add Products task: /wp-admin/admin.php?page=wc-admin&task=products
Set up Payments task: /wp-admin/admin.php?page=wc-admin&task=payments
Set up Taxes task: /wp-admin/admin.php?page=wc-admin&task=tax
Set up Shipping task: /wp-admin/admin.php?page=wc-admin&task=shipping
Personalize Store task: /wp-admin/admin.php?page=wc-admin&task=appearance

**Home Screen**: /wp-admin/admin.php?page=wc-admin

**Settings**: /wp-admin/admin.php?page=wc-settings

**Products:** 
List: wp-admin/edit.php?post_type=product
Add Product: /wp-admin/post-new.php?post_type=product

**Orders:**
List: wp-admin/edit.php?post_type=shop_order
Edit Order: /wp-admin/post.php?post=XXXXX&action=edit

**Analytics Dashboard:** /wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview

Instructions to install HotJar: https://help.hotjar.com/hc/en-us/articles/115009336727-How-to-Install-your-Hotjar-Tracking-Code

The access to the HotJar account is available in the Secret Store. 

## Security and privacy considerations

See p90Yrv-2Tv-p2 for the full discussion.

- Only include the tracking code on pages that are relevant (above) and explicitly ensure that none of that pages include PII
- If a page that the tracking code is being added to does in fact contain and expose PII, elevate it as an issue and with @pmcpinto 
    - if it is decided that the page still requires tracking, ensure that any PII is tagged as sensitive and isn't recorded, and _ensure that the tagging is successful_
- Find a way to unload/disable FS script on React app to ensure we have guaranteed control when a user is exiting designated recorded pages
- Global features that may include sensitive information (such as a login form popup from a global menu) should be disabled on recorded pages
- Changes over features inside a recorded page should be given more scrutiny to ensure no PII is unintentionally added in
- Set a [data retention window](https://help.fullstory.com/hc/en-us/articles/360020827493-Can-I-delete-sessions-) to ensure no data gets kept indefinitely
- manually delete all sessions data by contacting FS support after we’ve finished analyzing the data so it’s not kept longer than necessary (this will need to be done when we decide that the data collected and analysed is sufficient).
- Add a "dead man's switch" option which immediately disables the tracking code with a single code change and deploy

**Comment by pmcpinto** [comment]
@timmyc here's the issue about adding Hotjar

**Comment by timmyc** [comment]
@pmcpinto looking at the implementation in Calypso for hotjar, and I noticed there are a few checks that happen before hotjar is activated: https://github.com/Automattic/wp-calypso/blob/4537033c6794449ce0a10b69d72daf5fa658d553/client/lib/analytics/hotjar.js#L20-L25

The ones that stuck out to me are what appears to be something around GDPR, a check to see if there is any PII on the page potentially, and also one for seeing if tracks are enabled.

I'm guessing we want to have similar logic for our usage here - but wanted to confirm with you.

Based on the PII one though, we might need to consider **not** having the script running on pages like Orders where there is most definitely PII... but on that topic, even the onboarding steps will have some PII so curious for your thoughts there - or do you think we need to double check with legal?

**Comment by pmcpinto** [comment]
Nice catch. HotJar provides tools to suppress personal data, see the following docs:
- [Processing Personal Data in Hotjar](https://help.hotjar.com/hc/en-us/articles/360039027113-Processing-Personal-Data-in-Hotjar)
- [How to Suppress Text and Images from Collected Data](https://help.hotjar.com/hc/en-us/articles/115012439167)

If we use those tools we'll probably don't need to exclude any page that involves personal data (almost all include some kind of PII). @hollyannehogan what do you think?

**Comment by pmcpinto** [comment]
@timmyc let's start with the pages that don't contain sensitive data and that align with our current goals. Sounds good?

**Onboarding:**
Store details:/wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=store-details
Industry: /wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=industry
Product Types: /wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=product-types
Business Details: /wp-admin/admin.php?page=wc-admin&path=%2Fprofiler&step=business-details
Add Products task: /wp-admin/admin.php?page=wc-admin&task=products
Set up Payments task: /wp-admin/admin.php?page=wc-admin&task=payments
Set up Taxes task: /wp-admin/admin.php?page=wc-admin&task=tax
Set up Shipping task: /wp-admin/admin.php?page=wc-admin&task=shipping
Personalize Store task: /wp-admin/admin.php?page=wc-admin&task=appearance

**Home Screen:** /wp-admin/admin.php?page=wc-admin

**Products:**
Add Product: /wp-admin/post-new.php?post_type=product

**Comment by timmyc** [comment]
@pmcpinto seems like the onboarding pages might be safe to add it in, as for homescreen/products - my main concern at this point is *all* Woo core pages like these have the Orders Activity panel on them ( on the ecomm plan it is hidden via css ), which introduces the possibility of leaking PII around customer's customers.

**Comment by pmcpinto** [comment]
I think that we can suppress specific elements, such as the activity panels: https://help.hotjar.com/hc/en-us/articles/115012439167-How-to-Suppress-Text-and-Images-from-Collected-Data#element

**Comment by becdetat** [comment]
@pmcpinto Ok, I'll include it in the planning. I assume that the above conversation between you and Timmy is still valid?

**Comment by pmcpinto** [comment]
Yes. It's better to start with the areas I listed [here](https://github.com/Automattic/wc-calypso-bridge/issues/581#issuecomment-687267915) cc @jarekmorawski in case you have any suggestion or question

**Comment by mattsherman** [comment]
> Yes. It's better to start with the areas I listed [here](https://github.com/Automattic/wc-calypso-bridge/issues/581#issuecomment-687267915) cc @jarekmorawski in case you have any suggestion or question

If that is the case, the issue description should be updated... any reason why it wasn't?

**Comment by pmcpinto** [comment]
Sorry for the late reply. I still need to update the description. I chatted with Legal and they want to be included in any discussion regarding 3rd party tracking. I'll publish a post this week to make sure that we can move forward with this.

**Comment by pmcpinto** [comment]
Hey Mike, we explored that option, but the Sec team expressed concerns about using HotJar or FullStory, so we didn't proceed with the implementation.
