### ISSUE TITLE
eCommerce Plan: Unable to complete Customizer Publish on new site.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/wc-calypso-bridge#585]
#### Steps to reproduce
1. Purchase and create new eCommerce Plan site
2. Open the customizer via the customization checklist item
3. Click Publish

#### What I expected

The Customizer to complete the publish action and take me back to the checklist.

#### What happened instead

Errors about invalid values that I wasn't able to resolve.

![image](https://user-images.githubusercontent.com/545779/70736645-6289d280-1cd6-11ea-9410-60c79cb22a32.png)

**Comment by xristos3490** [comment]
Closing this as obsolete.
