### ISSUE TITLE
Ecommerce plan: Purchase "Thank you" screen design

### ISSUE THREAD

**Issue by alaczek** [Automattic/wc-calypso-bridge#588]
The design of Ecommerce plan post-purchase "Thank you" page is is inconsistent with any other pattern or set of design elements inside of WordPress.com.

![image](https://user-images.githubusercontent.com/4550351/57673931-1653b280-7661-11e9-831b-74a9a55a11b5.png)

@ianstewart made a video of the whole flow here: paObgF-7Y-p2

(The notices above the card are covered in  Automattic/wp-calypso#33009)

#### Steps to reproduce
1. Sign up as a new user and select Ecommerce plan during checkout.
2. Proceed to checkout.
3. Note the "Thank you" page after completing the purchase.

#### What I expected
For the "Thank you" page to be more aligned with our existing design patterns. Not pointing to any specific thing to fix, as the whole screen needs re-thinking. As for the content of the page, displaying the amount paid for the plan feels off.

**Comment by xristos3490** [comment]
Closing this as obsolete.
