### ISSUE TITLE
Ecommerce plan: My plan page does not mention store creation

### ISSUE THREAD

**Issue by alaczek** [Automattic/wc-calypso-bridge#589]
When signing up and purchasing Ecommerce plan, clicking the "Confirm Now" button in the email takes customer to My plan page in Calypso (https://wordpress.com/plans/my-plan/{site}/?verified=1):

![image](https://user-images.githubusercontent.com/4550351/57671919-1d76c280-7659-11e9-8125-c2536363c69a.png)

The features list does not mention ecommerce/starting a store, which presumably is the main reason someone would purchase Ecommerce plan. Ideally the whole flow would get an overhaul and we'd guide customers through store setup as part of onboarding, but even adding a card with a nudge towards setting up a store to the top of features list would be an improvement.

The whole video of signup process can be found in this post (under eCommerce plan customers): paObgF-7Y-p2

**Comment by timmyc** [comment]
We have work in progress on this topic, and going to close in favor of #555
