### ISSUE TITLE
Add WooCommerce.com License Removal during Atomic Cleanup Process

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#591]
Full details and history can be viewed here: p9o2xV-Ya-p2

But specifically in [this comment for the proposed fix](https://atomicp2.wordpress.com/2020/07/24/ecommerce-licenses-not-removed-on-downgrade/#comment-3409)

TL;DR;

Currently when an ecommerce plan atomic site goes through the revert process back to a "simple" WordPress.com site, the logic that cancels the licenses provisioned from WooCommerce.com is not currently being called. The logic currently only is called when a plan is _deactivated_. The fix should be adding in the requisite call to the `PlanManager` class on revert.

This fix should entirely take place in the WordPress.com repository.

**Comment by timmyc** [comment]
Estimating at 3 since this is still a pretty new area of the code for everyone on the team.

**Comment by Nic-Sevic** [comment]
To add to the above, I was testing this to try and clarify our docs and found that if the site is reverted and then the plan deactivated this logic is also not called. It's only if the site remains AT and the plan is cancelled that the woo order is cancelled and the subs removed
