### ISSUE TITLE
Help panel unavailable to eCommerce customers using Calypso

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#592]
The Calypso header hides the wcadmin activity panels, making it impossible to access the Help panel through Calypso.

This is particularly important as 70-80% of new eCommerce plan customers are viewing and completing the setup tasks in Calypso.

**Comment by pmcpinto** [comment]
@timmyc @jameskoster I know that this problem between the activity panels and the Calypso header was already discussed a couple of times in the past, but I'm wondering if we could find a workaround just for the Help panel. It doesn't need to the perfect, but at least it could give us a sense of how many eComm users are using the panel before implementing something more consistent.

**Comment by jameskoster** [comment]
Could we plug the button that opens the help panel in to the Calypsoify top bar? Or would that be seriously cross the streams?

![img](https://cldup.com/LHZ2659hDH-3000x3000.png)

**Comment by pmcpinto** [comment]
> Could we plug the button that opens the help panel in to the Calypsoify top bar? Or would that be seriously cross the streams?

That would be perfect.

**Comment by timmyc** [comment]
I think that solution would be a bit problematic from the code side of things... unless we looked into styling the woo nav bar to look like the one in calypsoify.

**Comment by jameskoster** [comment]
Yeah, it's hard to see a solution here that doesn't go down the "remove calypsoify" rabbit hole.

**Comment by timmyc** [comment]
> that doesn't go down the "remove calypsoify" rabbit hole

My thoughts exactly. Kind of thinking any efforts made here will have a very short shelf life in production. I'd be more keen to just live with this as-is until we can ship nav.

**Comment by pmcpinto** [comment]
What if we remove the Calypso top bar? The benefits of having the activity panel clearly outweighs keeping that top bar

**Comment by timmyc** [comment]
The top bar is kind of a key part of the calypsoify design -  and on various screens, we use the bar to house the action buttons like "Add Product", "Add Order" or taxonomy action buttons too. So we can't simply wholesale remove the nav bar without finding a new home for those actions.

**Comment by pmcpinto** [comment]
> The top bar is kind of a key part of the calypsoify design - and on various screens, we use the bar to house the action buttons like "Add Product", "Add Order" or taxonomy action buttons too. So we can't simply wholesale remove the nav bar without finding a new home for those actions.

💩 I forgot about those buttons. We could remove them and keep the approach that we have on Core, correct? https://d.pr/i/5RRO4T

What was the reasoning behind having them in the top bar? I think that placing them in the top bar makes sense, but it creates several limitations in terms of using our activity panels. And it seems that this pattern is only used in the store screens. Pages example: https://d.pr/i/p5THkB

**Comment by timmyc** [comment]
Well iirc the reasoning of having those action buttons in the top bar was to make things look more like calypso. But it appears that the pattern in Calypso has since diverged from that as I can't find any pages ( outside of Store on WPCOM ) that follow this action button pattern.

Honestly, it seems like the Nav/Breacrumb bar across the top isn't really used anywhere in calypso anymore ( besides Store ).

So based upon that, we have some options here. I'll preface these by saying I'd prefer not to invest too much time into Calypsoify since it is very much going to be code with a very short shelf life ( hopefully ).

1. Remove the top nav bar on the setup task list pages, allow the wc-admin navbar to then be displayed with the help menu.
2. Remove the top nav bar on *all* pages, and display the wc-admin nav bar instead. Bigger effort to rip out all the moving of action buttons, but it gets us closer to feature parity with woo core. And it also will match the other usage of Calypsoify on the plugins screen:

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/22080/91237298-1610e680-e6ef-11ea-9e1a-c90b9e39ebb3.png">

3. Remove calypsoify entirely and call it good :shipit:

**Comment by jameskoster** [comment]
In respect to the original issue, options one and two seem fine. It's worth noting that we'll likely want to display these contextual help links on other screens in the future. So I suppose it comes down to a question of whether we want to prepare for that now (option two) or just handle it later (option one).

**Comment by pmcpinto** [comment]
As we chatted yesterday, option 2 seems to be the best path and it's aligned with the implementation of the new nav.

**Comment by octaedro** [comment]
Hi @pmcpinto and @jameskoster,
I'm working on this issue and I wanted to confirm a design modification.
Currently we have the `Add new` button in the Calypso header:
![screenshot-three wordpress test-2020 09 22-14_45_21](https://user-images.githubusercontent.com/1314156/93919013-8d806880-fce3-11ea-9c84-9d7c70f04290.png)

Is it ok if I move it to under the Search input?
![screenshot-three wordpress test-2020 09 22-13_33_42](https://user-images.githubusercontent.com/1314156/93919040-9709d080-fce3-11ea-898f-a2d058d2a13e.png)

I also reduced the space between the Search input and the header. If you think that it should be like it was before, let me know.

**Comment by jameskoster** [comment]
Where does the add button live on Calypsofied versions of the posts / pages lists? I'd look there for inspiration. cc @elizaan36

**Comment by octaedro** [comment]
Thank you @jameskoster.
In Calypso those buttons are aligned to the right. If it's ok I will align ours to the right too.
![screenshot-wordpress com-2020 09 23-10_01_36](https://user-images.githubusercontent.com/1314156/94016197-34b4dc80-fd84-11ea-9391-6d16ece1a8a3.png)

cc @elizaan36

**Comment by elizaan36** [comment]
I know I'm just joining this conversation at the end, but have we considered placing the `Add new` button to the right of the activity panel in the wc-admin navbar? Is that a possibility @octaedro or does it have to be placed outside of the nav?

**Comment by octaedro** [comment]
Hi @elizaan36,
No problem, it would look like this:
![screenshot-three wordpress test-2020 09 25-13_18_07](https://user-images.githubusercontent.com/1314156/94291211-b26a1b00-ff31-11ea-87a2-00db6bbb7fcb.png)

**Comment by elizaan36** [comment]
Nice! Is there any way we could place the `Add new` button to the **right** of the activity panel in the wc-admin navbar?
I'm looking at Jay's previous designs for this component, and there's an example here: https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=3847%3A15111

The primary action is located at the far right. Not sure if that gets in the way of any metrics we're trying to track, but I think having the primary action on the top right is best for usability.

**Comment by octaedro** [comment]
Hi @elizaan36,
> Is there any way we could place the `Add new` button to the **right** of the activity panel in the wc-admin navbar?

Are you referring to the whole actions group or only to the `Add new` button?

Moving the grouped buttons is easy, but sending **only** the `Add new` button is more tricky.
If you don't mind, it would be great if you could share a design to give me a clearer idea about what you think it should look like.

**Comment by elizaan36** [comment]
hey @octaedro, we've just had some progress on [removing Calypsoify](https://github.com/Automattic/dotcom-manage/issues/44) so whatever we do here will be removed eventually to go back to a consistent wp-admin experience.

If it's not too much work, I think your solution will work fine for now! (with the button group on the left.)

**Comment by psealock** [comment]
>Yeah, it's hard to see a solution here that doesn't go down the "remove calypsoify" rabbit hole.

Bingo! Since we're headed down this route, we can close this issue.
