### ISSUE TITLE
Home Screen: default experience for every eComm plan user

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#593]
We should ship the home screen first for every eComm plan user before making the wider release in WooCommerce 4.6. This will allow us to start gathering data about the home screen usage among existing users and anticipate any unforeseen problems before the 4.6 release.

**Comment by pmcpinto** [comment]
@timmyc I think that we should target the 1st or 2nd week of September to do this. Does this date look doable to you?

**Comment by timmyc** [comment]
Yep we can hit that date https://github.com/Automattic/wc-calypso-bridge/pull/594

**Comment by pmcpinto** [comment]
@timmyc  can we ship it this Wednesday or Thursday? Considering that 4.5 includes the home screen welcome modal.
