### ISSUE TITLE
Marketing tab disappeared (again) from the Calypso menu

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#597]
**Describe the bug**
The Marketing menu item disappeared from the Store navigation in Calypso and it's showing up in the Plugins navigation menu

**To Reproduce**

1. Log in with an account with the eCommerce plan active
2. Click on Store
3. See that the Marketing item is not present in the menu
4. Click Tools - Plugins and see the Marketing item in the menu

**Expected behavior**
See the Marketing menu item in the Store menu

**Screenshots**
https://d.pr/i/DuP7sR
https://d.pr/i/AsCr7o

**Related issue**
#577

**Comment by timmyc** [comment]
This has been fixed:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/22080/91747620-5d75f780-eb73-11ea-987b-279335ca8ccd.png">
