### ISSUE TITLE
Home Screen - Store Management: wrong redirect when clicking on "Get Support"

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#602]
The "Get Support" option in the eCommerce plan should redirect the user to https://wordpress.com/help

Currently is redirecting to https://woocommerce.com/my-account/create-a-ticket/

~See video: https://www.loom.com/share/7c76888e8eff4fe1913f8c0d2da74ad8~

_Revised by @timmyc 1/28/21 to update location of bad link_

<img width="530" alt="get-support" src="https://user-images.githubusercontent.com/22080/106208969-123f2f80-6179-11eb-899f-cf74ae628abb.png">

__Steps to recreate bug__
- On an ecommerce plan site
- Visit the Home Screen
- Click the Help Menu in the Activity Bar area
- Click on "Get Support" note you are directed to `https://woocommerce.com/my-account/create-a-ticket/`

__Expected Behavior__
- To be directed to `https://wordpress.com/help`

**Comment by timmyc** [comment]
We have a [js filter](https://github.com/woocommerce/woocommerce-admin/blob/main/client/header/activity-panel/panels/help.js#L332-L337), `woocommerce_admin_setup_task_help_items`, that should allow us to modify this particular help link to the proper location.

Estimate: 1
