### ISSUE TITLE
Set up payments task missing 

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#603]
I created a test store today to check the changes made by Fernando in the Calypso Home and in the meantime, I noticed that the Set up payments task is missing: https://d.pr/i/XYwGGW

**Comment by joshuatf** [comment]
@pmcpinto Was WooCommerce Payments installed?  Looks like that task is hidden if it's already installed.
https://github.com/woocommerce/woocommerce-admin/blob/a4e10235922f41eef12c71069aa2afdfa759fe14/client/task-list/tasks.js#L194

**Comment by pmcpinto** [comment]
> @pmcpinto Was WooCommerce Payments installed? Looks like that task is hidden if it's already installed.

Yep, it was installed by default: https://d.pr/i/rXnENa

Probably there's a conflict because the store location is not set in the US.
