### ISSUE TITLE
Auto-update the WooCommerce database in the eCommerce plan

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#605]
**User story:**
As a merchant
I want to see my database updated automatically
So I can manage my store instead of being interrupted by notifications

**Description:** we prompt the eCommerce plan users to move forward with the DB update. This can increase friction, cognitive load and distract them. We can streamline this process by auto-update the WC database.

Acceptance Criteria:
[ ] - Automatically update the WooCommerce database
[ ] - Display notification when the update is running

**Comment by xristos3490** [comment]
Done in #932
