### ISSUE TITLE
eComm plan - Inbox feature missing in the home screen

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#609]
The inbox panel disappeared from the home screen in the eCommerce plan with the WooCommerce 4.6 update. This is happening in Calypso and WP-Admin:

Calypso: https://d.pr/i/6LuLM7
WP-Admin: https://d.pr/i/3JLF2Z

**Comment by timmyc** [comment]
I can reproduce this _on_ ecomm plan sites only, and have not been able to make it happen locally.

**Comment by pmcpinto** [comment]
@timmyc the inbox is showing up in the eComm test store that I created a couple of mins ago: https://d.pr/i/LnYKAe
There's definitely something weird happening with the inbox panel

**Comment by timmyc** [comment]
@pmcpinto I think this issue on eComm plan sites is related to https://github.com/woocommerce/woocommerce-admin/issues/5385

I'm not sure _why_ yet, but the change that did happen in the inbox panel for this release was the migration to `wp.data`. From what I've seen in my debugging it looks like the request to fetch the notes doesn't seem to work properly, which results in the homescreen thinking there are no valid notes to display, and as such we show things in one column.

Oddly enough, things work fine on "embedded" pages for the inbox, like say visiting the orders page with the gutenberg plugin active - the notes indicator and panel works fine.

Deactivating the Gutenberg plugin on my ecommerce plan site fixes the problem.
