### ISSUE TITLE
Reenable WooCommerce Payments auto-install on US Stores

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#611]
We should reenable the WooCommerce Payments auto-install on US Stores, considering that WooCommerce Core 4.6 included the [fix](https://github.com/woocommerce/woocommerce-admin/pull/5166) to show payments task for non-US stores when wcpay installed

**Comment by pmcpinto** [comment]
cc @timmyc

**Comment by timmyc** [comment]
Deployed in r215452-wpcom
