### ISSUE TITLE
Storefront child themes not loading in Calypso

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/wc-calypso-bridge#617]
The eCommerce plan includes Storefront child themes, but when I tested this I found they can only be activated via the Customizer or WP Admin. If one of the included child themes is activated, it does not load in Calypso.

Screenshot: https://d.pr/i/xRs7jo

I would expect the active theme to appear in Calypso and all the child themes to appear on the Themes page as options.

**Comment by timmyc** [comment]
@jamiepalatnik thanks for logging this issue - definitely looks buggy to me. That screen however is part of calypso so thinking it might be best to open the issue there. I'm not certain which team would be responsible for the theme screen in calypso, but I imagine this same bug would impact any site that is using a child theme, regardless of if Woo is installed or not.

**Comment by jamiepalatnik** [comment]
Thanks for taking a look! I am not able to recreate this with any other child themes, only the child themes included with the  eCommerce plan. I reported this here: https://github.com/Automattic/wp-calypso/issues/47838

**Comment by xristos3490** [comment]
Closing this as obsolete.
