### ISSUE TITLE
[4.8-beta.1] Snackbar Left Margin off

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#619]
I think this has already been mentioned in the context of the new navigation, but currently in the ecommerce plan, the Snack Bar notices are not aligned properly with the left sidebar. I also realize the likliehood of us fixing this with nav on the doorstop is slim, I'm more just logging this as a "known issue" for 4.8, but imagine it is the same way with 4.7 as well:

<img width="1801" alt="snackbar-padding-4 8-beta1" src="https://user-images.githubusercontent.com/22080/99719759-98e0dd80-2a61-11eb-8040-44a82e0bd085.png">

**Comment by xristos3490** [comment]
Closing this as obsolete.
