### ISSUE TITLE
[4.8-beta.1] Extra top padding in OBW

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#620]
Test Setup:
- Atomic Ephmeral
- WC 4.8 Beta 1
- wpcomsh
- Gutenberg
- And manually installed [ecomm plan helper](https://teamisotope.wordpress.com/2020/07/01/getting-by-with-a-little-helper/)

When going through the OBW with the above configuration, there is some extra padding at the top of the screen:

<img width="1801" alt="padding-top-4 8-beta1" src="https://user-images.githubusercontent.com/22080/99720071-055bdc80-2a62-11eb-8860-c3be1da8d6fb.png">

I believe this may have been introduced with #604 but I didn't test further to verify that hunch.

**Comment by xristos3490** [comment]
Closing this as obsolete.
