### ISSUE TITLE
Store profiler: styling fixes are not working properly

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#624]
**Describe the bug**
Some elements of the Store Profiler should be hidden in the eCommerce plan

**To Reproduce**

1. Purchase a new eCommerce plan
2. Go to the store profiler
3. In the product types step see that we're displaying a monthly pricing toggle and a mention about billing
4. In the business details step see that we're showing the extensions after you fill the two initial questions
5. After completing the store profiler see that you're redirected to wp-admin instead of calypso.

**Expected behavior**
The monthly pricing toggle, the mention about billing and the extensions promotions should be hidden. And the user should be redirected to the woo home screen in Calypso (until we implement the new nav and remove calypoify).

**Screenshots**

Product Types: https://d.pr/i/IKsfe6
Business Details: https://d.pr/i/U4DoRo
Landing on wp-admin: https://d.pr/i/6IU48j

**Comment by pmcpinto** [comment]
@timmyc here's the issue

**Comment by xristos3490** [comment]
Closing this as obsolete.
