### ISSUE TITLE
Remove Calypsoify: Ensure Jetpack doesn't add Calypsoify`

### ISSUE THREAD

**Issue by psealock** [Automattic/wc-calypso-bridge#629]
In some poking around I noticed that using the `remove/calypsoify` branch doesn't prevent Calypsofiy from turning on if Jetpack is activated.

This may be a non-issue because the `&calypsoify=1` query parameter may never get added, but I'm creating this issue so we remember to confirm this.

**Comment by joshuatf** [comment]
@psealock After investigating a bit, I think `remove/calypsoify` should prevent the Jetpack version from turning on.  The following line filters the user metadata which is how Jetpack determines whether or not to turn on Calypsoify.

https://github.com/Automattic/wc-calypso-bridge/blob/7e4628cfeb01d2e9d70f534c6f945b1420517852/class-wc-calypso-bridge.php#L146

Are you still able to see calypsoified styles in the rebased `master` branch now?  If so, are there any other steps here we might need to recreate the issue?

**Comment by psealock** [comment]
>Are you still able to see calypsoified styles in the rebased master branch now?

Yeah, if you have Jetpack installed, and add the param `&calypsoify=1` (using `master` of the wc-calypso-bridge), then you get this:

<img width="1148" alt="Screen Shot 2021-01-12 at 1 23 59 PM" src="https://user-images.githubusercontent.com/1922453/104253553-a6eb3180-54d9-11eb-8655-700a58dc53d8.png">

Can we be sure that `decalypsoify_ecommerce_plan` prevents Jetpack from adding the parameter?

**Comment by psealock** [comment]
This Calypso PR should ensure we don't run into an errant Calypsoification https://github.com/Automattic/wp-calypso/pull/48897
