### ISSUE TITLE
Navigation [WC 5.0] Force Navigation on for Business Plan users

### ISSUE THREAD

**Issue by psealock** [Automattic/wc-calypso-bridge#631]
Similar to how its been done for eCommerce plan, we need to turn on Navigation for Business Plan users.

## Deliverables

* Turn of Navigation for  Business Plan users
* Enable the feature toggle in Settings. Avoid duplication if it already exists

**Comment by pmcpinto** [comment]
As it was discussed 1-2 weeks ago, let's see how it goes the nav unification on the Dotcom side before making this change

**Comment by timmyc** [comment]
Since assessing how Nav Unification roll out goes is going to probably take a few weeks, the soonest we will get to this issue will likely be in the next sprint cycle. As such, removing from this cycle.

**Comment by xristos3490** [comment]
Closing this as obsolete.
