### ISSUE TITLE
Redirect users back to Calypso Home when clicking on the WordPress Dashboard menu item

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#633]
Currently we're redirecting eCommerce plan users to the wp-admin dashboard when they click on the WordPress Dashboard menu item. However, it will be better to redirect users back to the Calypso Home, as we don't know if they manage the other parts of their website on Calypso or wp-admin. And they can always access wp-admin through the nav option in the Calypso menu.

**Comment by timmyc** [comment]
Adding this to cycle 9. Looks like the work is done, we just need to get a new version of the bridge out including this fix.
