### ISSUE TITLE
Various WC_Install::install() Methods Not Running on eCom Sites

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#637]
This feedback came in via the WPCOM Happiness Townhall yesterday where @pmcpinto gave a presentation about the eCommerce Plan.

Post about this topic on the Atomic P2: p9o2xV-1eZ-p2

As the title states, the bug is that when a new ecommerce plan site is launched, the default WooCommerce pages ( Shop, Cart, Checkout Etc ) are not created, which is problematic for new Woo users.

I spent a little time digging in to where this logic is triggered, and the logic is housed in `WC_Install::install()` method which in-turn calls a method called [`maybe_create_pages`](https://github.com/woocommerce/woocommerce/blob/56e67b1ef8f4b521c349780e2dd38f84cf513358/includes/class-wc-install.php#L311). That method only checks to see if the site option for `woocommerce_db_version` is present, if it is, the install of Woo is considered an upgrade, and no default pages are set.

On a brand-new ecomm site created today, I verified that this behavior still exists, no default pages created, and after the site is provisioned, the db version looks correct:

![image](https://user-images.githubusercontent.com/22080/106062926-4dbff800-60ac-11eb-8fd4-351937e0cd8a.png)

I also confirmed that the page creation behavior is working as anticipated in a 4.9 install on a Jurassic Ninja site:

![image](https://user-images.githubusercontent.com/22080/106063178-a394a000-60ac-11eb-9969-62bd8bf02f2a.png)

## Missing Cron Jobs Too

I also wanted to see if any other logic in the `install()` method was not behaving as expected, so I also looked into [`WC_Install::create_cron_jobs()`](https://github.com/woocommerce/woocommerce/blob/56e67b1ef8f4b521c349780e2dd38f84cf513358/includes/class-wc-install.php#L512), and it too appears to not be running on install on the eCommerce Plan sites. So I'm a bit perplexed as parts of the install logic ( database creation and updating db version option ) are running, but so far at least 2 others are not.

__Cron jobs prefixed with `woocommerce_` on new JN Install__
![image](https://user-images.githubusercontent.com/22080/106063983-f0c54180-60ad-11eb-8e2d-c69bbc811669.png)

__Cron jobs prefixed with `woocommerce_` on eComm new Install__
![image](https://user-images.githubusercontent.com/22080/106064052-0e92a680-60ae-11eb-91cf-5a1f026a1519.png)

As such it seems like something with how WooCommerce is installed on ecommerce plan sites, which is done so via symlink, is resulting in the normal install flow for a fresh copy of the plugin to not proceed as anticipated.

**Comment by timmyc** [comment]
So a bit unsure on how to estimate this one - we could add some logic to the bridge to sniff out if the default pages are not setup, and trigger that, perhaps during the daily wc admin job. But I feel we need to get to the root cause of this bug, as it will continue to impact us in other ways ( see the cron issue too ). As such this will likely require working with the Atomic team to do some more discovery.

I'm going to place this one at 3.

**Comment by philnick206** [comment]
Report here: #3714489-zen

**Comment by philnick206** [comment]
Another: #3751727-zen

**Comment by timmyc** [comment]
> couldn't we simply check if the pages exist and create them if not?

I think that would be a sound approach @moon0326 - we could possibly hook into the [`woocommerce_admin_newly_installed`](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Install.php#L149) action and do a check to see if the default pages exist, and if not, call `maybe_create_pages` again.

**Comment by moon0326** [comment]
@timmyc Sounds good! I will make a PR 👍

**Comment by moon0326** [comment]
Closing it as this issue has been resolved on prod.
