### ISSUE TITLE
The Bridge Housekeeping

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#647]
Gazing into the crystal ball of 2021, I for-see more development happening in _The Bridge_ and as such, I'm thinking we need to invest some time into cleaning up some things in the plugin here, and getting workflow tooling in place so development in this project _feels_ as smooth and normal as working in other repositories that Start Manage teams are active in.

Feels like an epic!

**Comment by timmyc** [comment]
Due to the shift in focus, I'm going to remove this from the current dev cycle since we will be likely focusing efforts in other repositories so these tasks aren't as critical in the bridge plugin.

**Comment by xristos3490** [comment]
Closing this in favor of #932
