### ISSUE TITLE
Remove Legacy Store on WordPress.com Code

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#648]
Store on WordPress.com will be officially sunset by the time we start the next sprint cycle in March 2021. As such, it is time to remove any code that still exists in this plugin that is specific to Store on WordPress.com:

https://github.com/Automattic/wc-calypso-bridge/tree/master/store-on-wpcom

**Comment by warrendholmes** [comment]
Closing this since we have https://github.com/Automattic/wc-calypso-bridge/issues/885
