### ISSUE TITLE
Hide free extensions promotion

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#652]
**Describe the bug**
Some of the free extensions that we promote (Facebook and Mailchimp) are installed by default on the eComm plan. We should hide the extensions promotions in the alternative flows that we created: [#4579](https://github.com/woocommerce/woocommerce-admin/issues/4579) and [#5287](https://github.com/woocommerce/woocommerce-admin/issues/5287). We should hide the free extensions promotion in these flows 

**To Reproduce**

1. Create a new eComm plan
2. Select US as the country in the store detail step
3. In the Industry step select one of the following industries: Other, Food & Drinks, Fashion, Apparel, Accessories or Health & Beauty
4. See the free extensions promotion in the Business details step

**Comment by timmyc** [comment]
@pmcpinto given the extensions step is such a moving target, would it make more sense to remove it entirely from the eCommerce plan? We can not currently do that, but after https://github.com/woocommerce/woocommerce-admin/issues/6352 lands we will be able to do so.

**Comment by psealock** [comment]
I'm pretty sure this is handled by https://github.com/Automattic/wc-calypso-bridge/pull/675 which hides the free extensions tab in Business Details step.
