### ISSUE TITLE
eCommerce Plan "Powered by Woo" obscures update/delete brand buttons

### ISSUE THREAD

**Issue by haszari** [Automattic/wc-calypso-bridge#658]
**Describe the bug**
When running [WooCommerce Brands plugin](https://woocommerce.com/products/brands/), there is a visual issue with `Powered by WooCommerce`  obscuring update/delete brand links. (May be better to log a separate issue.)

<img width="1078" alt="Screenshot on 2021-01-21 at 09-19-02" src="https://user-images.githubusercontent.com/4167300/105782076-a4f49880-5fd8-11eb-9b7e-56acce5c462d.png">

Suggest removing the `Powered by Woo` as it's redundant and inconsistent with standard Woo admin experience.

**To Reproduce**
2. Activate WooCommerce Brands on a WPCOM eCommerce Plan site.
3. `WooCommerce > Products > Brands` .
4. In some circumstances, the `Powered by Woo` obscures brands-related UI.

(Note - I have not attempted to reproduce this, when someone looks at this please update repro instructions!)

**Expected behavior**
WooCommerce Brands should have all functionality available with new nav and in WPCOM eCommerce plan.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by haszari** [comment]
FYI @pmcpinto @timmyc

**Comment by psealock** [comment]
@haszari I can only reproduce this when the new Navigation is turned off. Considering this is for eCommerce plan users who have Navigation turned on, I don't think its worth fixing. What do you think?

**Comment by haszari** [comment]
> I can only reproduce this when the new Navigation is turned off. Considering this is for eCommerce plan users who have Navigation turned on, I don't think its worth fixing. What do you think?

@psealock Sounds reasonable - happy to close 😄 

If there's a lingering issue here someone can log a new issue. Closing 👍
