### ISSUE TITLE
Handle local Calypso development server in `woocommerce_navigation_root_back_url` filter

### ISSUE THREAD

**Issue by mattsherman** [Automattic/wc-calypso-bridge#660]
We should build off of #659 and handle going back to the local Calypso development server (`http://calypso.localhost:3000`) if the referrer starts with `http://calypso.localhost:3000`. In that case, we'd want to go back to `http://calypso.localhost:3000/home/${ slug }`.

This would make development and testing of WooCommerce-related functionality in Calypso less confusing. Because as it is now, you'd be in Calypso on your local server, checking out some changes, click some link to go to WooCommerce in wp-admin, then click the "WordPress Dashboard" link and not realize that you went back to `https://wordpress.com` and not your local Calypso server. I've been burned by things like this many times in the past... "why are my changes taking affect?"... refresh page... "what's going on?"... refresh page... "$&*@#, argh... how'd I get on wordpress.com production/staging!".

/cc @psealock  @joelclimbsthings @joshuatf

**Comment by joelclimbsthings** [comment]
I like this idea a lot. I haven't tried to run Calypso locally as of yet, although anything we can do to bring this closer to the production experience is a big :+1:  from me.

Should be fairly easy to implement as well.
