### ISSUE TITLE
The Bridge can not be installed alongside wpcomsh for testing

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#661]
This item came up during our Cycle 9 2021 retro: p90Yrv-2aP-p2

And I confirmed that when you attempt to upload a zip file of the bridge plugin to an Atomic Ephemeral site for testing, there are conflicts with constants and class names that prevent the bridge from being tested on AE with wpcomsh.

**Comment by xristos3490** [comment]
Closing this as obsolete.
