### ISSUE TITLE
Business plan users (ex-Store UI) - Store Analytics tab not working

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#667]
**Describe the bug**
Happiness received some support tickets from Business plan customers that were using the Store UI reporting that the Store tab in the Stats and Insights page is not working: https://d.pr/i/5SfEh0

**To Reproduce**

1. Use a business plan account with Woo installed
2. Click on the Stats menu item
3. Click on the Store tab

**Expected behavior**
To see the tab as we have in the eComm plan (https://d.pr/i/EF5VsS) or to be redirected to the WooCommerce Analytics page

**Comment by pmcpinto** [comment]
@becdetat do you think it's possible to fix this during cycle 11? I'm assuming that redirecting to the wcadmin analytics page is the easiest approach, but I'd like to get your feedback. Thanks

**Comment by moon0326** [comment]
@pmcpinto @becdetat I signed up for a new business plan and tested it. The store tab worked fine for me. Do you have more details by any chance? Thanks!

![Screen Shot 2021-03-30 at 5.49.18 PM.jpg](https://images.zenhubusercontent.com/5fa082d991c622599eeba31b/1910f84e-11d6-4a3a-9739-03b0d6a02093)

**Comment by becdetat** [comment]
@pmcpinto @moon0326 I also can't reproduce this on a new business plan store

**Comment by pmcpinto** [comment]
Thanks for checking this. Let me see if Happiness can provide more info.

**Comment by becdetat** [comment]
Repro:

- load the page using a site param: `https://wordpress.com/stats/day?site=<YOUR_SITE>.wpcomstaging.com`
- Then click the store stats:

![image](https://user-images.githubusercontent.com/224531/113222404-4eeaec80-92ca-11eb-9ec5-e3e8a9202c37.png)

Then you get redirected to https://wordpress.com/stats/day/store.a8c.com
