### ISSUE TITLE
OBW: Filter To Two Steps

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#68]
Background in first comment: p3fqKv-6Ej-p2

Since we will be utilizing the Woo core OBW for this project, it seems a good first task will be to filter the list of steps, and only include the two we will need. In subsequent tasks we will likely need to modify these two steps further, but this will be a good first step.

`/wp-admin/admin.php?page=wc-setup`

![image](https://user-images.githubusercontent.com/22080/47314165-bd093080-d5f5-11e8-83ec-e77e13e8b9da.png)

Lets keep the first two steps for now - the second step will be combined with the shipping options - design pending.

Filter for this documented(ish) [here](https://github.com/woocommerce/woocommerce/blob/60fafd821d3fff2e7e57df9892c90102650dbe68/includes/admin/class-wc-admin-setup-wizard.php#L258)

**Comment by joshuatf** [comment]
Resolved by https://github.com/Automattic/wc-calypso-bridge/pull/72
