### ISSUE TITLE
Include WCPayments menu item in Business and eComm plan customers using Woo

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/wc-calypso-bridge#686]
**Description:** we want to run this initial test to validate if have WCPayments as a "default" option with a menu item can boost adoption among existing merchants. 

**Acceptance criteria:**
- [x] #688
- [x] #689
- [x] #690
- [x] #691

**Event tracking:**
TBD

**Additional info:**
Project thread: paJDYF-1Yz-p2
Welcome screen mockup w/ financial incentive: paJDYF-1Yz#comment-6585-p2

**Comment by pmcpinto** [comment]
@becdetat I don't know which team will handle this. Let me know if I need to add more details. Thanks

**Comment by becdetat** [comment]
@pmcpinto Currently Ghidora will handle this. cc @samueljseay

**Comment by adrianduffell** [comment]
@pmcpinto @elizaan36 @becdetat I have created a demo video hoping to finalize and declare this as done. Enjoy! 🍿 


https://user-images.githubusercontent.com/9312929/126649100-9ff11bb6-45b2-479a-a176-855b02e5303a.mp4

**Comment by pmcpinto** [comment]
@adrianduffell thanks for sharing the demo. It looks great. Just to confirm, the event tracking is workly properly, right?

cc @oneillo @thenbrent in case you want to take a look at the demo

**Comment by ilyasfoo** [comment]
@pmcpinto I have tested and confirm the following tracks work:

1. On opening the payments welcome page `wcadmin_page_view` with props `{path: "payments_connect_dotcom_test"}`
2. On clicking "Remove and send feedback", `wcadmin_wcpay_exit_survey` with props `{happy: "Yes", install: "No", moreInfo: "No", anotherTime: "Yes", somethingElse: "No", …}`
3. On clicking "Get Started", `wcadmin_wcpay_connect_account_clicked` with props `{wpcom_connection: "No"}`
4. On clicking "Learn more", `wcadmin_wcpay_welcome_learn_more`

Also fyi in case if this is important, if user click on "Just remove woocommerce payments" no track is recorded.

**Comment by thenbrent** [comment]
Looking great! Thanks for the demo @adrianduffell and work on this one @moon0326, @ilyasfoo, and others.

**Comment by pmcpinto** [comment]
Thanks @ilyasfoo 

One additional thing that we should track, in order to have a clear picture of the funnel, is viewing the menu item with the red badge. Is there a way to track this?

**Comment by ilyasfoo** [comment]
@pmcpinto I think that's only partially possible with only wp-admin interface being tracked. Calypso will have the badge displayed but getting it tracked would take a considerable amount of effort since we'd need to build it in a different repo, I estimate to be at least 5. 

Also if the user has WooCommerce navigation there's no red badge displayed, so I'm thinking it could also skew some of the results.

**Comment by pmcpinto** [comment]
Thanks for your feedback. That's a lot of work. Let me think about this during the weekend. 

I just noticed that the starting point in the demo is the wp-admin menu. But AFAIK the Dotcom team unified the menu UI and customers can only use this UI: https://d.pr/i/KmpZNK
Has this flow been tested with this menu UI?

**Comment by ilyasfoo** [comment]
@pmcpinto Yes, we've tested it in the unified menu too, it will look like the following:

![image](https://user-images.githubusercontent.com/3747241/126919446-c797f661-9d25-4d9c-a8ad-58f9c84be719.png)

**Comment by pmcpinto** [comment]
Thanks! @ilyasfoo @adrianduffell it seems that we're ready to ship it, right? 
Can you just give a heads up to wpcom happiness in their p2 (wpcomhappy)? I don't expect a spike in terms of tickets because of this, but it's better to make sure they're aware of this experiment. Thanks.

**Comment by adrianduffell** [comment]
Thanks @pmcpinto!

Yep, we are all ready to ship. It has now been scheduled for [Wednesday, July 28 1AM UTC](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Launch+Bridge&iso=20210728T01&p1=1440).

I'll update Happiness in the meantime!

**Comment by becdetat** [comment]
@adrianduffell if this is ready, can you make sure the ticket is moved to the correct swim land in ZenHub? I use that as my source of truth for determining what's in progress and what is coming up.

Thanks :-)

**Comment by adrianduffell** [comment]
@becdetat Sorry, I didn't post an update here but we moved the deployment to today (Monday).

I'll close this out once it's deployed and tested well.

**Comment by adrianduffell** [comment]
This is now deployed! 🎉  

I'll close it out, which I think puts it in the correct ZenHub swim lane.

**Comment by becdetat** [comment]
Thanks 🥳
