### ISSUE TITLE
Display the WCPayments menu item red badge to US Business/eCommerce plan customers

### ISSUE THREAD

**Issue by samueljseay** [Automattic/wc-calypso-bridge#688]
Add a menu item named "Payments" with a red "1" badge linking to the [Welcome screen](https://github.com/Automattic/wc-calypso-bridge/issues/692).

The menu item should display under the following conditions:

- WC Pay plugin is not installed.
- Store is located in the U.S.
- Store has not [opted out](https://github.com/automattic/wc-calypso-bridge/issues/691). Perhaps add a new WP option to keep this state.

**Comment by samueljseay** [comment]
Copying comments from @ilyasfoo about the required work here:

We'd have to:
- [ ] Add React support in bridge
- [ ] Add a menu item with conditional show/hide - if users disabled it. We'll need to make sure this menu item is also displayed on WooCommerce Navigation.
- [ ] Add the new welcome page with the capability to install WCPay while showing loading/progress, and redirect to wcpaySettings.connectUrl global var after installation.
- [ ] I assume we'd want to track this flow as well since we're bypassing the original track done on WCPay connect page.

**Comment by adrianduffell** [comment]
I've split the Welcome Page & React requirements into their own issues #692 #693.

**Comment by adrianduffell** [comment]
@moon0326 I updated the description with the requirements about how the menu item should conditionally display.

**Comment by moon0326** [comment]
@adrianduffell Thank you Adrian. I will open a new PR with the changes.

**Comment by moon0326** [comment]
@samueljseay @adrianduffell 

Do we also want to include the menu when the WC Payment is installed, but not active?

**Comment by moon0326** [comment]
PR is here https://github.com/Automattic/wc-calypso-bridge/pull/703

**Comment by adrianduffell** [comment]
We went ahead and included the menu when the WC Pay plugin is installed, but not active.

PR #703 closes this.
