### ISSUE TITLE
Reuse one of the financial incentives implemented for the new existing store acquisition experiment

### ISSUE THREAD

**Issue by samueljseay** [Automattic/wc-calypso-bridge#689]
Stores that set up WC Pay should have the "no transaction fees for 3 months" promo applied to their account.

**Comment by samueljseay** [comment]
Copying down comments from @ilyasfoo about required work here:

According to WCPay server code, the promo is applied during connect flow if the user had actioned on any notes. [This](https://github.com/Automattic/woocommerce-payments-server/blob/trunk/server/wp-content/rest-api-plugins/endpoints/wcpay/class-oauth-redirect-controller.php#L206) is the relevant code in the server and [this](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-account.php#L553) is passed from the client. We may be able to force a promo by manually manipulating the `admin_note store` in  `WC_Data_Store` . We also need to know which financial incentive we want to reuse.

**Comment by samueljseay** [comment]
Comments on @adrianduffell :

Still investigating this. Seems like we’d need to apply a discount on the WC Pay account. https://wcpay.wordpress.com/2021/04/27/wcpay-existing-store-acquisition-experiment-v2/

**Comment by ilyasfoo** [comment]
Have we decided which financial incentive we'd want to reuse? cc @pmcpinto

**Comment by pmcpinto** [comment]
Adrian asked me the same yesterday :) I gave feedback here: paJDYF-1Yz#comment-6814-p2

**Comment by moon0326** [comment]
> Copying down comments from @ilyasfoo about required work here:
> 
> According to WCPay server code, the promo is applied during connect flow if the user had actioned on any notes. [This](https://github.com/Automattic/woocommerce-payments-server/blob/trunk/server/wp-content/rest-api-plugins/endpoints/wcpay/class-oauth-redirect-controller.php#L206) is the relevant code in the server and [this](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-account.php#L553) is passed from the client. We may be able to force a promo by manually manipulating the `admin_note store` in `WC_Data_Store` . We also need to know which financial incentive we want to reuse.

@ilyasfoo is correct on that. WC Pay Server checks for the actioned status of a note to determine promo eligibility. This [PR](https://github.com/Automattic/woocommerce-payments-server/pull/835) can be a good reference.
