### ISSUE TITLE
OBW: Calypsoify Styles

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#69]
Again this is fully pending hi-fi designs that @josemarques is currently working on. But until then, perhaps we can explore enqueuing the existing calypsoify styles to see how far that can get us. The enqueuing of the styles can be [seen here in Jetpack](https://github.com/Automattic/jetpack/blob/master/modules/class.jetpack-calypsoify.php#L92-L94)

**Comment by timmyc** [comment]
That is correct, enqueue the base calypsoify stylesheet so we can utilize the classes as needed to make the OBW _feel_ more like calyposo.

**Comment by joshuatf** [comment]
Closing this issue as it looks like the query param will be passed based on the comment here - https://github.com/Automattic/wc-calypso-bridge/pull/75#issuecomment-432383114
