### ISSUE TITLE
Automatically redirect merchants to the KYC flow after they install the extension

### ISSUE THREAD

**Issue by samueljseay** [Automattic/wc-calypso-bridge#690]
The WC Pay welcome screen has a "Get Started" button.

![image](https://user-images.githubusercontent.com/9312929/124141299-e32c4180-dabb-11eb-963b-c0f9c0a7f8e5.png)

This button should install WCPay while showing loading/progress, then redirect to `wcpaySettings.connectUrl` global var after installation.

**Comment by samueljseay** [comment]
I'm estimating this as a 2, because I think based on discussion that once everything else is in place this will be a relatively small task.

@adrianduffell @ilyasfoo could you confirm?

**Comment by adrianduffell** [comment]
Yeah 2 sounds good to me 👍

**Comment by ilyasfoo** [comment]
Adding a detail we had in sprint planning call, we can try to use either the wp.data store `wc/admin/plugins` (the most optimal) or directly to API `/wc-admin/plugins/install`. Business step in OBW would be a good reference

**Comment by ilyasfoo** [comment]
@pmcpinto The existing track in WCPay used to connect is `wcadmin_wcpay_connect_account_clicked`. Do you want to have a different track for when users connect via the wcpay in core experiment? Or maybe an additional prop to differentiate?

**Comment by pmcpinto** [comment]
@ilyasfoo I think that probably having a different event or `wcadmin_page_view` `path` prop is enough. @oneillo what do you think?

**Comment by oneillo** [comment]
@pmcpinto @ilyasfoo - I like the idea of using a new `wcadmin_page_view` prop to distinguish when a user sees the version of this screen in the experiment and keeping the existing track for connecting WCPay the same. I think it better reflects the situation; that a user is seeing this screen that they may not have seen previously, and if they connect, they are taking the same action they would have taken under normal circumstances.

**Comment by ilyasfoo** [comment]
@pmcpinto @oneillo Just to make sure I understood this correctly, do we want to add a new prop `wcadmin_page_view` with the `path` as its value into `wcadmin_wcpay_connect_account_clicked` track event?

Also, note that this new prop will only exist when users connect via this project. The original track in WCPay will not contain this new prop.

**Comment by pmcpinto** [comment]
> @pmcpinto @oneillo Just to make sure I understood this correctly, do we want to add a new prop wcadmin_page_view with the path as its value into wcadmin_wcpay_connect_account_clicked track event?
> Also, note that this new prop will only exist when users connect via this project. The original track in WCPay will not contain this new prop.

@ilyasfoo I think the goal is to add a new value to the `path` prop of `wcadmin_page_view` when the user visits this variation of the welcome screen and keep the event triggered when clicking on the main button:
`wcadmin_page_view`
`path`: `payments_connect_dotcom_test`

Makes sense?

**Comment by ilyasfoo** [comment]
Ok, understood!

**Comment by ilyasfoo** [comment]
The track is added in https://github.com/Automattic/wc-calypso-bridge/pull/709
