### ISSUE TITLE
Allow merchants to remove the WCPayments menu item if they don’t want to adopt our product

### ISSUE THREAD

**Issue by samueljseay** [Automattic/wc-calypso-bridge#691]
The welcome page has a “No thanks” button.

![image](https://user-images.githubusercontent.com/9312929/124137527-56cc4f80-dab8-11eb-95f0-db1b0bb9e458.png)

When this button is pressed, the store should no longer display the Payments menu item. Additionally, an exit survey will appear (issue #694).

**Comment by samueljseay** [comment]
Comments from @adrianduffell copied here:

This looks like part of the welcome page with the “No thanks”. It could be done by adding a new option to track whether the user has opted out, then hiding the menu item if they have.
Looks like there might also be some plans to add an exit survey as well? paJDYF-1Yz-p2#comment-6656

**Comment by mattsherman** [comment]
Moving this to Ghidorah Dev Sprint (looks like it was assigned to Mothra Dev Sprint by accident).

**Comment by pmcpinto** [comment]
> @pmcpinto Could you clarify if an exit survey is needed?

Sorry, I missed this ping. Yes. It’s the best way to collect feedback from customers that don’t want to use WCPayments. And this feedback will be extremely useful if we want to apply the same strategy across all Woo stores.

**Comment by adrianduffell** [comment]
I moved the exit survey out to it own issue #694.

**Comment by moon0326** [comment]
@pmcpinto @adrianduffell When a user closes the exit survey modal, where should we redirect them? I'm thinking we could redirect the user to "My Home" page.
