### ISSUE TITLE
Add WC Pay welcome screen

### ISSUE THREAD

**Issue by adrianduffell** [Automattic/wc-calypso-bridge#692]
![image.png](https://images.zenhubusercontent.com/5f56e5a83c18801db083d2ad/ac338a62-56f2-4c1f-91f0-c2cd8b914612)

 [Figma](https://href.li/?https://www.figma.com/file/7QOkvxzz1ylS3QBS4zqW8R/Payments-experiments?node-id=8537%3A35116)
 
- There is a new [Onboarding package](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/onboarding) containing components that may be able to be re-used here: `WCPayCard`, `WCPayAcceptedMethods`.
- The design also has similarities to the ["Connect" page in WC Pay](https://github.com/Automattic/woocommerce-payments/tree/develop/client/connect-account-page).

React support needs to be added first in #693 .

Ideally a spike should be created for this early so that the buttons can be worked on separately (issues #690, #691).

**Comment by adrianduffell** [comment]
@pmcpinto @elizaan36 Do you have the FAQ content ready for this?

**Comment by pmcpinto** [comment]
> @pmcpinto @elizaan36 Do you have the FAQ content ready for this?

@elizaan36 can you give feedback on this? I'm not finding the Figma file with the latest design, and I'm not sure if it included all the FAQs. Thanks

**Comment by elizaan36** [comment]
We'll need to create the FAQ content. I'll start a shared doc this week.

**Comment by elizaan36** [comment]
Here's a shared doc with some starter questions - https://docs.google.com/document/d/1txfcYxA_1ha8QhOTRdXtZ7QLhq5enIAvxPlNGI1v_X8/edit#

Who would be the best point of contact to help create this on the payments side? I wonder if they have existing FAQ we can use.

**Comment by elizaan36** [comment]
Regarding the help link on this screen, I'm thinking we can include it below the FAQ in the same card.

<img width="680" alt="Screen Shot 2021-07-08 at 11 33 33 AM" src="https://user-images.githubusercontent.com/5121465/124973476-6c71d580-dfe0-11eb-9cf4-cad62d0b0b89.png">

**Comment by pmcpinto** [comment]
> Who would be the best point of contact to help create this on the payments side? I wonder if they have existing FAQ we can use.

@bmccotter can you provide some guidance on this? Thanks!

**Comment by bmccotter** [comment]
@elizaan36  I requested access. Can you also please share with @thenbrent

**Comment by thenbrent** [comment]
> I wonder if they have existing FAQ we can use.

We have a publicly available FAQ here: https://docs.woocommerce.com/document/payments/faq/

If you just want to put this together quickly, you could pull 3-5 from there. Those FAQs are mostly focused on questions people have after using the product though, not before (i.e pre-sales) which would be better here.

Orlando's idea of asking Happiness for common pre-sales questions is a good one (p6q7sZ-8Wb-p2).

If that doesn't yield anything useful, I'd include some of the ones in the doc now along with the FAQs on:

* [What are the fees?](https://docs.woocommerce.com/document/payments/faq/fees/)
* [When will I get paid?](https://docs.woocommerce.com/document/payments/faq/deposit-schedule/)

**Comment by elizaan36** [comment]
Thanks all for the help with putting the FAQ together. I think we can use the top 5 questions in the [shared doc](https://docs.google.com/document/d/1txfcYxA_1ha8QhOTRdXtZ7QLhq5enIAvxPlNGI1v_X8/edit?ts=60e82602#). This includes the top 3 most visited FAQ's currently as well as information about the promotion and plugin compatibility.

**Comment by adrianduffell** [comment]
This is now finished.
