### ISSUE TITLE
Match footer text behaviour with WooCommerce Core

### ISSUE THREAD

**Issue by dougaitken** [Automattic/wc-calypso-bridge#7]
ticket - 771133-zen

Background: Installing WooCommerce on a WordPress.com Business plan should feel identical to WooCommerce on any other host.

Relating to woocommerce/woocommerce/pull/17057 - can we revert or amend woocommerce/wc-api-dev/pull/32 to match? 

The ideal scenario, I can amend the [Footer text](https://docs.woocommerce.com/document/configuring-woocommerce-settings/#section-20) and it will show whatever I want but _not_ a hardcoded `Powered by WooCommerce' appended.

**Comment by juliasydnor** [comment]
Another report: 949252-zen

**Comment by dougaitken** [comment]
I've retested this in `3.3.1` on my atomic site.

* Deleted footer text
* Saved Email settings
* entered new footer text and saved

Text still shows as `Doug Atomic – Powered by WooCommerce`

**Comment by dougaitken** [comment]
I think this is covered by Automattic/wc-calypso-bridge/issues/25 but I defer to @timmyc for confirmation

**Comment by timmyc** [comment]
Correct @dougaitken once we remove the email over-rides all will be happy.

**Comment by timmyc** [comment]
Closing this out now that we are no longer over-riding core email templates - this should no longer be an issue.
