### ISSUE TITLE
Create Calypso/Woo Stylesheet

### ISSUE THREAD

**Issue by timmyc** [Automattic/wc-calypso-bridge#71]
We will likely need to have our own stylesheet to add in a variety of tweaks to ensure all the things in the Calypsoify/Woo experience look good. As such, this task involves creation of a new stylesheet specifically for Calypsoify/Woo that should be enqueued in both the OBW, and when the Calypsoify theme is active for WooCommerce

**Comment by joshuatf** [comment]
@timmyc Do we anticipate a lot of styles?  Should we go ahead and setup node-sass to process SCSS files?

**Comment by timmyc** [comment]
Let's just keep it a generic .css file for now. Looking at [calypsoify itself](https://github.com/Automattic/jetpack/blob/master/modules/calypsoify/style.css) it has a good chunk of styles, but it is still just a .css file.

Also I'd like to keep the build process of this plugin as simple as possible. Currently we tag a release, and update `wpcomsh`'s composer file with the new tagged release on github, and that is it. ( well there are more steps, but this part is simple 😄 )
