### ISSUE TITLE
Add "Launch site" context and CTA to Woo dash for wpcom eComm customers

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/wc-calypso-bridge#720]
Outlined in detail here: pd2qGl-aS-p2

When a customer signs up for an eCommerce plan on WordPress.com they're brought through a few different onboarding flows. Their linear onboarding ends in the WooCommerce dashboard, where we have two concerns:

1) There's no context set for WordPress.com eCommerce customers that their experience is powered by Woo
2) Their site is private until they launch. But there's no indication of this in the Woo dashboard. Only if / when they make it to WordPress.com do we inform them of this

I'm proposing a simple solution on the Woo dashboard (or globally in Woo) that includes a small notice to set the context for items 1 & 2. 

![woo-site-private](https://user-images.githubusercontent.com/214813/126688949-89cc656c-93dc-49e6-81b4-492d37fc01b5.png)

This would only exist for WordPress.com e-commerce customers. 

cc'ing the My Home pod team since we discovered this. @autumnfjeld

**Comment by joshuatf** [comment]
Thanks for the proposal, @jeffgolenski!

This would involve extending this page in the WooCommerce Admin repo as well.  I think a SlotFill approach in the main area or on a per-page basis would be best here as opposed to hard coding this in the WCA repo.

I'll open an issue in WCA to address this.  I'll also write up a p2 post on SlotFill extensibility this week so we can take a deeper dive in @Automattic/isotope on how we want to structure the (many) incoming SlotFills.

**Comment by joshuatf** [comment]
WooCommerce Admin issue created here - https://github.com/woocommerce/woocommerce-admin/issues/8010
