### ISSUE TITLE
Fix WC Pay note not appearing

### ISSUE THREAD

**Issue by moon0326** [Automattic/wc-calypso-bridge#763]
This is a follow-up issue for https://github.com/Automattic/wc-calypso-bridge/pull/756

The note described in the PR does not show up as expected due to the missing cron event.

We used `register_activation_hook` to register the cron event, but it never gets triggered as `wc-calypso-bridge` is a part of MU plugin (wpcomsh). MU plugins do not have activation/deactivation. 

As an alternative, we can use [muplugins_loaded](https://developer.wordpress.org/reference/hooks/muplugins_loaded/) or `plugins_loaded`

**Comment by adrianduffell** [comment]
Closing, this was fixed by https://github.com/Automattic/wc-calypso-bridge/pull/764
