### ISSUE TITLE
Avoid rendering WC Pay Menu if WCA has it already

### ISSUE THREAD

**Issue by moon0326** [Automattic/wc-calypso-bridge#772]
We've been working on moving WC Pay menu into WCA (https://github.com/woocommerce/woocommerce-admin/issues/8062), but we also want to keep the same feature in `wc-calypso-brdige` for those users who do not update to the latest WCA. However, we need to avoid rendering the same WC Pay Menu twice in the bridge and WCA.

Make a change in `wc-calypso-bridge to detect WC Pay Menu from WCA. If detected, avoid adding the menu in `wc-calypso-brdige`

**Comment by mattsherman** [comment]
@moon0326 Are you currently working on this? I see you assigned. If so, please move to the correct pipeline. Thanks!

**Comment by moon0326** [comment]
> @moon0326 Are you currently working on this? I see you assigned. If so, please move to the correct pipeline. Thanks!

Thank you for the reminder 👍
