### ISSUE TITLE
Replace Calypso Home with WooCommerce Home

### ISSUE THREAD

**Issue by xristos3490** [Automattic/wc-calypso-bridge#830]
### Description

This issue aims to replace the current Calypso Home with the WooCommerce Home. As part of this work, we will be introducing two new Tasks to the WooCommerce Home Task List:

- Choose a domain
- Launch your store

Once this is completed, the WooCommerce menu item will point to **WooCommerce > Orders** -- just like WooCommerce used to be before the **WooCommerce > Home** menu item was introduced.

**Comment by PanosSynetos** [comment]
Closed by #852
