### ISSUE TITLE
Free trial site-wide customer facing banner

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#911]
P2: pdibGW-1iQ-p2
Figma: oRIYBgxHeLDtlVrTjINlxf-fi-646%3A29343&t=tA0y6iDCXjGfC6f6-0

![Image](https://user-images.githubusercontent.com/3747241/212799668-eed5bf29-612b-4540-8631-8af0c97f2f97.png)

Add a permanent, customer facing bottom banner with a CTA to pick a free trial plan. I'd recommend to just enqueue a script and style to bridge.

### Acceptance Criteria

1. Add a customer facing banner that appears on all pages.
2. When clicking on "pick a plan", it should redirect to the plans page.

**Comment by moon0326** [comment]
Hey @ilyasfoo,

Do you have link to the `pick a plan` link?

**Comment by chihsuan** [comment]
> Do you have a link to the pick a plan link?

@moon0326 I think it should be a link to this page:

![Screenshot 2023-01-23 at 11 36 37](https://user-images.githubusercontent.com/4344253/213961840-769252a6-f3e8-4ff1-99b1-91e362cb7848.png)

**Comment by ilyasfoo** [comment]
@moon0326 Apologies for missing this. It goes to the plans page as @chihsuan mentioned.
