### ISSUE TITLE
Free trial - Add a new class to handle free trial use cases

### ISSUE THREAD

**Issue by moon0326** [Automattic/wc-calypso-bridge#916]
In order to implement https://github.com/Automattic/wc-calypso-bridge/issues/911 and https://github.com/woocommerce/team-ghidorah/issues/158, it would be ideal to have a dedicated class that handles Free Trial plan use cases.

~We could possibly add a new if statement inside https://github.com/Automattic/wc-calypso-bridge/blob/master/wc-calypso-bridge.php#L80 and require a class.~

It looks like free trial is a subset of ECOM plan with some features disabled according to D94408-code

We can use the following function to check for a free trial.

```
function is_ecommerce_trial() {
	return wpcom_site_has_feature( \WPCOM_Features::ECOMMERCE_MANAGED_PLUGINS ) && ! wpcom_site_has_feature( \WPCOM_Features::INSTALL_PLUGINS );	
}
```

### Acceptance Criteria

1. Add a new class that handles Free Trial plan use cases.

**Comment by moon0326** [comment]
I'll implement it in https://github.com/Automattic/wc-calypso-bridge/issues/911 instead.

**Comment by ilyasfoo** [comment]
FYI I've created an issue to handle orders and marketing screen https://github.com/Automattic/wc-calypso-bridge/issues/918
