### ISSUE TITLE
eCommerce Navigation: Home redirect not working when Jetpack SSO is off

### ISSUE THREAD

**Issue by kriskorn** [Automattic/wc-calypso-bridge#923]
## Quick summary

When Jetpack SSO is deactivated and a customer has not authenticated WP Admin log in for their site, then the redirection to WooCommerce Home does not work and it displays a WP Admin log in page. If the Coming Soon mode is enabled, then it actually redirects to a Coming Soon page. 

## Steps to reproduce
1. Make sure you do not have a WP Admin log in cookie for your eCommerce plan site in your browser.
2. Deactivate Jetpack SSO via Calypso by going to Settings -> Security. 
3. Click a WP Admin link in the left sidebar.

## What you expected to happen
Not quite sure. The possible solution is to redirect to Calypso Home instead of WooCommerce Home, when Jetpack SSO is deactivated. Though, a customer should not be redirected to a log in page. 

## What actually happened

**Coming Soon Enabled**
Customer is redirected to a Coming Soon page and no WP Admin log in is shown.
*This seems to depend on a cookie if I am correct, so might not always show.* 

**Coming Soon Disabled**
Customer is redirected to a WP Admin log in page. 

### Context
p1674197330375039-wpcom-support

### Platform (Simple, Atomic, or both?)
Atomic

### Reproducibility
Consistent

### Severity
Some (< 50%)

### Available workarounds?
Yes & No. If you know the direct URLs for Calypso pages, you can access them. However, customer cannot normally manage their site in Calypso, meaning they cannot access vital pages like Hosting Configuration. 

@Automattic/somewherewarm

**Comment by Nic-Sevic** [comment]
This happened with another user here: 6175368-zd-woothemes

To clarify, requiring SSO to be on is not a good workaround in many cases. If a user doesn't want to use SSO or has any sort of membership site which handles logins, their dashboard is effectively broken.

**Comment by PanosSynetos** [comment]
@xristos3490 is your PR relevant to what happened to the above ticket?

> User can\'t access pages/posts and other pages. It gets redirected to the wp-admin login page. This happened after upgrading to eCommerce.

> Tried reconnecting JP. Getting the following errors: Unknown user in /wordpress/plugins/jetpack/11.7-a.3/sal/class.json-api-post-base.php on line 782

**Comment by madisoncmiller** [comment]
Any updates on this?

**Comment by warrendholmes** [comment]
@xristos3490 Just an FYI that I've updated the team here to SomewhereWarm from Serenity since you're handling it.
