### ISSUE TITLE
Free trial payment restrictions

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/wc-calypso-bridge#924]
As described in 
- peapX7-1rw-p2 , 
- peapX7-1xk-p2

in free trial, payments will be blocked for non-admin users

**Comment by that-mike-bal** [comment]
@FlorianBru will help provide design/banner copy for payment gateways screen to inform the user that if they want to use a gateway outside of the three we support, they will be able to upload/integrate once they are on the paid plan. 

We should postpone any whitelist work tied to support outside of our core 3 payment gateways to post launch. @PanosSynetos  might be worth putting a different issue on the backlog for just that work.

**Comment by that-mike-bal** [comment]
Fluffy Fox also says we should hide some of the settings at the bottom of the page - Not a big deal.
