### ISSUE TITLE
Free trial extension: Disabled tasks accordion component

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#931]
Free trial disabled tasklist accordion component

## User Story

> As a free trial user, 
> I want to see tasks unavailable to me as a preview
> so that I'm able to know other setup tasks that will be made available after purchasing

## Acceptance Criteria

```
Feature: Display accordion component
Given the user is on a free trial plan
When the user views WooCommerce homescreen
Then show accordion component
```

```
Feature: Toggle accordion component
Given the user is on a free trial plan and views accordion component
When the user clicks "Upgrade to a paid plan to unlock the next tasks"
Then toggle accordion to expand or contract
```

```
Feature: Click on "Sign up for a plan" button
Given the user is on a free trial plan and views accordion component
When the user clicks on "Sign up for a plan" button
Then navigate to plans page (ex: https://wordpress.com/plans/sitenamehere)
```

```
Feature: Hide accordion component
Given the user is NOT on a free trial plan
When the user views WooCommerce homescreen
Then hide accordion component
```

## Other details

Figma: oRIYBgxHeLDtlVrTjINlxf-fi-646%3A29343

![Image](https://user-images.githubusercontent.com/3747241/215648310-8e60d5f4-9301-4ddc-a7de-e91e986c06ec.png)

Related extensibility PR: https://github.com/woocommerce/woocommerce/pull/36527

**Comment by moon0326** [comment]
Hey @ilyasfoo, 

Do we always display Grow your business and Launch your store and start selling! or do we need to detect ECOM plan only tasks and list them 🤔 ?

**Comment by ilyasfoo** [comment]
Hey, @moon0326! 

As far as I know, both the business plan and ECOM plan would have the task since they have similar capabilities. So I don't think we need to detect for ECOM plan, the free trial plan should be sufficient.

**Comment by moon0326** [comment]
> 

I assume we need to disable `Grow your business` and `Launch your store and start selling!` tasks and list them under the accordion in that case?

**Comment by ilyasfoo** [comment]
> I assume we need to disable Grow your business and Launch your store and start selling! tasks and list them under the accordion in that case?

I believe "Launch your store" task will be disabled by Serenity in this PR: https://github.com/Automattic/wc-calypso-bridge/pull/937, and disabling "Grow your business" will be implemented in the custom tasks issue.

Thus, we could implement just the accordion for this issue. I think hardcoding them into the accordion should suffice for now, but a follow-up could be to obtain the tasks' names somehow.
