### ISSUE TITLE
Free trial extension: Add product changes

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#934]
Related spike: https://github.com/woocommerce/team-ghidorah/issues/171

We should use JavaScript/jQuery to remove components and update copies.

## Acceptance Criteria

Customize add products screen by:

1. Remove Pinterest tab
2. Remove "Like & Share" card
3. Modify copies for "Channel visibility" card
    - Description: `To sync your products directly to Google, manage your product feed, and create Google Ad campaigns, all you need to do is sign up for a plan.`
    - CTA: `Upgrade now`
    - URL: Plan URL, `https://wordpress.com/plans/sitenamehere`

## Other details

Figma: oRIYBgxHeLDtlVrTjINlxf-fi-646%3A29343

![Image](https://user-images.githubusercontent.com/3747241/216618162-60b28822-0821-4615-b349-4f273d965230.png)

**Comment by ilyasfoo** [comment]
This can be skipped

**Comment by daledupreez** [comment]
This should be handled as part of Automattic/dotcom-forge#1560, where we want to ensure that the marketing plugins are installed but not activated on free trial sites.
