### ISSUE TITLE
Free Trial: WooCommerce Marketplace Restrictions

### ISSUE THREAD

**Issue by manospsyx** [Automattic/wc-calypso-bridge#944]
### Description

Merchants using the Free Trial should:

- Understand that they can later add functionality through Extensions.
- Browse extensions and see what is available. 
- Be prompted to upgrade in order to do so.

The Woo Marketplace catalog under *Extensions > Discover* solves the discovery and installation problem on self-hosted Woo stores, in a way that relies on a hand-off process between their dashboard and WooCommerce.com. 

Keeping in mind that users can/may always visit the WooCommerce Marketplace directly, there are two approaches to restrict Extension purchases while allowing merchants to browse:

1. Prevent users from browsing the Marketplace catalog in their dashboard, show a notice to inform them about the limitation(s) in place & prompt them to upgrade, and point them to the Marketplace archive on WooCommerce.com. 

In a nutshell, the idea here is to replace the in-product/dashboard catalog with a placeholder page that sends users off to WooCommerce.com. 

2. Let users browse the Marketplace catalog in their dashboard, show a notice to inform them about the limitation(s) in place & prompt them to upgrade, and prevent purchases on the WooCommerce.com side once they decide to view details for an Extension.

This requires us to implement restrictions on the WooCommerce.com side when merchants decide to view details for an Extension they are interested in. 

The problems with this approach:

- Effort/time. 
- Merchants can always purchase Extensions by visiting WooCommerce.com directly. 

Given that (2)

- doesn't really provide a robust, universal way to solve the problem; and
- ultimately, we want to allow merchants on the Free Trial to install white-listed Extensions (and not necessarily pay for them);

I would propose that we move with (1).

**Comment by that-mike-bal** [comment]
I agree, let's go with 1 for now and treat marketplace experience as a follow up project. I'd love to see what @FlorianBru pulls together for handling dotcom marketplace and Woo marketplace in parallel

**Comment by FlorianBru** [comment]
Brief summary of what has been discussed for the MVP last week: We will implement a landing page for the Extensions section. So browsing and managing extensions are disabled while on a free plan.

But I see this treatment only as a temporary solution until we aligned on our way forward (reducing friction, avoiding duplicated marketplaces ...)

@manospsyx @that-mike-bal @xristos3490

**Comment by xristos3490** [comment]
> We will implement a landing page for the Extensions section. So browsing and managing extensions are disabled while on a free plan.

This is addressed in https://github.com/Automattic/wc-calypso-bridge/pull/990
