### ISSUE TITLE
Free trial: Marketing screen takeover

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#953]
We've decided to replace existing marketing screen.

1. Marketing screen should be replaced with a new landing page
2. Hide existing marketing menu

## User Story

> As a free trial user, 
> I want to be informed of what features are available in marketing
> so that I'm able to be informed before purchasing a plan

## Acceptance Criteria

```
Feature: Hide original marketing menu
Given the user is on a free trial plan
When the user views sidebar menu
Then it should not display the original marketing menu
Then it should display a new "marketing" item with a link to the landing page
```

```
Feature: Click on marketing on sidebar menu
Given the user is on a free trial plan
When the user clicks "Marketing" on sidebar menu
Then navigate to the landing page
```

```
Feature: Click on "Upgrade now" buttons
Given the user is on a free trial plan
When the user clicks on "Upgrade now" button
Then navigate to plans page (ex: https://wordpress.com/plans/sitenamehere)
```

```
Feature: Click on "Try AutomateWoo" button
Given the user is on a free trial plan
When the user clicks on "Try AutomateWoo" button
Then navigate to AutomateWoo dashboard "/wp-admin/admin.php?page=automatewoo-dashboard"
```

```
Feature: Click on "Create digital gift cards" button
Given the user is on a free trial plan
When the user clicks on "Try AutomateWoo" button
Then navigate to gift cards extension dashboard (TBC)
```

## Other details

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-1096%3A24909

![Image](https://user-images.githubusercontent.com/3747241/220125748-1267ac3d-e31a-4302-a64c-949c5a31eed5.png)

![Image](https://user-images.githubusercontent.com/3747241/220125850-4538c624-88cc-46cd-95d2-0d7532db0d7c.png)

**Comment by that-mike-bal** [comment]
Dear, @FlorianBru  - please update with your magic.

**Comment by moon0326** [comment]
>Then navigate to gift cards extension dashboard (TBC)

@ilyasfoo ✋ Do you know when we can get the link for the Gift Card extension?
