### ISSUE TITLE
Free trial: Ensure tasklists are re-enabled after a user purchases a plan

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#954]
Since users are unable to finish all tasks during free trial, we should re-enable tasklists in case it was dismissed during free trial.

## User Story

> As a paid user, 
> I want to know important steps I need to do for setting up my store after purchasing a plan
> so that I'm able to finish setting up my store

## Acceptance Criteria

```
Feature: Re-enable taskslists
Given the user was on a free trial plan, finished and dismissed setup tasks
When the user purchases a plan
Then system should re-enable tasklists
```

**Comment by ilyasfoo** [comment]
Hi @daledupreez, for re-enabling tasklists after users purchase a plan, do we have a place to "hook" our logic to enable a site option?

**Comment by ilyasfoo** [comment]
A workaround is to have an option that flags free trial initially and then could be used to check if the site has converted to paid plan and then hook our logic around that conversion, removing the flag after. Not optimal though.

**Comment by daledupreez** [comment]
@ilyasfoo, I think this is something we should handle from WPCOM's side, as we will have all the site and purchase information available to us, while having that occur downstream will be much more complicated.

Do you know how we track/flag/record completion of the task list? My suspicion is that it's via a site option, and my thinking was that our code would simply remove the option at the time the user upgrades. Specific tasks would remain complete, but there would be additional tasks present in the list.

**Comment by ilyasfoo** [comment]
@daledupreez Sounds good!

> Do you know how we track/flag/record completion of the task list? My suspicion is that it's via a site option, and my thinking was that our code would simply remove the option at the time the user upgrades. Specific tasks would remain complete, but there would be additional tasks present in the list.

In order to "reset" tasklists' states, deleting these options should be sufficient:

1. `woocommerce_task_list_hidden_lists`: List of tasklists that are hidden.
2. `woocommerce_task_list_completed_lists`: List of tasklists that are completed. Used for sending tracks after a tasklist is completed. Deleting it would allow for the track to be fired again.
1. `woocommerce_task_list_keep_completed`: Flag to keep showing tasklists even after completion. Deleting this option would allow users to get the [completion component](https://github.com/Automattic/wc-calypso-bridge/issues/928) to show again if they've enabled to force-show after initial completion.

**Comment by ilyasfoo** [comment]
@daledupreez Should I close this issue, or somehow would you like to transfer it to Serenity?

**Comment by daledupreez** [comment]
@ilyasfoo, let's keep it open -- I've added the issue to our sprint board.

**Comment by daledupreez** [comment]
I am working on this in D102210-code - please feel free to take a look at the implementation, especially to confirm that the three options we want to delete are:
 * `woocommerce_task_list_hidden_lists`
 * `woocommerce_task_list_completed_lists`
 * `woocommerce_task_list_keep_completed`

**Comment by ilyasfoo** [comment]
Options LGTM!

**Comment by daledupreez** [comment]
I expanded this list in the final diff, which was just deployed in D102210-code:
 * `woocommerce_task_list_complete`
 * `woocommerce_task_list_completed_lists`
 * `woocommerce_task_list_dismissed_tasks`
 * `woocommerce_task_list_hidden_lists`
 * `woocommerce_task_list_keep_completed`
 * `woocommerce_task_list_tracked_completed_tasks`

Please re-open and let me know if we should be changing any of the options we delete.

**Comment by ilyasfoo** [comment]
@daledupreez  Looks good to delete the additional ones, thanks for adding them in! 👍
