### ISSUE TITLE
Task: Update tax task to handle when the recommended plugin is installed

### ISSUE THREAD

**Issue by daledupreez** [Automattic/wc-calypso-bridge#996]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/Automattic/wc-calypso-bridge/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

As discussed in this Slack thread, p1677228037977309/1677175126.823349-slack-CNA89KY6M , we need to be able to detect when the AvaTax plugin is already installed, but not yet activated. When that is the case, the Tax task in the onboarding checklist needs to trigger activation of the plugin rather than redirecting out to WooCommerce.com.

### Acceptance criteria

1. Copy AvaTax from tax task in core to [bridge](https://github.com/Automattic/wc-calypso-bridge/tree/master/src/free-trial/tax).
2. Detect AvaTax plugin is installed. If it is, change the CTA action to activate the plugin and then [navigate to AvaTax](https://github.com/woocommerce/woocommerce/blob/6b099f917be2f65f5d3d5be80bb9fddfc47cba7b/plugins/woocommerce-admin/client/tasks/fills/tax/avalara/card.tsx#L51-L62) settings screen. Otherwise, it should have the same behaviour.

**Comment by daledupreez** [comment]
cc @ilyasfoo

**Comment by ilyasfoo** [comment]
Thanks, @daledupreez. I assume we also need to bring back AvaTax to the tax task, correct?

**Comment by daledupreez** [comment]
Yes, that's correct, @ilyasfoo -- we are going to be installing AvaTax (but not activating it) once we land D102721-code, which should be later today.

**Comment by ilyasfoo** [comment]
Thanks for confirming @daledupreez, I've edited the issue to add acceptance criteria. Also, would the plugin be guaranteed to be installed? I assume there are only 2 cases we need to handle:

1. Installed but not activated - activate and then navigate user to AvaTax settings
2. Installed and activated - navigate user to AvaTax settings
3. Not installed - not currently handled.

**Comment by chihsuan** [comment]
Hey @daledupreez I'm working on this but getting a 403 error when I try to activate the AvaTax plugin as a free trial user.

It seems that a free trial user can't activate plugins, or there’s something that I missed?

```json
{"code":"woocommerce_rest_cannot_update","message":"Sorry, you cannot manage plugins.","data":{"status":403}}
```

**Comment by chihsuan** [comment]
Hi @daledupreez Any thoughts on this?

**Comment by daledupreez** [comment]
@chihsuan, I have to relevant items:
* Automattic/wpcomsh#1301 - this should fix both this specific issue and some others
* Automattic/wp-calypso#373541 - another closely related issue
