### ISSUE TITLE
Free trial: Customize "Add store details" task completion

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#997]
This is a follow-up to https://github.com/Automattic/woocommerce.com/pull/16136.

When we pass store country data from NUX profiler, we could set `Add store details` task as completed to encourage users to continue with the next tasks.

### Acceptance criteria

1. Wait for NUX profiler transfer to be working. https://github.com/Automattic/wp-calypso/issues/72716
1. We'd need to change the "Add store details" task completion logic to only store country, similar to what we did in [payments task](https://github.com/Automattic/wc-calypso-bridge/blob/26ac35a7fd469ef905cd3dc291600a2989771403/includes/class-wc-calypso-bridge-free-trial-payment-task.php#L41-L51)
1. Remove the [filter](https://github.com/Automattic/wc-calypso-bridge/blob/26ac35a7fd469ef905cd3dc291600a2989771403/includes/class-wc-calypso-bridge-woocommerce-admin-features.php#L69-L81) that overrides onboarding profile option

**Comment by that-mike-bal** [comment]
@ilyasfoo  looks like this is ready to get picked up again.

**Comment by ilyasfoo** [comment]
Thanks for the ping! @moon0326 picked it up and it's now in review 🥳
