### ISSUE TITLE
Free trial: Update homescreen header message for 0 task

### ISSUE THREAD

**Issue by ilyasfoo** [Automattic/wc-calypso-bridge#998]
Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-1691%3A16306

Update homescreen header tasks copies. 

https://github.com/Automattic/wc-calypso-bridge/blob/31d4065f96df3946ba100712bb3f10f708e13fdf/src/homescreen-progress-header/progress-header.tsx#L58

### Acceptance criteria

1. When 0 tasks are complete, message should be `You’re almost ready to start selling! Follow these steps to set up your test store.`

**Comment by moon0326** [comment]
Looks like this is already done in https://github.com/Automattic/wc-calypso-bridge/pull/987?

I see the updated copy.

Could you confirm @ilyasfoo ?

**Comment by ilyasfoo** [comment]
Ah, I thought there was a change. Thanks for noticing, @moon0326! I'll close this issue
